#!/usr/bin/env bash
set -e
CSPROJ="fieldroutes-api-client.csproj"
SOURCE="$2"
[ -n "$SOURCE" ] && [ "$SOURCE" != "message" ] && exit 0

MSG=$(cat "$1")
VERSION=$(sed -n 's/.*<Version>\([^<]*\)<\/Version>.*/\1/p' "$CSPROJ" | head -1)
MAJOR=$(echo "$VERSION" | awk -F. '{print $1}')
MINOR=$(echo "$VERSION" | awk -F. '{print $2}')
PATCH=$(echo "$VERSION" | awk -F. '{print $3}')

if [[ "$MSG" == *"[major]"* ]]; then
  MAJOR=$((MAJOR+1)); MINOR=0; PATCH=0
elif [[ "$MSG" == *"[minor]"* ]]; then
  MINOR=$((MINOR+1)); PATCH=0
elif [[ "$MSG" == *"[bump]"* ]]; then
  PATCH=$((PATCH+1))
else
  exit 0
fi

sed -i '' "s|<Version>$VERSION</Version>|<Version>$MAJOR.$MINOR.$PATCH</Version>|" "$CSPROJ"
git add "$CSPROJ"
