// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTaskSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key.</summary>
    public int? TaskIDs { get; set; }
    public int? OfficeID { get; set; }
    public int? OfficeIDs { get; set; }
    /// <summary>CustomerID the task relates to.</summary>
    public int? CustomerID { get; set; }
    /// <summary>EmployeeID who created the task</summary>
    public int? AddedBy { get; set; }
    /// <summary>EmployeeID the task is assigned to</summary>
    public int? AssignedTo { get; set; }
    /// <summary>EmployeeID who completed the task</summary>
    public int? CompletedBy { get; set; }
    /// <summary>Type of task: 0 - Task, 1 - Alert</summary>
    public int? Type { get; set; }
    /// <summary>Time the task or alert is due.</summary>
    public string? DueDate { get; set; }
    /// <summary>Time the task or alert was added.</summary>
    public string? DateAdded { get; set; }
    /// <summary>Category ID of the task</summary>
    public int? Category { get; set; }
    /// <summary>ReferenceID for the task. (e.g. subscriptionID that it relates to)</summary>
    public int? ReferenceID { get; set; }
    /// <summary>Phone number associated with the task</summary>
    public string? Phone { get; set; }
    /// <summary>Time the task was last updated.</summary>
    public string? DateUpdated { get; set; }
    /// <summary>Status of the task. (0-Pending, 1-Completed, 2-In Use, 3-Urgent)</summary>
    public int? Status { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (TaskIDs is not null) d["taskIDs"] = TaskIDs;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (AddedBy is not null) d["addedBy"] = AddedBy;
        if (AssignedTo is not null) d["assignedTo"] = AssignedTo;
        if (CompletedBy is not null) d["completedBy"] = CompletedBy;
        if (Type is not null) d["type"] = Type;
        if (DueDate is not null) d["dueDate"] = DueDate;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (Category is not null) d["category"] = Category;
        if (ReferenceID is not null) d["referenceID"] = ReferenceID;
        if (Phone is not null) d["phone"] = Phone;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (Status is not null) d["status"] = Status;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
