// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesDocumentSearchParameters
{
    public int? UploadIDs { get; set; }
    public int? OfficeIDs { get; set; }
    public int? OfficeID { get; set; }
    /// <summary>customerID associated with the document</summary>
    public int? CustomerIDs { get; set; }
    /// <summary>customerID associated with the document</summary>
    public int? CustomerID { get; set; }
    /// <summary>appointmentID associated with the document</summary>
    public int? AppointmentIDs { get; set; }
    /// <summary>appointmentID associated with the document</summary>
    public int? AppointmentID { get; set; }
    /// <summary>formTemplateID for pulling specific form types</summary>
    public int? FormTemplateID { get; set; }
    public string? DateAdded { get; set; }
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (UploadIDs is not null) d["uploadIDs"] = UploadIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (AppointmentIDs is not null) d["appointmentIDs"] = AppointmentIDs;
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (FormTemplateID is not null) d["formTemplateID"] = FormTemplateID;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
