// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesReviewSearchParameters
{
    public int? FeedbackIDs { get; set; }
    public int? OfficeIDs { get; set; }
    public int? CustomerIDs { get; set; }
    public int? AppointmentIDs { get; set; }
    public string? Date { get; set; }
    public int? StarRating { get; set; }
    public int? Favorable { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (FeedbackIDs is not null) d["feedbackIDs"] = FeedbackIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (AppointmentIDs is not null) d["appointmentIDs"] = AppointmentIDs;
        if (Date is not null) d["date"] = Date;
        if (StarRating is not null) d["starRating"] = StarRating;
        if (Favorable is not null) d["favorable"] = Favorable;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
