// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesServicePlanRoundSearchParameters
{
    public int? OfficeIDs { get; set; }
    /// <summary>Default: (0,1). 0: Frozen and no longer being placed in the job pool, 1: Active, -3: Lead</summary>
    public int? Active { get; set; }
    /// <summary>Customer who owns this subcscription</summary>
    public int? CustomerIDs { get; set; }
    /// <summary>Unique Identifier for this Subscription</summary>
    public int? SubscriptionIDs { get; set; }
    /// <summary>The user who is being credited for this sale. Used in stats and commissions reporting</summary>
    public int? SoldBy { get; set; }
    /// <summary>The employee ID of the preferred tech</summary>
    public int? PreferredTech { get; set; }
    /// <summary>Date this subscription was created / added / sold</summary>
    public string? DateAdded { get; set; }
    /// <summary>Date this subscription was cancelled</summary>
    public string? DateCancelled { get; set; }
    /// <summary>Last date that something was changed on this subscription.</summary>
    public string? DateUpdated { get; set; }
    /// <summary>The recurring service type to be scheduled for this subscription</summary>
    public int? ServiceType { get; set; }
    /// <summary>The recurring service type to be scheduled for this subscription</summary>
    public int? ServiceID { get; set; }
    /// <summary>The service frequency of this subscription. &gt;0: The number of days, if it is divisible by 30 it is the number of months, -3: Custom Schedule</summary>
    public int? Frequency { get; set; }
    /// <summary>When this subscription is due for their next service</summary>
    public string? DueDate { get; set; }
    /// <summary>When the last service was completed</summary>
    public string? LastCompleted { get; set; }
    public string? DateUpdatedStart { get; set; }
    public string? DateUpdatedEnd { get; set; }
    public string? DateAddedStart { get; set; }
    public string? DateAddedEnd { get; set; }
    /// <summary>The contract ID signed for the subscription</summary>
    public int? ContractIDs { get; set; }
    /// <summary>The date the lead was closed</summary>
    public string? LeadDateClosed { get; set; }
    /// <summary>The date the lead was assigned</summary>
    public string? LeadDateAssigned { get; set; }
    /// <summary>The stageID of the lead</summary>
    public int? LeadStageID { get; set; }
    /// <summary>The employeeID the lead was assigned to</summary>
    public int? LeadAssignedTo { get; set; }
    /// <summary>The employeeID who added the lead</summary>
    public int? LeadAddedBy { get; set; }
    /// <summary>The date the lead was added</summary>
    public string? LeadDateAdded { get; set; }
    /// <summary>The date the lead was last updated</summary>
    public string? LeadUpdated { get; set; }
    /// <summary>The sourceID of the lead</summary>
    public int? LeadSourceID { get; set; }
    /// <summary>The sourceID of the subscription</summary>
    public int? SourceID { get; set; }
    /// <summary>The date that the next service is due</summary>
    public string? NextService { get; set; }
    /// <summary>RegionID of the subscription</summary>
    public int? RegionID { get; set; }
    /// <summary>Date for last service of subscription type</summary>
    public string? LastRegularServiceDate { get; set; }
    /// <summary>Last regular service status</summary>
    public int? LastRegularServiceStatus { get; set; }
    /// <summary>Set as 1 if the subscription is connected to sentricon</summary>
    public int? SentriconConnected { get; set; }
    /// <summary>Sentricon Site ID or null if not connected to Sentricon</summary>
    public string? SentriconSiteID { get; set; }
    /// <summary>Next billing date for the subscription</summary>
    public string? NextBillingDate { get; set; }
    public int? ParentID { get; set; }
    /// <summary>The template type associated with the service type</summary>
    public string? TemplateType { get; set; }
    /// <summary>Last appointment of the subscription</summary>
    public string? LastAppointment { get; set; }
    /// <summary>Service plan round description/abbreviation</summary>
    public string? Description { get; set; }
    /// <summary>Date this service round can start being serviced</summary>
    public string? StartDate { get; set; }
    /// <summary>Last date that this service round can be serviced</summary>
    public string? EndDate { get; set; }
    /// <summary>The skip/omit status for the round</summary>
    public string? Skipped { get; set; }
    /// <summary>The date this round was skipped or omitted</summary>
    public string? DateSkipped { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Active is not null) d["active"] = Active;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (SubscriptionIDs is not null) d["subscriptionIDs"] = SubscriptionIDs;
        if (SoldBy is not null) d["soldBy"] = SoldBy;
        if (PreferredTech is not null) d["preferredTech"] = PreferredTech;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (DateCancelled is not null) d["dateCancelled"] = DateCancelled;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (ServiceType is not null) d["serviceType"] = ServiceType;
        if (ServiceID is not null) d["serviceID"] = ServiceID;
        if (Frequency is not null) d["frequency"] = Frequency;
        if (DueDate is not null) d["dueDate"] = DueDate;
        if (LastCompleted is not null) d["lastCompleted"] = LastCompleted;
        if (DateUpdatedStart is not null) d["dateUpdatedStart"] = DateUpdatedStart;
        if (DateUpdatedEnd is not null) d["dateUpdatedEnd"] = DateUpdatedEnd;
        if (DateAddedStart is not null) d["dateAddedStart"] = DateAddedStart;
        if (DateAddedEnd is not null) d["dateAddedEnd"] = DateAddedEnd;
        if (ContractIDs is not null) d["contractIDs"] = ContractIDs;
        if (LeadDateClosed is not null) d["leadDateClosed"] = LeadDateClosed;
        if (LeadDateAssigned is not null) d["leadDateAssigned"] = LeadDateAssigned;
        if (LeadStageID is not null) d["leadStageID"] = LeadStageID;
        if (LeadAssignedTo is not null) d["leadAssignedTo"] = LeadAssignedTo;
        if (LeadAddedBy is not null) d["leadAddedBy"] = LeadAddedBy;
        if (LeadDateAdded is not null) d["leadDateAdded"] = LeadDateAdded;
        if (LeadUpdated is not null) d["leadUpdated"] = LeadUpdated;
        if (LeadSourceID is not null) d["leadSourceID"] = LeadSourceID;
        if (SourceID is not null) d["sourceID"] = SourceID;
        if (NextService is not null) d["nextService"] = NextService;
        if (RegionID is not null) d["regionID"] = RegionID;
        if (LastRegularServiceDate is not null) d["lastRegularServiceDate"] = LastRegularServiceDate;
        if (LastRegularServiceStatus is not null) d["lastRegularServiceStatus"] = LastRegularServiceStatus;
        if (SentriconConnected is not null) d["sentriconConnected"] = SentriconConnected;
        if (SentriconSiteID is not null) d["sentriconSiteID"] = SentriconSiteID;
        if (NextBillingDate is not null) d["nextBillingDate"] = NextBillingDate;
        if (ParentID is not null) d["parentID"] = ParentID;
        if (TemplateType is not null) d["templateType"] = TemplateType;
        if (LastAppointment is not null) d["lastAppointment"] = LastAppointment;
        if (Description is not null) d["description"] = Description;
        if (StartDate is not null) d["startDate"] = StartDate;
        if (EndDate is not null) d["endDate"] = EndDate;
        if (Skipped is not null) d["skipped"] = Skipped;
        if (DateSkipped is not null) d["dateSkipped"] = DateSkipped;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
