// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesFormSearchParameters
{
    public int? FormIDs { get; set; }
    public int? OfficeIDs { get; set; }
    public int? CustomerID { get; set; }
    /// <summary>The date the form was signed.</summary>
    public string? DateSigned { get; set; }
    /// <summary>The date the form was added.</summary>
    public string? DateAdded { get; set; }
    /// <summary>The unitID associated with the form.</summary>
    public int? UnitID { get; set; }
    /// <summary>The employeeID who created the form.</summary>
    public int? EmployeeID { get; set; }
    /// <summary>State of the document e.g. WIP, COMPLETED</summary>
    public int? DocumentState { get; set; }
    /// <summary>ID of the template this form was created from</summary>
    public int? FormTemplateID { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (FormIDs is not null) d["formIDs"] = FormIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (DateSigned is not null) d["dateSigned"] = DateSigned;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (UnitID is not null) d["unitID"] = UnitID;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (DocumentState is not null) d["documentState"] = DocumentState;
        if (FormTemplateID is not null) d["formTemplateID"] = FormTemplateID;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
