// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesNoteSearchParameters
{
    public int? NoteIDs { get; set; }
    public int? OfficeIDs { get; set; }
    public int? CustomerIDs { get; set; }
    public string? Date { get; set; }
    public string? DateAdded { get; set; }
    public int? TypeIDs { get; set; }
    public int? EmployeeIDs { get; set; }
    public string? Content { get; set; }
    public int? CancellationReason { get; set; }
    public int? ReferenceID { get; set; }
    /// <summary>Last date this note record was updated.</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (NoteIDs is not null) d["noteIDs"] = NoteIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (Date is not null) d["date"] = Date;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (TypeIDs is not null) d["typeIDs"] = TypeIDs;
        if (EmployeeIDs is not null) d["employeeIDs"] = EmployeeIDs;
        if (Content is not null) d["content"] = Content;
        if (CancellationReason is not null) d["cancellationReason"] = CancellationReason;
        if (ReferenceID is not null) d["referenceID"] = ReferenceID;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
