// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAccessControlSearchParameters
{
    /// <summary>Primary key</summary>
    public int? EmployeeID { get; set; }
    /// <summary>Primary key</summary>
    public int? EmployeeIDs { get; set; }
    /// <summary>0: Custom Access Control Profile per user. Otherwise, ID of defined Access Control Profiles</summary>
    public int? AccessControlProfileID { get; set; }
    /// <summary>Administrator</summary>
    public int? Admin { get; set; }
    /// <summary>0: Custom Access Control Profile per user. Otherwise, ID of defined Access Control Profiles</summary>
    public int? AccessControlProfileIDs { get; set; }
    /// <summary>officeID of the profile</summary>
    public int? OfficeID { get; set; }
    /// <summary>officeID of the profile</summary>
    public int? OfficeIDs { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (EmployeeIDs is not null) d["employeeIDs"] = EmployeeIDs;
        if (AccessControlProfileID is not null) d["accessControlProfileID"] = AccessControlProfileID;
        if (Admin is not null) d["admin"] = Admin;
        if (AccessControlProfileIDs is not null) d["accessControlProfileIDs"] = AccessControlProfileIDs;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
