// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerSourceSearchParameters
{
    /// <summary>Primary key</summary>
    public int? SourceID { get; set; }
    /// <summary>Primary key alias</summary>
    public int? SourceIDs { get; set; }
    /// <summary>Primary key alias</summary>
    public int? CustomerSourceID { get; set; }
    /// <summary>Office ID region belongs to</summary>
    public int? OfficeID { get; set; }
    /// <summary>Office ID region belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Name of the source</summary>
    public string? Source { get; set; }
    /// <summary>Set as 1 if this is a default source for the mobile app</summary>
    public int? SalesRoutesDefault { get; set; }
    /// <summary>Visibility of the source</summary>
    public string? Visible { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (SourceID is not null) d["sourceID"] = SourceID;
        if (SourceIDs is not null) d["sourceIDs"] = SourceIDs;
        if (CustomerSourceID is not null) d["customerSourceID"] = CustomerSourceID;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Source is not null) d["source"] = Source;
        if (SalesRoutesDefault is not null) d["salesRoutesDefault"] = SalesRoutesDefault;
        if (Visible is not null) d["visible"] = Visible;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
