// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesPaymentSearchParameters
{
    /// <summary>Office Unique Identifier</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Payment Unique Identifier</summary>
    public int? PaymentIDs { get; set; }
    /// <summary>Customer Unique Identifier</summary>
    public int? CustomerIDs { get; set; }
    /// <summary>Amount of Payment</summary>
    public decimal? Amount { get; set; }
    /// <summary>Payment date</summary>
    public string? Date { get; set; }
    /// <summary>Payment Method 0-Coupon, 1-Cash, 2-Check, 3-Credit Card, 4 ACH</summary>
    public int? PaymentMethod { get; set; }
    /// <summary>Status of the payment (0-Unsuccessful, 1-Successful, 2-Refunded)</summary>
    public int? Status { get; set; }
    /// <summary>Date the payment was applied</summary>
    public string? DateApplied { get; set; }
    /// <summary>employeeID that recorded the payment</summary>
    public int? EmployeeID { get; set; }
    /// <summary>Original paymentID (for refunds)</summary>
    public int? OriginalPaymentID { get; set; }
    /// <summary>Date the payment was last updated</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (PaymentIDs is not null) d["paymentIDs"] = PaymentIDs;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (Amount is not null) d["amount"] = Amount;
        if (Date is not null) d["date"] = Date;
        if (PaymentMethod is not null) d["paymentMethod"] = PaymentMethod;
        if (Status is not null) d["status"] = Status;
        if (DateApplied is not null) d["dateApplied"] = DateApplied;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (OriginalPaymentID is not null) d["originalPaymentID"] = OriginalPaymentID;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
