// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesServiceTypeSearchParameters
{
    /// <summary>Office Unique Identifier</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Service Type Unique Identifier</summary>
    public int? TypeIDs { get; set; }
    /// <summary>Description of the Service Type</summary>
    public string? Description { get; set; }
    /// <summary>Category of the Service Type</summary>
    public string? Category { get; set; }
    /// <summary>Service is a reservice type</summary>
    public int? Reservice { get; set; }
    /// <summary>Service is a sentricon service type</summary>
    public int? Sentricon { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (TypeIDs is not null) d["typeIDs"] = TypeIDs;
        if (Description is not null) d["description"] = Description;
        if (Category is not null) d["category"] = Category;
        if (Reservice is not null) d["reservice"] = Reservice;
        if (Sentricon is not null) d["sentricon"] = Sentricon;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
