// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesDoorSearchParameters
{
    /// <summary>doorID</summary>
    public int? DoorID { get; set; }
    /// <summary>lat</summary>
    public decimal? Lat { get; set; }
    /// <summary>lng</summary>
    public decimal? Lng { get; set; }
    /// <summary>employeeID</summary>
    public int? EmployeeID { get; set; }
    /// <summary>Size in miles of the search grid when using centerLat, centerLng filters.</summary>
    public int? SearchDistance { get; set; }
    /// <summary>Latitude of search radius center. Default distance 50 miles; override with searchDistance parameter. centerLng must also be set to use this filter</summary>
    public decimal? CenterLat { get; set; }
    /// <summary>Longitude of search radius center. Default distance 50 miles; override with searchDistance parameter. centerLat must also be set to use this filter</summary>
    public decimal? CenterLng { get; set; }
    /// <summary>alias of timeCreated</summary>
    public string? DateCreated { get; set; }
    /// <summary>timeCreated</summary>
    public string? TimeCreated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (DoorID is not null) d["doorID"] = DoorID;
        if (Lat is not null) d["lat"] = Lat;
        if (Lng is not null) d["lng"] = Lng;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (SearchDistance is not null) d["searchDistance"] = SearchDistance;
        if (CenterLat is not null) d["centerLat"] = CenterLat;
        if (CenterLng is not null) d["centerLng"] = CenterLng;
        if (DateCreated is not null) d["dateCreated"] = DateCreated;
        if (TimeCreated is not null) d["timeCreated"] = TimeCreated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
