// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTeamSearchParameters
{
    /// <summary>Unique Identifier</summary>
    public int? TeamID { get; set; }
    public int? OfficeIDs { get; set; }
    /// <summary>Team Name</summary>
    public string? Name { get; set; }
    /// <summary>Team type. 0: Office Team, 2: Sales Team</summary>
    public int? Type { get; set; }
    /// <summary>Employee ID of the team leader</summary>
    public int? TeamLeader { get; set; }
    /// <summary>Employee IDs of team members</summary>
    public int? EmployeeIDs { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (TeamID is not null) d["teamID"] = TeamID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Name is not null) d["name"] = Name;
        if (Type is not null) d["type"] = Type;
        if (TeamLeader is not null) d["teamLeader"] = TeamLeader;
        if (EmployeeIDs is not null) d["employeeIDs"] = EmployeeIDs;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
