// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesEmployeeSearchParameters
{
    public int? OfficeIDs { get; set; }
    /// <summary>'Active': 1 or 'Inactive': 0</summary>
    public int? Active { get; set; }
    /// <summary>Unique Identifier</summary>
    public int? EmployeeIDs { get; set; }
    /// <summary>Unique Identifier</summary>
    public int? EmployeeID { get; set; }
    /// <summary>How many years this employee has in experience. Typically used for sales reps to distinguish between rookies and seasoned.</summary>
    public int? YearsExperience { get; set; }
    /// <summary>Employee's last name</summary>
    public string? Lname { get; set; }
    /// <summary>Employee's first name</summary>
    public string? Fname { get; set; }
    /// <summary>Employee type. 0: Office Staff, 1: Technician, 2: Sales Rep</summary>
    public int? Type { get; set; }
    /// <summary>Employee's Link</summary>
    public string? EmployeeLink { get; set; }
    /// <summary>EmployeeID of the master account if this account has access to multiple offices.</summary>
    public int? RoamingRep { get; set; }
    /// <summary>teamID of the employee</summary>
    public int? TeamID { get; set; }
    /// <summary>primary teamID of the employee</summary>
    public int? PrimaryTeam { get; set; }
    /// <summary>phone number</summary>
    public string? Phone { get; set; }
    /// <summary>email</summary>
    public string? Email { get; set; }
    /// <summary>Access Control Profile ID</summary>
    public int? AccessControlProfileID { get; set; }
    /// <summary>Date employee was last updated</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Active is not null) d["active"] = Active;
        if (EmployeeIDs is not null) d["employeeIDs"] = EmployeeIDs;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (YearsExperience is not null) d["yearsExperience"] = YearsExperience;
        if (Lname is not null) d["lname"] = Lname;
        if (Fname is not null) d["fname"] = Fname;
        if (Type is not null) d["type"] = Type;
        if (EmployeeLink is not null) d["employeeLink"] = EmployeeLink;
        if (RoamingRep is not null) d["roamingRep"] = RoamingRep;
        if (TeamID is not null) d["teamID"] = TeamID;
        if (PrimaryTeam is not null) d["primaryTeam"] = PrimaryTeam;
        if (Phone is not null) d["phone"] = Phone;
        if (Email is not null) d["email"] = Email;
        if (AccessControlProfileID is not null) d["accessControlProfileID"] = AccessControlProfileID;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
