// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesLocationSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key</summary>
    public int? LocationIDs { get; set; }
    /// <summary>Primary key alias</summary>
    public int? LocationID { get; set; }
    /// <summary>OfficeID insect belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>visibility of the location</summary>
    public int? Visible { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (LocationIDs is not null) d["locationIDs"] = LocationIDs;
        if (LocationID is not null) d["locationID"] = LocationID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Visible is not null) d["visible"] = Visible;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
