// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesRouteSearchParameters
{
    public int? OfficeIDs { get; set; }
    public int? RouteIDs { get; set; }
    public string? Date { get; set; }
    public string? DateStart { get; set; }
    public string? DateEnd { get; set; }
    public int? AssignedTech { get; set; }
    /// <summary>Send as 1 to retrieve only routes that the API can schedule for.</summary>
    public bool? ApiCanSchedule { get; set; }
    public string? LastUpdated { get; set; }
    public string? DateUpdated { get; set; }
    /// <summary>Send with an employeeID to limit routes to those that the employee's team is assigned to via route can schedule settings.</summary>
    public int? EmployeeTeams { get; set; }
    /// <summary>send as 1 to ignore routes available to the global sales team</summary>
    public int? ExcludeGlobalSalesTeam { get; set; }
    /// <summary>Title of the group associated with the route</summary>
    public string? GroupTitle { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (RouteIDs is not null) d["routeIDs"] = RouteIDs;
        if (Date is not null) d["date"] = Date;
        if (DateStart is not null) d["dateStart"] = DateStart;
        if (DateEnd is not null) d["dateEnd"] = DateEnd;
        if (AssignedTech is not null) d["assignedTech"] = AssignedTech;
        if (ApiCanSchedule is not null) d["apiCanSchedule"] = ApiCanSchedule;
        if (LastUpdated is not null) d["lastUpdated"] = LastUpdated;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (EmployeeTeams is not null) d["employeeTeams"] = EmployeeTeams;
        if (ExcludeGlobalSalesTeam is not null) d["excludeGlobalSalesTeam"] = ExcludeGlobalSalesTeam;
        if (GroupTitle is not null) d["groupTitle"] = GroupTitle;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
