// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesApplicationMethodSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key</summary>
    public int? MethodIDs { get; set; }
    /// <summary>Primary key alias</summary>
    public int? MethodID { get; set; }
    /// <summary>Primary key alias</summary>
    public int? ApplicationMethodID { get; set; }
    /// <summary>Primary key alias</summary>
    public int? ApplicationMethodIDs { get; set; }
    /// <summary>OfficeID insect belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>visibility of the method</summary>
    public int? Visible { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (MethodIDs is not null) d["methodIDs"] = MethodIDs;
        if (MethodID is not null) d["methodID"] = MethodID;
        if (ApplicationMethodID is not null) d["applicationMethodID"] = ApplicationMethodID;
        if (ApplicationMethodIDs is not null) d["applicationMethodIDs"] = ApplicationMethodIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Visible is not null) d["visible"] = Visible;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
