// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesChemicalSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key</summary>
    public int? ChemicalIDs { get; set; }
    /// <summary>Office ID region belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Name of the chemical</summary>
    public string? Name { get; set; }
    /// <summary>Visibility of the chemical</summary>
    public string? Visible { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (ChemicalIDs is not null) d["chemicalIDs"] = ChemicalIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Name is not null) d["name"] = Name;
        if (Visible is not null) d["visible"] = Visible;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
