// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerSearchParameters
{
    public int? OfficeIDs { get; set; }
    /// <summary>Whether or not this customer is 'Active': 1 or 'Inactive': 0.</summary>
    public int? Active { get; set; }
    /// <summary>Unique Identifier</summary>
    public int? CustomerIDs { get; set; }
    /// <summary>The date this customer was created or added.</summary>
    public string? DateAdded { get; set; }
    /// <summary>The date this customer was cancelled.</summary>
    public string? DateCancelled { get; set; }
    /// <summary>Last date this customer record was updated.</summary>
    public string? DateUpdated { get; set; }
    /// <summary>Auto Pay status: 0-Not on Auto Pay, 1-Auto Pay CC, 2-AutoPay ACH</summary>
    public int? APay { get; set; }
    /// <summary>Customer's last name</summary>
    public string? Lname { get; set; }
    /// <summary>Customer's first name</summary>
    public string? Fname { get; set; }
    /// <summary>Customer's address</summary>
    public string? Address { get; set; }
    /// <summary>Customer's city</summary>
    public string? City { get; set; }
    /// <summary>Customer's state</summary>
    public string? State { get; set; }
    /// <summary>Customer's zip code</summary>
    public string? Zip { get; set; }
    public string? DateUpdatedStart { get; set; }
    public string? DateUpdatedEnd { get; set; }
    public string? DateAddedStart { get; set; }
    public string? DateAddedEnd { get; set; }
    /// <summary>CustomerID for the master account in the connected property</summary>
    public int? MasterAccount { get; set; }
    /// <summary>Balance age in days. Available filters: &gt;, &lt;, &gt;=, &lt;=, =, !=, IN, BETWEEN</summary>
    public int? BalanceAge { get; set; }
    /// <summary>Date the balance began.</summary>
    public string? AgingDate { get; set; }
    /// <summary>Responsible balance age in days. Available filters: &gt;, &lt;, &gt;=, &lt;=, =, !=, IN, BETWEEN</summary>
    public int? ResponsibleBalanceAge { get; set; }
    /// <summary>Date the responsibleBalance began.</summary>
    public string? ResponsibleAgingDate { get; set; }
    /// <summary>Match any 10-digit phone number (phone1, phone2, or additionalContact phone). Numbers only.</summary>
    public int? Phone { get; set; }
    /// <summary>Primary 10-digit phone number. Numbers only.</summary>
    public int? Phone1 { get; set; }
    /// <summary>Secondary 10-digit phone number. Numbers only.</summary>
    public int? Phone2 { get; set; }
    /// <summary>Additional contact 10-digit phone number. Numbers only.</summary>
    public int? AdditionalPhone { get; set; }
    /// <summary>Billing 10-digit phone number. Numbers only.</summary>
    public int? BillingPhone { get; set; }
    /// <summary>Company name of the customer.</summary>
    public string? CompanyName { get; set; }
    /// <summary>Search by the CustomerID specified on import/main.</summary>
    public string? CustomerLink { get; set; }
    /// <summary>RegionID of the customer</summary>
    public int? RegionID { get; set; }
    /// <summary>Customer's email</summary>
    public string? Email { get; set; }
    /// <summary>EmployeeID who added the customer</summary>
    public int? EmployeeID { get; set; }
    /// <summary>EmployeeID who added the customer</summary>
    public int? AddedByID { get; set; }
    /// <summary>ID of the autopay paymentProfile attached to the customer</summary>
    public int? AutoPayPaymentProfileID { get; set; }
    /// <summary>Customer balance amount. Available filters: &gt;, &lt;, &gt;=, &lt;=, =, !=, IN, BETWEEN</summary>
    public int? Balance { get; set; }
    /// <summary>Responsible balance amount. Available filters: &gt;, &lt;, &gt;=, &lt;=, =, !=, IN, BETWEEN</summary>
    public int? ResponsibleBalance { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Active is not null) d["active"] = Active;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (DateCancelled is not null) d["dateCancelled"] = DateCancelled;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (APay is not null) d["aPay"] = APay;
        if (Lname is not null) d["lname"] = Lname;
        if (Fname is not null) d["fname"] = Fname;
        if (Address is not null) d["address"] = Address;
        if (City is not null) d["city"] = City;
        if (State is not null) d["state"] = State;
        if (Zip is not null) d["zip"] = Zip;
        if (DateUpdatedStart is not null) d["dateUpdatedStart"] = DateUpdatedStart;
        if (DateUpdatedEnd is not null) d["dateUpdatedEnd"] = DateUpdatedEnd;
        if (DateAddedStart is not null) d["dateAddedStart"] = DateAddedStart;
        if (DateAddedEnd is not null) d["dateAddedEnd"] = DateAddedEnd;
        if (MasterAccount is not null) d["masterAccount"] = MasterAccount;
        if (BalanceAge is not null) d["balanceAge"] = BalanceAge;
        if (AgingDate is not null) d["agingDate"] = AgingDate;
        if (ResponsibleBalanceAge is not null) d["responsibleBalanceAge"] = ResponsibleBalanceAge;
        if (ResponsibleAgingDate is not null) d["responsibleAgingDate"] = ResponsibleAgingDate;
        if (Phone is not null) d["phone"] = Phone;
        if (Phone1 is not null) d["phone1"] = Phone1;
        if (Phone2 is not null) d["phone2"] = Phone2;
        if (AdditionalPhone is not null) d["additionalPhone"] = AdditionalPhone;
        if (BillingPhone is not null) d["billingPhone"] = BillingPhone;
        if (CompanyName is not null) d["companyName"] = CompanyName;
        if (CustomerLink is not null) d["customerLink"] = CustomerLink;
        if (RegionID is not null) d["regionID"] = RegionID;
        if (Email is not null) d["email"] = Email;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (AddedByID is not null) d["addedByID"] = AddedByID;
        if (AutoPayPaymentProfileID is not null) d["autoPayPaymentProfileID"] = AutoPayPaymentProfileID;
        if (Balance is not null) d["balance"] = Balance;
        if (ResponsibleBalance is not null) d["responsibleBalance"] = ResponsibleBalance;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
