// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesGlAccountSearchParameters : FieldRoutesQueryBase
{
    public int? GlAccountIDs { get; set; }
    public int? GlAccountID { get; set; }
    public int? GlNumber { get; set; }
    public int? OfficeIDs { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (GlAccountIDs is not null) d["glAccountIDs"] = GlAccountIDs;
        if (GlAccountID is not null) d["glAccountID"] = GlAccountID;
        if (GlNumber is not null) d["glNumber"] = GlNumber;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
