// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesChemicalUseSearchParameters
{
    /// <summary>Primary key</summary>
    public int? ChemicalUseIDs { get; set; }
    /// <summary>Primary key alias</summary>
    public int? ChemicalUseID { get; set; }
    /// <summary>Office ID region belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>ID of the chemical Used</summary>
    public int? ChemicalID { get; set; }
    public int? AppointmentID { get; set; }
    public int? CustomerID { get; set; }
    public string? DateCreated { get; set; }
    public string? CreatedBy { get; set; }
    public int? ServiceID { get; set; }
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (ChemicalUseIDs is not null) d["chemicalUseIDs"] = ChemicalUseIDs;
        if (ChemicalUseID is not null) d["chemicalUseID"] = ChemicalUseID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (ChemicalID is not null) d["chemicalID"] = ChemicalID;
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (DateCreated is not null) d["dateCreated"] = DateCreated;
        if (CreatedBy is not null) d["createdBy"] = CreatedBy;
        if (ServiceID is not null) d["serviceID"] = ServiceID;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
