// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppliedPaymentSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key</summary>
    public int? AppliedPaymentID { get; set; }
    /// <summary>Primary key alias</summary>
    public int? AppliedPaymentIDs { get; set; }
    /// <summary>Office Unique Identifier</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Office Unique Identifier</summary>
    public int? OfficeID { get; set; }
    /// <summary>Payment Unique Identifier</summary>
    public int? PaymentIDs { get; set; }
    /// <summary>Payment Unique Identifier</summary>
    public int? PaymentID { get; set; }
    /// <summary>ticket Unique Identifier</summary>
    public int? TicketIDs { get; set; }
    /// <summary>ticket Unique Identifier</summary>
    public int? TicketID { get; set; }
    /// <summary>Customer Unique Identifier</summary>
    public int? CustomerIDs { get; set; }
    /// <summary>Customer Unique Identifier</summary>
    public int? CustomerID { get; set; }
    /// <summary>Payment application date</summary>
    public string? DateApplied { get; set; }
    /// <summary>Date payment application was last updated.</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (AppliedPaymentID is not null) d["appliedPaymentID"] = AppliedPaymentID;
        if (AppliedPaymentIDs is not null) d["appliedPaymentIDs"] = AppliedPaymentIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (PaymentIDs is not null) d["paymentIDs"] = PaymentIDs;
        if (PaymentID is not null) d["paymentID"] = PaymentID;
        if (TicketIDs is not null) d["ticketIDs"] = TicketIDs;
        if (TicketID is not null) d["ticketID"] = TicketID;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (DateApplied is not null) d["dateApplied"] = DateApplied;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
