// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTimeClockSearchParameters
{
    /// <summary>Primary key.</summary>
    public int? EntryIDs { get; set; }
    /// <summary>Primary key (alias)</summary>
    public int? TimeClockIDs { get; set; }
    public int? OfficeIDs { get; set; }
    /// <summary>EmployeeID who the time clock entry applies to.</summary>
    public int? EmployeeIDs { get; set; }
    /// <summary>Clock-in time</summary>
    public string? TimeIn { get; set; }
    /// <summary>Clock-out time</summary>
    public string? TimeOut { get; set; }
    /// <summary>0 for unpaid categories, 1 for paid categories. Clock entries with no category association are considered paid.</summary>
    public int? Paid { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (EntryIDs is not null) d["entryIDs"] = EntryIDs;
        if (TimeClockIDs is not null) d["timeClockIDs"] = TimeClockIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (EmployeeIDs is not null) d["employeeIDs"] = EmployeeIDs;
        if (TimeIn is not null) d["timeIn"] = TimeIn;
        if (TimeOut is not null) d["timeOut"] = TimeOut;
        if (Paid is not null) d["paid"] = Paid;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
