// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesRegionSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key</summary>
    public int? RegionIDs { get; set; }
    /// <summary>Office ID region belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Description of the region</summary>
    public string? Description { get; set; }
    /// <summary>Time the region was created</summary>
    public string? Created { get; set; }
    /// <summary>Time the region was deleted</summary>
    public string? Deleted { get; set; }
    public string? Type { get; set; }
    /// <summary>Active status for the region.</summary>
    public string? Active { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (RegionIDs is not null) d["regionIDs"] = RegionIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Description is not null) d["description"] = Description;
        if (Created is not null) d["created"] = Created;
        if (Deleted is not null) d["deleted"] = Deleted;
        if (Type is not null) d["type"] = Type;
        if (Active is not null) d["active"] = Active;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
