// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppointmentReminderSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary Key</summary>
    public int? ReminderID { get; set; }
    /// <summary>Alias of reminderID</summary>
    public int? ReminderIDs { get; set; }
    /// <summary>Alias of reminderID</summary>
    public int? AppointmentReminderIDs { get; set; }
    /// <summary>Office the reminder belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>appointmentID the reminder pertains to</summary>
    public int? AppointmentID { get; set; }
    /// <summary>Text of the reminder</summary>
    public string? Text { get; set; }
    /// <summary>Time the reminder was sent</summary>
    public string? DateSent { get; set; }
    /// <summary>Time email was sent</summary>
    public string? EmailSent { get; set; }
    /// <summary>Time voice message was sent</summary>
    public string? VoiceSent { get; set; }
    /// <summary>-1 = don't send, 0 = not sent, 1 = sent, 9 = confirmed</summary>
    public int? Status { get; set; }
    /// <summary>Response text received</summary>
    public string? Response { get; set; }
    /// <summary>Time response was received</summary>
    public string? ResponseTime { get; set; }
    /// <summary>Phone number for SMS</summary>
    public string? SendTo { get; set; }
    /// <summary>Email address the reminder was sent to</summary>
    public string? EmailAddress { get; set; }
    /// <summary>Phone number for voice</summary>
    public string? VoiceNumber { get; set; }
    /// <summary>Date that this appointmentReminder was last updated</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (ReminderID is not null) d["reminderID"] = ReminderID;
        if (ReminderIDs is not null) d["reminderIDs"] = ReminderIDs;
        if (AppointmentReminderIDs is not null) d["appointmentReminderIDs"] = AppointmentReminderIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (Text is not null) d["text"] = Text;
        if (DateSent is not null) d["dateSent"] = DateSent;
        if (EmailSent is not null) d["emailSent"] = EmailSent;
        if (VoiceSent is not null) d["voiceSent"] = VoiceSent;
        if (Status is not null) d["status"] = Status;
        if (Response is not null) d["response"] = Response;
        if (ResponseTime is not null) d["responseTime"] = ResponseTime;
        if (SendTo is not null) d["sendTo"] = SendTo;
        if (EmailAddress is not null) d["emailAddress"] = EmailAddress;
        if (VoiceNumber is not null) d["voiceNumber"] = VoiceNumber;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
