// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesGenericFlagSearchParameters
{
    public int? GenericFlagIDs { get; set; }
    public int? OfficeIDs { get; set; }
    public string? Code { get; set; }
    public string? Description { get; set; }
    public int? Status { get; set; }
    public string? Type { get; set; }
    public string? DateCreated { get; set; }
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (GenericFlagIDs is not null) d["genericFlagIDs"] = GenericFlagIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Code is not null) d["code"] = Code;
        if (Description is not null) d["description"] = Description;
        if (Status is not null) d["status"] = Status;
        if (Type is not null) d["type"] = Type;
        if (DateCreated is not null) d["dateCreated"] = DateCreated;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
