// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesChangelogSearchParameters
{
    public int? OfficeIDs { get; set; }
    public int? ClassID { get; set; }
    public int? ReferenceID { get; set; }
    /// <summary>The date this log was created</summary>
    public string? DateChanged { get; set; }
    /// <summary>Primary key for changelog</summary>
    public int? ChangeIDs { get; set; }
    /// <summary>Primary key for changelog (alias)</summary>
    public int? ChangelogIDs { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (ClassID is not null) d["classID"] = ClassID;
        if (ReferenceID is not null) d["referenceID"] = ReferenceID;
        if (DateChanged is not null) d["dateChanged"] = DateChanged;
        if (ChangeIDs is not null) d["changeIDs"] = ChangeIDs;
        if (ChangelogIDs is not null) d["changelogIDs"] = ChangelogIDs;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
