// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTicketSearchParameters : FieldRoutesQueryBase
{
    public int? OfficeIDs { get; set; }
    public int? TicketIDs { get; set; }
    /// <summary>Whether this ticket/invoice is active: 1 or inactive: 0. Inactive tickets are not added to the customer's balance or A/R aging</summary>
    public int? Status { get; set; }
    /// <summary>The customer who owns this ticket</summary>
    public int? CustomerIDs { get; set; }
    /// <summary>When a ticket has a recurring template subscription ID it represents a recurring ticket template</summary>
    public int? RecurringTemplateSubscriptionIDs { get; set; }
    /// <summary>The date this ticket was created</summary>
    public string? DateCreated { get; set; }
    /// <summary>Invoice date</summary>
    public string? InvoiceDate { get; set; }
    /// <summary>The date the ticket was updated</summary>
    public string? DateUpdated { get; set; }
    /// <summary>Any unpaid balance left on this ticket</summary>
    public decimal? Balance { get; set; }
    /// <summary>Amount of ticket before tax</summary>
    public decimal? SubTotal { get; set; }
    /// <summary>Total of invoice including any applicable taxes</summary>
    public decimal? Total { get; set; }
    /// <summary>Amount of tax</summary>
    public decimal? TaxAmount { get; set; }
    /// <summary>The appointment this ticket was generated for. Tickets may not always be attached to an appointment. For example in cases of recurring billing or stand alone invoices for administrative fees.</summary>
    public int? AppointmentIDs { get; set; }
    /// <summary>The subscription this ticket was generated for. This is only used for the ticket template which define the price of the subscription setup.</summary>
    public int? SubscriptionIDs { get; set; }
    /// <summary>The ticket template type. I: initial ticket template, R: recurring ticket template, NA: not a ticket template.</summary>
    public string? TemplateType { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (TicketIDs is not null) d["ticketIDs"] = TicketIDs;
        if (Status is not null) d["status"] = Status;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (RecurringTemplateSubscriptionIDs is not null) d["recurringTemplateSubscriptionIDs"] = RecurringTemplateSubscriptionIDs;
        if (DateCreated is not null) d["dateCreated"] = DateCreated;
        if (InvoiceDate is not null) d["invoiceDate"] = InvoiceDate;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (Balance is not null) d["balance"] = Balance;
        if (SubTotal is not null) d["subTotal"] = SubTotal;
        if (Total is not null) d["total"] = Total;
        if (TaxAmount is not null) d["taxAmount"] = TaxAmount;
        if (AppointmentIDs is not null) d["appointmentIDs"] = AppointmentIDs;
        if (SubscriptionIDs is not null) d["subscriptionIDs"] = SubscriptionIDs;
        if (TemplateType is not null) d["templateType"] = TemplateType;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
