// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesContractSearchParameters
{
    public int? OfficeIDs { get; set; }
    public int? ContractIDs { get; set; }
    public int? CustomerIDs { get; set; }
    public int? SubscriptionIDs { get; set; }
    /// <summary>The date the contract was signed.</summary>
    public string? DateSigned { get; set; }
    /// <summary>The date the contract was added.</summary>
    public string? DateAdded { get; set; }
    /// <summary>The date the contract was last updated.</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (ContractIDs is not null) d["contractIDs"] = ContractIDs;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (SubscriptionIDs is not null) d["subscriptionIDs"] = SubscriptionIDs;
        if (DateSigned is not null) d["dateSigned"] = DateSigned;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
