// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTimeClockCategorySearchParameters
{
    /// <summary>Primary key.</summary>
    public int? ClockCategoryIDs { get; set; }
    /// <summary>Primary key (alias)</summary>
    public int? TimeClockCategoryIDs { get; set; }
    public int? OfficeIDs { get; set; }
    /// <summary>Visible to staff</summary>
    public int? Visible { get; set; }
    /// <summary>time clock category is allowed on initial clock in.</summary>
    public int? AllowOnClockIn { get; set; }
    /// <summary>1 = system reserved category (cannot be deleted or changed)</summary>
    public int? SystemReserved { get; set; }
    /// <summary>0 for unpaid categories, 1 for paid categories. Clock entries with no category association are considered paid.</summary>
    public int? Paid { get; set; }
    /// <summary>Date this category was last changed</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (ClockCategoryIDs is not null) d["clockCategoryIDs"] = ClockCategoryIDs;
        if (TimeClockCategoryIDs is not null) d["timeClockCategoryIDs"] = TimeClockCategoryIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Visible is not null) d["visible"] = Visible;
        if (AllowOnClockIn is not null) d["allowOnClockIn"] = AllowOnClockIn;
        if (SystemReserved is not null) d["systemReserved"] = SystemReserved;
        if (Paid is not null) d["paid"] = Paid;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
