// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesDisbursementSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key</summary>
    public int? GatewayDisbursementIDs { get; set; }
    /// <summary>Primary key alias</summary>
    public int? GatewayDisbursementID { get; set; }
    /// <summary>Date created</summary>
    public string? DateCreated { get; set; }
    /// <summary>Date last updated</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (GatewayDisbursementIDs is not null) d["gatewayDisbursementIDs"] = GatewayDisbursementIDs;
        if (GatewayDisbursementID is not null) d["gatewayDisbursementID"] = GatewayDisbursementID;
        if (DateCreated is not null) d["dateCreated"] = DateCreated;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
