// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesProductSearchParameters
{
    /// <summary>Primary Key</summary>
    public int? ProductID { get; set; }
    /// <summary>OfficeID of the product; -1 is available to all offices.</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Product Code (up to 25 characters)</summary>
    public string? Code { get; set; }
    /// <summary>Product category</summary>
    public string? Category { get; set; }
    /// <summary>Whether or not the product is visible in lists when creating a new addon</summary>
    public int? Visible { get; set; }
    /// <summary>Whether or not the product is visible for sales reps on mobile app</summary>
    public int? SalesVisible { get; set; }
    /// <summary>Description of the product</summary>
    public string? Description { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (ProductID is not null) d["productID"] = ProductID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Code is not null) d["code"] = Code;
        if (Category is not null) d["category"] = Category;
        if (Visible is not null) d["visible"] = Visible;
        if (SalesVisible is not null) d["salesVisible"] = SalesVisible;
        if (Description is not null) d["description"] = Description;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
