// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesUnitSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key.</summary>
    public int? UnitIDs { get; set; }
    public int? OfficeIDs { get; set; }
    /// <summary>Customer who owns this unit</summary>
    public int? CustomerIDs { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (UnitIDs is not null) d["unitIDs"] = UnitIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
