// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerFlagSearchParameters
{
    public int? CustomerIDs { get; set; }
    /// <summary>Limit using user-defined generic flags or system flags: paidInFull, switchOver, purpleDragon, pendingCancellation, prefersPaper, collectonsStage</summary>
    public string? CustomerFlags { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (CustomerFlags is not null) d["customerFlags"] = CustomerFlags;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
