// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesInsectSearchParameters
{
    /// <summary>Primary key</summary>
    public int? InsectIDs { get; set; }
    /// <summary>Primary key alias</summary>
    public int? InsectID { get; set; }
    /// <summary>OfficeID insect belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>1 if insect is visible, 0 otherwise</summary>
    public int? Visible { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (InsectIDs is not null) d["insectIDs"] = InsectIDs;
        if (InsectID is not null) d["insectID"] = InsectID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Visible is not null) d["visible"] = Visible;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
