// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesEmployeeLocationSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key.</summary>
    public int? LocationIDs { get; set; }
    /// <summary>EmployeeID the location is assigned to</summary>
    public int? EmployeeID { get; set; }
    public int? OfficeID { get; set; }
    /// <summary>time the location check-in took place</summary>
    public int? Time { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (LocationIDs is not null) d["locationIDs"] = LocationIDs;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (Time is not null) d["time"] = Time;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
