// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppointmentRescheduleReasonSearchParameters
{
    public int? RescheduleReasonIDs { get; set; }
    public int? RescheduleReasonID { get; set; }
    public int? OfficeIDs { get; set; }
    public int? OfficeID { get; set; }
    public int? Visible { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (RescheduleReasonIDs is not null) d["rescheduleReasonIDs"] = RescheduleReasonIDs;
        if (RescheduleReasonID is not null) d["rescheduleReasonID"] = RescheduleReasonID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (Visible is not null) d["visible"] = Visible;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
