// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAdditionalContactSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary Key</summary>
    public int? AdditionalContactIDs { get; set; }
    /// <summary>Primary Key</summary>
    public int? AdditionalContactID { get; set; }
    /// <summary>Primary Key</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Primary Key</summary>
    public int? OfficeID { get; set; }
    /// <summary>Customer ID that the is additional contact belongs to</summary>
    public int? CustomerID { get; set; }
    /// <summary>If this is tied to a WDO termite report this will be non-null</summary>
    public int? TermiteReportID { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (AdditionalContactIDs is not null) d["additionalContactIDs"] = AdditionalContactIDs;
        if (AdditionalContactID is not null) d["additionalContactID"] = AdditionalContactID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (TermiteReportID is not null) d["termiteReportID"] = TermiteReportID;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
