// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSkillSearchParameters
{
    /// <summary>Primary key</summary>
    public int? SkillIDs { get; set; }
    /// <summary>Primary key alias</summary>
    public int? SkillID { get; set; }
    /// <summary>Office ID skill belongs to</summary>
    public int? OfficeIDs { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (SkillIDs is not null) d["skillIDs"] = SkillIDs;
        if (SkillID is not null) d["skillID"] = SkillID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
