// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesKnockSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary Key</summary>
    public int? KnockID { get; set; }
    /// <summary>Door the knock is associated with</summary>
    public int? DoorID { get; set; }
    /// <summary>Date the knock was created</summary>
    public string? DateAdded { get; set; }
    /// <summary>Date the knock was last updated</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (KnockID is not null) d["knockID"] = KnockID;
        if (DoorID is not null) d["doorID"] = DoorID;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
