// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesDiagramSearchParameters : FieldRoutesQueryBase
{
    public int? DiagramIDs { get; set; }
    public int? OfficeIDs { get; set; }
    public int? OfficeID { get; set; }
    public int? CustomerID { get; set; }
    /// <summary>The date the diagram was updated.</summary>
    public string? DateUpdated { get; set; }
    /// <summary>Type of diagram ['WDO','PROPERTY ESTIMATION'].</summary>
    public string? DiagramType { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (DiagramIDs is not null) d["diagramIDs"] = DiagramIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (DiagramType is not null) d["diagramType"] = DiagramType;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
