// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSpotSearchParameters
{
    public int? OfficeIDs { get; set; }
    /// <summary>Primary key for spots.</summary>
    public int? SpotIDs { get; set; }
    public string? Date { get; set; }
    /// <summary>Send as 1 to retrieve only routes that the API can schedule for.</summary>
    public bool? ApiCanSchedule { get; set; }
    public int? AssignedTech { get; set; }
    /// <summary>Primary key for routes.</summary>
    public int? RouteID { get; set; }
    /// <summary>Primary key for routes.</summary>
    public int? RouteIDs { get; set; }
    /// <summary>Primary key for routes.</summary>
    public int? Reserved { get; set; }
    /// <summary>Date of last update.</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (SpotIDs is not null) d["spotIDs"] = SpotIDs;
        if (Date is not null) d["date"] = Date;
        if (ApiCanSchedule is not null) d["apiCanSchedule"] = ApiCanSchedule;
        if (AssignedTech is not null) d["assignedTech"] = AssignedTech;
        if (RouteID is not null) d["routeID"] = RouteID;
        if (RouteIDs is not null) d["routeIDs"] = RouteIDs;
        if (Reserved is not null) d["reserved"] = Reserved;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
