// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesGroupSearchParameters
{
    /// <summary>Primary key</summary>
    public int? GroupIDs { get; set; }
    /// <summary>Primary key alias</summary>
    public int? GroupID { get; set; }
    /// <summary>Office ID region belongs to</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>Date the group was last updated</summary>
    public string? Date { get; set; }
    /// <summary>Date the group was last updated</summary>
    public string? DateUpdated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (GroupIDs is not null) d["groupIDs"] = GroupIDs;
        if (GroupID is not null) d["groupID"] = GroupID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (Date is not null) d["date"] = Date;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
