// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTicketItemSearchParameters : FieldRoutesQueryBase
{
    public int? ItemIDs { get; set; }
    public int? OfficeIDs { get; set; }
    public int? OfficeID { get; set; }
    public int? TicketID { get; set; }
    public int? TicketIDs { get; set; }
    public int? ProductID { get; set; }
    public int? ServiceID { get; set; }
    public int? GlNumber { get; set; }
    public int? CreditTo { get; set; }
    public string? DateUpdated { get; set; }
    public string? DateCreated { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (ItemIDs is not null) d["itemIDs"] = ItemIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (TicketID is not null) d["ticketID"] = TicketID;
        if (TicketIDs is not null) d["ticketIDs"] = TicketIDs;
        if (ProductID is not null) d["productID"] = ProductID;
        if (ServiceID is not null) d["serviceID"] = ServiceID;
        if (GlNumber is not null) d["glNumber"] = GlNumber;
        if (CreditTo is not null) d["creditTo"] = CreditTo;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (DateCreated is not null) d["dateCreated"] = DateCreated;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
