// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesPaymentProfileSearchParameters : FieldRoutesQueryBase
{
    /// <summary>Primary key for the paymentProfile</summary>
    public int? PaymentProfileIDs { get; set; }
    /// <summary>customer that the paymentProfile belongs to.</summary>
    public int? CustomerIDs { get; set; }
    /// <summary>OfficeID of the customer that the paymentProfile belongs to.</summary>
    public int? OfficeIDs { get; set; }
    /// <summary>date the payment profile was created</summary>
    public string? DateCreated { get; set; }
    /// <summary>date the payment profile was last updated</summary>
    public string? DateUpdated { get; set; }
    /// <summary>-1 = soft deleted, 0 = empty, 1 = valid, 2 = invalid, 3 = expired, 4 = last transaction failed</summary>
    public int? Status { get; set; }
    /// <summary>State associated with the CC/Bank account</summary>
    public string? BillingState { get; set; }
    /// <summary>Zip associated with the CC/Bank account</summary>
    public string? BillingZip { get; set; }
    /// <summary>1=cc, 2 = ach</summary>
    public int? PaymentMethod { get; set; }
    /// <summary>ACH or CC gateway E.G. authorize, nmi, brain, element</summary>
    public string? Gateway { get; set; }
    /// <summary>Credit card only e.g. Visa, Mastercard</summary>
    public string? CardType { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (PaymentProfileIDs is not null) d["paymentProfileIDs"] = PaymentProfileIDs;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (DateCreated is not null) d["dateCreated"] = DateCreated;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (Status is not null) d["status"] = Status;
        if (BillingState is not null) d["billingState"] = BillingState;
        if (BillingZip is not null) d["billingZip"] = BillingZip;
        if (PaymentMethod is not null) d["paymentMethod"] = PaymentMethod;
        if (Gateway is not null) d["gateway"] = Gateway;
        if (CardType is not null) d["cardType"] = CardType;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
