// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppointmentSearchParameters : FieldRoutesQueryBase
{
    public int? OfficeID { get; set; }
    public int? OfficeIDs { get; set; }
    /// <summary>Unique ID</summary>
    public int? AppointmentIDs { get; set; }
    /// <summary>The status of an appointment which can include:&lt;ul&gt;&lt;li&gt;0: Pending&lt;/li&gt;&lt;li&gt;1: Completed&lt;/li&gt;&lt;li&gt;2: No Show&lt;/li&gt;&lt;li&gt;-2: Rescheduled&lt;/li&gt;&lt;li&gt;-1: Cancelled&lt;/li&gt;&lt;/ul&gt;</summary>
    public int? Status { get; set; }
    /// <summary>Customer who owns this appointment</summary>
    public int? CustomerIDs { get; set; }
    /// <summary>Subscription who owns this appointment. Appointments that are attached to subscriptions inherit the subscriptions pricing templates and other defaults as well as update the subscriptions next service dates upon completion. Re-services and stand-alone services are NOT attached to subscriptions.</summary>
    public int? SubscriptionIDs { get; set; }
    /// <summary>Spot ID the appointment is assigned to.</summary>
    public int? SpotIDs { get; set; }
    /// <summary>Route the appointment is assigned to.</summary>
    public int? RouteIDs { get; set; }
    /// <summary>Date this appointment was created / scheduled.</summary>
    public string? DateAdded { get; set; }
    /// <summary>Date this appointment was completed / marked serviced (not necessarily the date it was on the schedule).</summary>
    public string? DateCompleted { get; set; }
    /// <summary>Date this appointment is scheduled for.</summary>
    public string? Date { get; set; }
    /// <summary>Service type ID for this appointment. Reference the endpoint servicetypes to see available options</summary>
    public int? ServiceIDs { get; set; }
    /// <summary>The technician who serviced this appointment</summary>
    public int? ServicedBy { get; set; }
    /// <summary>The user who marked this appointment as completed NOT necessarily the one who serviced the appointment.</summary>
    public int? CompletedBy { get; set; }
    public string? DateAddedStart { get; set; }
    public string? DateAddedEnd { get; set; }
    public string? DateStart { get; set; }
    public string? DateEnd { get; set; }
    /// <summary>Cancelation date</summary>
    public string? DateCancelled { get; set; }
    /// <summary>employeeID of additional tech</summary>
    public int? AdditionalTechs { get; set; }
    /// <summary>Set as 1 if this is the first appointment connected to a subscription</summary>
    public int? SalesAnchor { get; set; }
    /// <summary>The ID of a target insect associated with the appointment, these IDs can be found in preferences via Admin &gt; Preferences &gt; Service Related &gt; Target Issues</summary>
    public int? TargetPests { get; set; }
    /// <summary>Date the appointment was last changed</summary>
    public string? DateUpdated { get; set; }
    /// <summary>Sales team that sold the appointment.</summary>
    public int? SalesTeamID { get; set; }
    /// <summary>EmployeeID that cancelled the appointment.</summary>
    public int? CancelledBy { get; set; }
    /// <summary>EmployeeID that was assigned to the appointment.</summary>
    public int? AssignedTech { get; set; }

    /// <summary>Fields supporting query objects, e.g. { "operator": ">", "value": "2016-01-01" }.</summary>
    public Dictionary<string, FilterValue> AdditionalFilters { get; } = new();

    internal Dictionary<string, object?> ToDictionary(bool includeData)
    {
        var d = new Dictionary<string, object?>();
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (AppointmentIDs is not null) d["appointmentIDs"] = AppointmentIDs;
        if (Status is not null) d["status"] = Status;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (SubscriptionIDs is not null) d["subscriptionIDs"] = SubscriptionIDs;
        if (SpotIDs is not null) d["spotIDs"] = SpotIDs;
        if (RouteIDs is not null) d["routeIDs"] = RouteIDs;
        if (DateAdded is not null) d["dateAdded"] = DateAdded;
        if (DateCompleted is not null) d["dateCompleted"] = DateCompleted;
        if (Date is not null) d["date"] = Date;
        if (ServiceIDs is not null) d["serviceIDs"] = ServiceIDs;
        if (ServicedBy is not null) d["servicedBy"] = ServicedBy;
        if (CompletedBy is not null) d["completedBy"] = CompletedBy;
        if (DateAddedStart is not null) d["dateAddedStart"] = DateAddedStart;
        if (DateAddedEnd is not null) d["dateAddedEnd"] = DateAddedEnd;
        if (DateStart is not null) d["dateStart"] = DateStart;
        if (DateEnd is not null) d["dateEnd"] = DateEnd;
        if (DateCancelled is not null) d["dateCancelled"] = DateCancelled;
        if (AdditionalTechs is not null) d["additionalTechs"] = AdditionalTechs;
        if (SalesAnchor is not null) d["salesAnchor"] = SalesAnchor;
        if (TargetPests is not null) d["targetPests"] = TargetPests;
        if (DateUpdated is not null) d["dateUpdated"] = DateUpdated;
        if (SalesTeamID is not null) d["salesTeamID"] = SalesTeamID;
        if (CancelledBy is not null) d["cancelledBy"] = CancelledBy;
        if (AssignedTech is not null) d["assignedTech"] = AssignedTech;
        foreach (var (k, v) in AdditionalFilters)
            d[k] = v;
        if (includeData) d["includeData"] = 1;
        return d;
    }
}
