// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class AccessControlsClient
{
    private readonly FieldRoutesCore _core;
    internal AccessControlsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesAccessControl> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesAccessControl>("accessControl", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesAccessControl>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["employeeIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesAccessControl>>("accessControl", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesAccessControl>> SearchAsync(FieldRoutesAccessControlSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesAccessControl>("accessControl", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
