// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class AdditionalContactsClient
{
    private readonly FieldRoutesCore _core;
    internal AdditionalContactsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesAdditionalContact> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesAdditionalContact>("additionalContact", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesAdditionalContactCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("additionalContact", "create", request.ToDictionary(), ct);

    public Task<List<FieldRoutesAdditionalContact>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["additionalContactIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesAdditionalContact>>("additionalContact", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesAdditionalContact>> SearchAsync(FieldRoutesAdditionalContactSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesAdditionalContact>("additionalContact", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
