// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class AppliedPaymentsClient
{
    private readonly FieldRoutesCore _core;
    internal AppliedPaymentsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesAppliedPayment> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesAppliedPayment>("appliedPayment", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesAppliedPayment>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["appliedPaymentIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesAppliedPayment>>("appliedPayment", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesAppliedPayment>> SearchAsync(FieldRoutesAppliedPaymentSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesAppliedPayment>("appliedPayment", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
