// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ApplicationMethodsClient
{
    private readonly FieldRoutesCore _core;
    internal ApplicationMethodsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesApplicationMethod> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesApplicationMethod>("applicationMethod", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesApplicationMethod>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["applciationMethodIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesApplicationMethod>>("applicationMethod", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesApplicationMethod>> SearchAsync(FieldRoutesApplicationMethodSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesApplicationMethod>("applicationMethod", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
