// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class AppointmentRemindersClient
{
    private readonly FieldRoutesCore _core;
    internal AppointmentRemindersClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesAppointmentReminder> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesAppointmentReminder>("appointmentReminder", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesAppointmentReminderCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("appointmentReminder", "create", request.ToDictionary(), ct);

    public Task<List<FieldRoutesAppointmentReminder>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["reminderIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesAppointmentReminder>>("appointmentReminder", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesAppointmentReminder>> SearchAsync(FieldRoutesAppointmentReminderSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesAppointmentReminder>("appointmentReminder", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UpdateAsync(FieldRoutesAppointmentReminderUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("appointmentReminder", "update", request.ToDictionary(), ct);

}
