// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class AppointmentsClient
{
    private readonly FieldRoutesCore _core;
    internal AppointmentsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesAppointment> GetAsync(int id, FieldRoutesAppointmentGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesAppointment>("appointment", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CancelAsync(FieldRoutesAppointmentCancelRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("appointment", "cancel", request.ToDictionary(), ct);

    public Task<int> CompleteAsync(FieldRoutesAppointmentCompleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("appointment", "complete", request.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesAppointmentCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("appointment", "create", request.ToDictionary(), ct);

    public Task<List<FieldRoutesAppointment>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesAppointmentGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["appointmentIDs"] = ids.Take(parameters?.MaxResults ?? 100).ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesAppointment>>("appointment", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesAppointment>> SearchAsync(FieldRoutesAppointmentSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesAppointment>("appointment", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UpdateAsync(FieldRoutesAppointmentUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("appointment", "update", request.ToDictionary(), ct);

}
