// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class AppointmentCancellationReasonsClient
{
    private readonly FieldRoutesCore _core;
    internal AppointmentCancellationReasonsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesAppointmentCancellationReason> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesAppointmentCancellationReason>("appointmentCancellationReason", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesAppointmentCancellationReason>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["cancellationReasonIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesAppointmentCancellationReason>>("appointmentCancellationReason", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesAppointmentCancellationReason>> SearchAsync(FieldRoutesAppointmentCancellationReasonSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesAppointmentCancellationReason>("appointmentCancellationReason", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
