// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class AppointmentRescheduleReasonsClient
{
    private readonly FieldRoutesCore _core;
    internal AppointmentRescheduleReasonsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesAppointmentRescheduleReason> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesAppointmentRescheduleReason>("appointmentRescheduleReason", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesAppointmentRescheduleReason>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["rescheduleReasonIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesAppointmentRescheduleReason>>("appointmentRescheduleReason", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesAppointmentRescheduleReason>> SearchAsync(FieldRoutesAppointmentRescheduleReasonSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesAppointmentRescheduleReason>("appointmentRescheduleReason", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
