// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class CancellationReasonsClient
{
    private readonly FieldRoutesCore _core;
    internal CancellationReasonsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesCancellationReason> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesCancellationReason>("cancellationReason", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesCancellationReason>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["reasonIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesCancellationReason>>("cancellationReason", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesCancellationReason>> SearchAsync(FieldRoutesCancellationReasonSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesCancellationReason>("cancellationReason", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
