// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ChangelogsClient
{
    private readonly FieldRoutesCore _core;
    internal ChangelogsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesChangelog> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesChangelog>("changelog", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesChangelog>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["changeIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesChangelog>>("changelog", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesChangelog>> SearchAsync(FieldRoutesChangelogSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesChangelog>("changelog", parameters.ToDictionary(includeData), ct);

}
