// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ChargebacksClient
{
    private readonly FieldRoutesCore _core;
    internal ChargebacksClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesChargeback> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesChargeback>("chargeback", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesChargeback>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["gatewayChargebackIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesChargeback>>("chargeback", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesChargeback>> SearchAsync(FieldRoutesChargebackSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesChargeback>("chargeback", parameters.ToDictionary(includeData), ct);

}
