// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ChemicalUsesClient
{
    private readonly FieldRoutesCore _core;
    internal ChemicalUsesClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesChemicalUse> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesChemicalUse>("chemicalUse", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesChemicalUse>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["chemicalUseIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesChemicalUse>>("chemicalUse", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesChemicalUse>> SearchAsync(FieldRoutesChemicalUseSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesChemicalUse>("chemicalUse", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
