// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ChemicalsClient
{
    private readonly FieldRoutesCore _core;
    internal ChemicalsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesChemical> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesChemical>("chemical", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesChemical>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["chemicalIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesChemical>>("chemical", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesChemical>> SearchAsync(FieldRoutesChemicalSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesChemical>("chemical", parameters.ToDictionary(includeData), ct);

}
