// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class CompassCustomersClient
{
    private readonly FieldRoutesCore _core;
    internal CompassCustomersClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesCompassCustomer> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesCompassCustomer>("compassCustomer", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesCompassCustomer>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["customerIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesCompassCustomer>>("compassCustomer", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesCompassCustomer>> SearchAsync(FieldRoutesCompassCustomerSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesCompassCustomer>("compassCustomer", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
