// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ContractsClient
{
    private readonly FieldRoutesCore _core;
    internal ContractsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesContract> GetAsync(int id, FieldRoutesContractGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesContract>("contract", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesContractCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("contract", "create", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesContractDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("contract", "delete", request.ToDictionary(), ct);

    public Task<List<FieldRoutesContract>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesContractGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["contractIDs"] = ids.ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesContract>>("contract", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesContract>> SearchAsync(FieldRoutesContractSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesContract>("contract", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesContractUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("contract", "update", request.ToDictionary(), ct);

}
