// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class CustomersClient
{
    private readonly FieldRoutesCore _core;
    internal CustomersClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesCustomer> GetAsync(int id, FieldRoutesCustomerGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesCustomer>("customer", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesCustomerCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("customer", "create", request.ToDictionary(), ct);

    public Task<FieldRoutesCustomerCreatePaymentProfileResult> CreatePaymentProfileAsync(FieldRoutesCustomerCreatePaymentProfileRequest request, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesCustomerCreatePaymentProfileResult>("customer", "createPaymentProfile", request.ToDictionary(), ct);

    public Task<List<FieldRoutesCustomer>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesCustomerGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["customerIDs"] = ids.ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesCustomer>>("customer", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesCustomer>> SearchAsync(FieldRoutesCustomerSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesCustomer>("customer", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesCustomerUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("customer", "update", request.ToDictionary(), ct);

    public Task<FieldRoutesCustomerUpdatePaymentProfileResult> UpdatePaymentProfileAsync(FieldRoutesCustomerUpdatePaymentProfileRequest request, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesCustomerUpdatePaymentProfileResult>("customer", "updatePaymentProfile", request.ToDictionary(), ct);

}
