// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class CustomerSourcesClient
{
    private readonly FieldRoutesCore _core;
    internal CustomerSourcesClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesCustomerSource> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesCustomerSource>("customerSource", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesCustomerSource>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["sourceIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesCustomerSource>>("customerSource", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesCustomerSource>> SearchAsync(FieldRoutesCustomerSourceSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesCustomerSource>("customerSource", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
