// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class CustomerFlagsClient
{
    private readonly FieldRoutesCore _core;
    internal CustomerFlagsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesCustomerFlag> GetAsync(int id, FieldRoutesCustomerFlagGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesCustomerFlag>("customerFlag", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<List<FieldRoutesCustomerFlag>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesCustomerFlagGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["customerIDs"] = ids.ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesCustomerFlag>>("customerFlag", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesCustomerFlag>> SearchAsync(FieldRoutesCustomerFlagSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesCustomerFlag>("customerFlag", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesCustomerFlagUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("customerFlag", "update", request.ToDictionary(), ct);

}
