// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class DiagramsClient
{
    private readonly FieldRoutesCore _core;
    internal DiagramsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesDiagram> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesDiagram>("diagram", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesDiagram>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["diagramIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesDiagram>>("diagram", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesDiagram>> SearchAsync(FieldRoutesDiagramSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesDiagram>("diagram", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UpdateAsync(FieldRoutesDiagramUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("diagram", "update", request.ToDictionary(), ct);

}
