// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class DisbursementsClient
{
    private readonly FieldRoutesCore _core;
    internal DisbursementsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesDisbursement> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesDisbursement>("disbursement", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesDisbursement>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["gatewayDisbursementIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesDisbursement>>("disbursement", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesDisbursement>> SearchAsync(FieldRoutesDisbursementSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesDisbursement>("disbursement", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
