// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class DisbursementItemsClient
{
    private readonly FieldRoutesCore _core;
    internal DisbursementItemsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesDisbursementItem> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesDisbursementItem>("disbursementItem", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesDisbursementItem>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["gatewayDisbursementEntryIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesDisbursementItem>>("disbursementItem", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesDisbursementItem>> SearchAsync(FieldRoutesDisbursementItemSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesDisbursementItem>("disbursementItem", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
