// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class DocumentsClient
{
    private readonly FieldRoutesCore _core;
    internal DocumentsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesDocument> GetAsync(int id, FieldRoutesDocumentGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesDocument>("document", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesDocumentCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("document", "create", request.ToDictionary(), ct);

    public Task<int> CreateEncodedAsync(FieldRoutesDocumentCreateEncodedRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("document", "createEncoded", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesDocumentDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("document", "delete", request.ToDictionary(), ct);

    public Task<List<FieldRoutesDocument>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesDocumentGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["uploadIDs"] = ids.ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesDocument>>("document", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesDocument>> SearchAsync(FieldRoutesDocumentSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesDocument>("document", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesDocumentUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("document", "update", request.ToDictionary(), ct);

}
