// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class DoorsClient
{
    private readonly FieldRoutesCore _core;
    internal DoorsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesDoor> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesDoor>("door", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesDoor>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["doorIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesDoor>>("door", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesDoor>> SearchAsync(FieldRoutesDoorSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesDoor>("door", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
