// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class EmployeeLocationsClient
{
    private readonly FieldRoutesCore _core;
    internal EmployeeLocationsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesEmployeeLocation> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesEmployeeLocation>("employeeLocation", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesEmployeeLocation>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["locationIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesEmployeeLocation>>("employeeLocation", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesEmployeeLocation>> SearchAsync(FieldRoutesEmployeeLocationSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesEmployeeLocation>("employeeLocation", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
