// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class EmployeesClient
{
    private readonly FieldRoutesCore _core;
    internal EmployeesClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesEmployee> GetAsync(int id, FieldRoutesEmployeeGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesEmployee>("employee", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesEmployeeCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("employee", "create", request.ToDictionary(), ct);

    public Task<int> DealiasAsync(FieldRoutesEmployeeDealiasRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("employee", "dealias", request.ToDictionary(), ct);

    public Task<List<FieldRoutesEmployee>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesEmployeeGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["employeeIDs"] = ids.ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesEmployee>>("employee", "get", d, ct);
    }

    public Task<int> ResetAsync(FieldRoutesEmployeeResetRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("employee", "reset", request.ToDictionary(), ct);

    public Task<SearchResponse<FieldRoutesEmployee>> SearchAsync(FieldRoutesEmployeeSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesEmployee>("employee", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesEmployeeUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("employee", "update", request.ToDictionary(), ct);

}
