// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FormsClient
{
    private readonly FieldRoutesCore _core;
    internal FormsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesForm> GetAsync(int id, FieldRoutesFormGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesForm>("form", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<List<FieldRoutesForm>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesFormGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["contractIDs"] = ids.Take(parameters?.MaxResults ?? 100).ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesForm>>("form", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesForm>> SearchAsync(FieldRoutesFormSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesForm>("form", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
