// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class GenericFlagsClient
{
    private readonly FieldRoutesCore _core;
    internal GenericFlagsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesGenericFlag> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesGenericFlag>("genericFlag", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesGenericFlag>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["genericFlagIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesGenericFlag>>("genericFlag", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesGenericFlag>> SearchAsync(FieldRoutesGenericFlagSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesGenericFlag>("genericFlag", parameters.ToDictionary(includeData), ct);

}
