// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class GenericFlagAssignmentsClient
{
    private readonly FieldRoutesCore _core;
    internal GenericFlagAssignmentsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesGenericFlagAssignment> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesGenericFlagAssignment>("genericFlagAssignment", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesGenericFlagAssignmentCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("genericFlagAssignment", "create", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesGenericFlagAssignmentDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("genericFlagAssignment", "delete", request.ToDictionary(), ct);

    public Task<List<FieldRoutesGenericFlagAssignment>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["genericFlagAssignmentIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesGenericFlagAssignment>>("genericFlagAssignment", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesGenericFlagAssignment>> SearchAsync(FieldRoutesGenericFlagAssignmentSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesGenericFlagAssignment>("genericFlagAssignment", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesGenericFlagAssignmentUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("genericFlagAssignment", "update", request.ToDictionary(), ct);

}
