// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class GlAccountsClient
{
    private readonly FieldRoutesCore _core;
    internal GlAccountsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesGlAccount> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesGlAccount>("glAccount", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesGlAccount>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["glAccountIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesGlAccount>>("glAccount", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesGlAccount>> SearchAsync(FieldRoutesGlAccountSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesGlAccount>("glAccount", parameters.ToDictionary(includeData), ct);

}
