// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class GroupsClient
{
    private readonly FieldRoutesCore _core;
    internal GroupsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesGroup> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesGroup>("group", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesGroupCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("group", "create", request.ToDictionary(), ct);

    public Task<List<FieldRoutesGroup>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["groupIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesGroup>>("group", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesGroup>> SearchAsync(FieldRoutesGroupSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesGroup>("group", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UpdateAsync(FieldRoutesGroupUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("group", "update", request.ToDictionary(), ct);

}
