// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class InsectsClient
{
    private readonly FieldRoutesCore _core;
    internal InsectsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesInsect> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesInsect>("insect", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesInsect>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["insectIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesInsect>>("insect", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesInsect>> SearchAsync(FieldRoutesInsectSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesInsect>("insect", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
