// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class LocationsClient
{
    private readonly FieldRoutesCore _core;
    internal LocationsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesLocation> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesLocation>("location", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesLocation>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["locationIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesLocation>>("location", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesLocation>> SearchAsync(FieldRoutesLocationSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesLocation>("location", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
