// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class NotesClient
{
    private readonly FieldRoutesCore _core;
    internal NotesClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesNote> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesNote>("note", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesNoteCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("note", "create", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesNoteDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("note", "delete", request.ToDictionary(), ct);

    public Task<List<FieldRoutesNote>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["noteIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesNote>>("note", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesNote>> SearchAsync(FieldRoutesNoteSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesNote>("note", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UpdateAsync(FieldRoutesNoteUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("note", "update", request.ToDictionary(), ct);

}
