// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class OfficesClient
{
    private readonly FieldRoutesCore _core;
    internal OfficesClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesOffice> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesOffice>("office", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesOffice>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["officeIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesOffice>>("office", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesOffice>> SearchAsync(FieldRoutesOfficeSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesOffice>("office", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
