// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class PaymentProfilesClient
{
    private readonly FieldRoutesCore _core;
    internal PaymentProfilesClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesPaymentProfile> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesPaymentProfile>("paymentProfile", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesPaymentProfileCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("paymentProfile", "create", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesPaymentProfileDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("paymentProfile", "delete", request.ToDictionary(), ct);

    public Task<List<FieldRoutesPaymentProfile>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["paymentProfileIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesPaymentProfile>>("paymentProfile", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesPaymentProfile>> SearchAsync(FieldRoutesPaymentProfileSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesPaymentProfile>("paymentProfile", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesPaymentProfileUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("paymentProfile", "update", request.ToDictionary(), ct);

}
