// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class PaymentsClient
{
    private readonly FieldRoutesCore _core;
    internal PaymentsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesPayment> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesPayment>("payment", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesPaymentCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("payment", "create", request.ToDictionary(), ct);

    public Task<int> CreateRefundAsync(FieldRoutesPaymentCreateRefundRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("payment", "createRefund", request.ToDictionary(), ct);

    public Task<List<FieldRoutesPayment>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["paymentIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesPayment>>("payment", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesPayment>> SearchAsync(FieldRoutesPaymentSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesPayment>("payment", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
