// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ProductsClient
{
    private readonly FieldRoutesCore _core;
    internal ProductsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesProduct> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesProduct>("product", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesProductCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("product", "create", request.ToDictionary(), ct);

    public Task<List<FieldRoutesProduct>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["productIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesProduct>>("product", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesProduct>> SearchAsync(FieldRoutesProductSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesProduct>("product", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesProductUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("product", "update", request.ToDictionary(), ct);

}
