// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class RegionsClient
{
    private readonly FieldRoutesCore _core;
    internal RegionsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesRegion> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesRegion>("region", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesRegion>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["regionIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesRegion>>("region", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesRegion>> SearchAsync(FieldRoutesRegionSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesRegion>("region", parameters.ToDictionary(includeData), ct);

}
