// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ReserviceReasonsClient
{
    private readonly FieldRoutesCore _core;
    internal ReserviceReasonsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesReserviceReason> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesReserviceReason>("reserviceReason", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesReserviceReason>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["reserviceReasonIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesReserviceReason>>("reserviceReason", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesReserviceReason>> SearchAsync(FieldRoutesReserviceReasonSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesReserviceReason>("reserviceReason", parameters.ToDictionary(includeData), ct);

}
