// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ReviewsClient
{
    private readonly FieldRoutesCore _core;
    internal ReviewsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesReview> GetAsync(int id, FieldRoutesReviewGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesReview>("review", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesReviewCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("review", "create", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesReviewDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("review", "delete", request.ToDictionary(), ct);

    public Task<List<FieldRoutesReview>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesReviewGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["feedbackIDs"] = ids.ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesReview>>("review", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesReview>> SearchAsync(FieldRoutesReviewSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesReview>("review", parameters.ToDictionary(includeData), ct);

    public Task<FieldRoutesReviewSummaryResult> SummaryAsync(FieldRoutesReviewSummaryRequest request, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesReviewSummaryResult>("review", "summary", request.ToDictionary(), ct);

    public Task<int> UpdateAsync(FieldRoutesReviewUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("review", "update", request.ToDictionary(), ct);

}
