// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class RouteTemplatesClient
{
    private readonly FieldRoutesCore _core;
    internal RouteTemplatesClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesRouteTemplate> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesRouteTemplate>("routeTemplate", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesRouteTemplate>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["templateIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesRouteTemplate>>("routeTemplate", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesRouteTemplate>> SearchAsync(FieldRoutesRouteTemplateSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesRouteTemplate>("routeTemplate", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
