// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class RoutesClient
{
    private readonly FieldRoutesCore _core;
    internal RoutesClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesRoute> GetAsync(int id, FieldRoutesRouteGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesRoute>("route", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesRouteCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("route", "create", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesRouteDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("route", "delete", request.ToDictionary(), ct);

    public Task<List<FieldRoutesRoute>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesRouteGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["routeIDs"] = ids.ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesRoute>>("route", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesRoute>> SearchAsync(FieldRoutesRouteSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesRoute>("route", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesRouteUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("route", "update", request.ToDictionary(), ct);

}
