// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ServicePlansClient
{
    private readonly FieldRoutesCore _core;
    internal ServicePlansClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesServicePlan> GetAsync(int id, FieldRoutesServicePlanGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesServicePlan>("servicePlan", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesServicePlanCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("servicePlan", "create", request.ToDictionary(), ct);

    public Task<List<FieldRoutesServicePlan>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesServicePlanGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["subscriptionIDs"] = ids.Take(parameters?.MaxResults ?? 100).ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesServicePlan>>("servicePlan", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesServicePlan>> SearchAsync(FieldRoutesServicePlanSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesServicePlan>("servicePlan", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UpdateAsync(FieldRoutesServicePlanUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("servicePlan", "update", request.ToDictionary(), ct);

    public Task<int> UpdateLeadStageAsync(FieldRoutesServicePlanUpdateLeadStageRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("servicePlan", "updateLeadStage", request.ToDictionary(), ct);

}
