// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class ServicePlanRoundsClient
{
    private readonly FieldRoutesCore _core;
    internal ServicePlanRoundsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesServicePlanRound> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesServicePlanRound>("servicePlanRound", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesServicePlanRound>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["subscriptionIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesServicePlanRound>>("servicePlanRound", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesServicePlanRound>> SearchAsync(FieldRoutesServicePlanRoundSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesServicePlanRound>("servicePlanRound", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UpdateAsync(FieldRoutesServicePlanRoundUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("servicePlanRound", "update", request.ToDictionary(), ct);

}
