// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class SkillsClient
{
    private readonly FieldRoutesCore _core;
    internal SkillsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesSkill> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesSkill>("skill", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesSkillCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("skill", "create", request.ToDictionary(), ct);

    public Task<List<FieldRoutesSkill>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["skillIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesSkill>>("skill", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesSkill>> SearchAsync(FieldRoutesSkillSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesSkill>("skill", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UpdateAsync(FieldRoutesSkillUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("skill", "update", request.ToDictionary(), ct);

}
