// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class SpotsClient
{
    private readonly FieldRoutesCore _core;
    internal SpotsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesSpot> GetAsync(int id, FieldRoutesSpotGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesSpot>("spot", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> BlockAsync(FieldRoutesSpotBlockRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("spot", "block", request.ToDictionary(), ct);

    public Task<List<FieldRoutesSpot>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesSpotGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["spotIDs"] = ids.Take(parameters?.MaxResults ?? 100).ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesSpot>>("spot", "get", d, ct);
    }

    public Task<int> ReleaseAsync(FieldRoutesSpotReleaseRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("spot", "release", request.ToDictionary(), ct);

    public Task<int> ReserveAsync(FieldRoutesSpotReserveRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("spot", "reserve", request.ToDictionary(), ct);

    public Task<SearchResponse<FieldRoutesSpot>> SearchAsync(FieldRoutesSpotSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesSpot>("spot", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

    public Task<int> UnblockAsync(FieldRoutesSpotUnblockRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("spot", "unblock", request.ToDictionary(), ct);

}
