// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class SubscriptionsClient
{
    private readonly FieldRoutesCore _core;
    internal SubscriptionsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesSubscription> GetAsync(int id, FieldRoutesSubscriptionGetParameters? parameters = null, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesSubscription>("subscription", id.ToString(CultureInfo.InvariantCulture), parameters?.ToDictionary(), ct);

    public Task<int> CreateAsync(FieldRoutesSubscriptionCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("subscription", "create", request.ToDictionary(), ct);

    public Task<int> CreateInitialAddOnAsync(FieldRoutesSubscriptionCreateInitialAddOnRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("subscription", "createInitialAddOn", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesSubscriptionDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("subscription", "delete", request.ToDictionary(), ct);

    public Task<int> DeleteInitialAddOnAsync(FieldRoutesSubscriptionDeleteInitialAddOnRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("subscription", "deleteInitialAddOn", request.ToDictionary(), ct);

    public Task<List<FieldRoutesSubscription>> GetBulkAsync(IEnumerable<int> ids, FieldRoutesSubscriptionGetBulkParameters? parameters = null, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> { 
            ["subscriptionIDs"] = ids.ToList(),
        };
        if (parameters is not null)
            foreach (var (k, v) in parameters.ToDictionary()) d[k] = v;
        return _core.PostAsync<List<FieldRoutesSubscription>>("subscription", "get", d, ct);
    }

    public Task<FieldRoutesSubscriptionGetInitialAddOnsResult> GetInitialAddOnsAsync(FieldRoutesSubscriptionGetInitialAddOnsRequest request, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesSubscriptionGetInitialAddOnsResult>("subscription", "getInitialAddOns", request.ToDictionary(), ct);

    public Task<SearchResponse<FieldRoutesSubscription>> SearchAsync(FieldRoutesSubscriptionSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesSubscription>("subscription", parameters.ToDictionary(includeData), ct);

    public Task<int> SetInitialAddOnsAsync(FieldRoutesSubscriptionSetInitialAddOnsRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("subscription", "setInitialAddOns", request.ToDictionary(), ct);

    public Task<int> UpdateAsync(FieldRoutesSubscriptionUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("subscription", "update", request.ToDictionary(), ct);

    public Task<int> UpdateInitialAddOnAsync(FieldRoutesSubscriptionUpdateInitialAddOnRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("subscription", "updateInitialAddOn", request.ToDictionary(), ct);

    public Task<int> UpdateLeadStageAsync(FieldRoutesSubscriptionUpdateLeadStageRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("subscription", "updateLeadStage", request.ToDictionary(), ct);

}
