// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class TasksClient
{
    private readonly FieldRoutesCore _core;
    internal TasksClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesTask> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesTask>("task", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesTaskCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("task", "create", request.ToDictionary(), ct);

    public Task<List<FieldRoutesTask>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["taskIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesTask>>("task", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesTask>> SearchAsync(FieldRoutesTaskSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesTask>("task", parameters.ToDictionary(includeData), ct);

    public Task<int> UpdateAsync(FieldRoutesTaskUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("task", "update", request.ToDictionary(), ct);

}
