// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class TicketsClient
{
    private readonly FieldRoutesCore _core;
    internal TicketsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesTicket> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesTicket>("ticket", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<int> CreateAsync(FieldRoutesTicketCreateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("ticket", "create", request.ToDictionary(), ct);

    public Task<int> CreateAddOnAsync(FieldRoutesTicketCreateAddOnRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("ticket", "createAddOn", request.ToDictionary(), ct);

    public Task<int> DeleteAsync(FieldRoutesTicketDeleteRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("ticket", "delete", request.ToDictionary(), ct);

    public Task<int> DeleteAddOnAsync(FieldRoutesTicketDeleteAddOnRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("ticket", "deleteAddOn", request.ToDictionary(), ct);

    public Task<List<FieldRoutesTicket>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["ticketIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesTicket>>("ticket", "get", d, ct);
    }

    public Task<FieldRoutesTicketGetAddOnsResult> GetAddOnsAsync(FieldRoutesTicketGetAddOnsRequest request, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesTicketGetAddOnsResult>("ticket", "getAddOns", request.ToDictionary(), ct);

    public Task<SearchResponse<FieldRoutesTicket>> SearchAsync(FieldRoutesTicketSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesTicket>("ticket", parameters.ToDictionary(includeData), ct);

    public Task<int> SetAddOnsAsync(FieldRoutesTicketSetAddOnsRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("ticket", "setAddOns", request.ToDictionary(), ct);

    public Task<int> UpdateAsync(FieldRoutesTicketUpdateRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("ticket", "update", request.ToDictionary(), ct);

    public Task<int> UpdateAddOnAsync(FieldRoutesTicketUpdateAddOnRequest request, CancellationToken ct = default)
        => _core.PostAsync<int>("ticket", "updateAddOn", request.ToDictionary(), ct);

}
