// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class TimeClockCategorysClient
{
    private readonly FieldRoutesCore _core;
    internal TimeClockCategorysClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesTimeClockCategory> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesTimeClockCategory>("timeClockCategory", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesTimeClockCategory>> GetBulkAsync(IEnumerable<int> ids, int maxResults = 100, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["clockCategoryIDs"] = ids.Take(maxResults).ToList(),
        };
        return _core.PostAsync<List<FieldRoutesTimeClockCategory>>("timeClockCategory", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesTimeClockCategory>> SearchAsync(FieldRoutesTimeClockCategorySearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesTimeClockCategory>("timeClockCategory", parameters.ToDictionary(includeData), parameters.MaxResults, ct);

}
