// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class TimeClocksClient
{
    private readonly FieldRoutesCore _core;
    internal TimeClocksClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesTimeClock> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesTimeClock>("timeClock", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesTimeClock>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["entryIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesTimeClock>>("timeClock", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesTimeClock>> SearchAsync(FieldRoutesTimeClockSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesTimeClock>("timeClock", parameters.ToDictionary(includeData), ct);

}
