// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class UnitsClient
{
    private readonly FieldRoutesCore _core;
    internal UnitsClient(FieldRoutesCore core) => _core = core;

    public Task<FieldRoutesUnit> GetAsync(int id, CancellationToken ct = default)
        => _core.PostAsync<FieldRoutesUnit>("unit", id.ToString(CultureInfo.InvariantCulture), null, ct);

    public Task<List<FieldRoutesUnit>> GetBulkAsync(IEnumerable<int> ids, CancellationToken ct = default)
    {
        var d = new Dictionary<string, object?> {
            ["unitIDs"] = ids.ToList(),
        };
        return _core.PostAsync<List<FieldRoutesUnit>>("unit", "get", d, ct);
    }

    public Task<SearchResponse<FieldRoutesUnit>> SearchAsync(FieldRoutesUnitSearchParameters parameters, bool includeData = false, CancellationToken ct = default)
        => _core.PostSearchAsync<FieldRoutesUnit>("unit", parameters.ToDictionary(includeData), ct);

}
