// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;
using FieldRoutesApiClient.Entities;

namespace FieldRoutesApiClient.Core;

/// <summary>Typed facade over every FieldRoutes entity client. Register with AddFieldRoutesClient and inject.</summary>
public sealed partial class FieldRoutesApi
{
    private readonly Dictionary<string, object> _clients = new();

    public AccessControlsClient AccessControls => (AccessControlsClient)(_clients.TryGetValue(nameof(AccessControls), out var c) ? c : _clients[nameof(AccessControls)] = new AccessControlsClient(_core));
    public AdditionalContactsClient AdditionalContacts => (AdditionalContactsClient)(_clients.TryGetValue(nameof(AdditionalContacts), out var c) ? c : _clients[nameof(AdditionalContacts)] = new AdditionalContactsClient(_core));
    public ApplicationMethodsClient ApplicationMethods => (ApplicationMethodsClient)(_clients.TryGetValue(nameof(ApplicationMethods), out var c) ? c : _clients[nameof(ApplicationMethods)] = new ApplicationMethodsClient(_core));
    public AppliedPaymentsClient AppliedPayments => (AppliedPaymentsClient)(_clients.TryGetValue(nameof(AppliedPayments), out var c) ? c : _clients[nameof(AppliedPayments)] = new AppliedPaymentsClient(_core));
    public AppointmentsClient Appointments => (AppointmentsClient)(_clients.TryGetValue(nameof(Appointments), out var c) ? c : _clients[nameof(Appointments)] = new AppointmentsClient(_core));
    public AppointmentCancellationReasonsClient AppointmentCancellationReasons => (AppointmentCancellationReasonsClient)(_clients.TryGetValue(nameof(AppointmentCancellationReasons), out var c) ? c : _clients[nameof(AppointmentCancellationReasons)] = new AppointmentCancellationReasonsClient(_core));
    public AppointmentRemindersClient AppointmentReminders => (AppointmentRemindersClient)(_clients.TryGetValue(nameof(AppointmentReminders), out var c) ? c : _clients[nameof(AppointmentReminders)] = new AppointmentRemindersClient(_core));
    public AppointmentRescheduleReasonsClient AppointmentRescheduleReasons => (AppointmentRescheduleReasonsClient)(_clients.TryGetValue(nameof(AppointmentRescheduleReasons), out var c) ? c : _clients[nameof(AppointmentRescheduleReasons)] = new AppointmentRescheduleReasonsClient(_core));
    public CancellationReasonsClient CancellationReasons => (CancellationReasonsClient)(_clients.TryGetValue(nameof(CancellationReasons), out var c) ? c : _clients[nameof(CancellationReasons)] = new CancellationReasonsClient(_core));
    public ChangelogsClient Changelogs => (ChangelogsClient)(_clients.TryGetValue(nameof(Changelogs), out var c) ? c : _clients[nameof(Changelogs)] = new ChangelogsClient(_core));
    public ChargebacksClient Chargebacks => (ChargebacksClient)(_clients.TryGetValue(nameof(Chargebacks), out var c) ? c : _clients[nameof(Chargebacks)] = new ChargebacksClient(_core));
    public ChemicalsClient Chemicals => (ChemicalsClient)(_clients.TryGetValue(nameof(Chemicals), out var c) ? c : _clients[nameof(Chemicals)] = new ChemicalsClient(_core));
    public ChemicalUsesClient ChemicalUses => (ChemicalUsesClient)(_clients.TryGetValue(nameof(ChemicalUses), out var c) ? c : _clients[nameof(ChemicalUses)] = new ChemicalUsesClient(_core));
    public CompassCustomersClient CompassCustomers => (CompassCustomersClient)(_clients.TryGetValue(nameof(CompassCustomers), out var c) ? c : _clients[nameof(CompassCustomers)] = new CompassCustomersClient(_core));
    public ContractsClient Contracts => (ContractsClient)(_clients.TryGetValue(nameof(Contracts), out var c) ? c : _clients[nameof(Contracts)] = new ContractsClient(_core));
    public CustomersClient Customers => (CustomersClient)(_clients.TryGetValue(nameof(Customers), out var c) ? c : _clients[nameof(Customers)] = new CustomersClient(_core));
    public CustomerFlagsClient CustomerFlags => (CustomerFlagsClient)(_clients.TryGetValue(nameof(CustomerFlags), out var c) ? c : _clients[nameof(CustomerFlags)] = new CustomerFlagsClient(_core));
    public CustomerSourcesClient CustomerSources => (CustomerSourcesClient)(_clients.TryGetValue(nameof(CustomerSources), out var c) ? c : _clients[nameof(CustomerSources)] = new CustomerSourcesClient(_core));
    public DiagramsClient Diagrams => (DiagramsClient)(_clients.TryGetValue(nameof(Diagrams), out var c) ? c : _clients[nameof(Diagrams)] = new DiagramsClient(_core));
    public DisbursementsClient Disbursements => (DisbursementsClient)(_clients.TryGetValue(nameof(Disbursements), out var c) ? c : _clients[nameof(Disbursements)] = new DisbursementsClient(_core));
    public DisbursementItemsClient DisbursementItems => (DisbursementItemsClient)(_clients.TryGetValue(nameof(DisbursementItems), out var c) ? c : _clients[nameof(DisbursementItems)] = new DisbursementItemsClient(_core));
    public DocumentsClient Documents => (DocumentsClient)(_clients.TryGetValue(nameof(Documents), out var c) ? c : _clients[nameof(Documents)] = new DocumentsClient(_core));
    public DoorsClient Doors => (DoorsClient)(_clients.TryGetValue(nameof(Doors), out var c) ? c : _clients[nameof(Doors)] = new DoorsClient(_core));
    public EmployeesClient Employees => (EmployeesClient)(_clients.TryGetValue(nameof(Employees), out var c) ? c : _clients[nameof(Employees)] = new EmployeesClient(_core));
    public EmployeeLocationsClient EmployeeLocations => (EmployeeLocationsClient)(_clients.TryGetValue(nameof(EmployeeLocations), out var c) ? c : _clients[nameof(EmployeeLocations)] = new EmployeeLocationsClient(_core));
    public FormsClient Forms => (FormsClient)(_clients.TryGetValue(nameof(Forms), out var c) ? c : _clients[nameof(Forms)] = new FormsClient(_core));
    public GenericFlagsClient GenericFlags => (GenericFlagsClient)(_clients.TryGetValue(nameof(GenericFlags), out var c) ? c : _clients[nameof(GenericFlags)] = new GenericFlagsClient(_core));
    public GenericFlagAssignmentsClient GenericFlagAssignments => (GenericFlagAssignmentsClient)(_clients.TryGetValue(nameof(GenericFlagAssignments), out var c) ? c : _clients[nameof(GenericFlagAssignments)] = new GenericFlagAssignmentsClient(_core));
    public GlAccountsClient GlAccounts => (GlAccountsClient)(_clients.TryGetValue(nameof(GlAccounts), out var c) ? c : _clients[nameof(GlAccounts)] = new GlAccountsClient(_core));
    public GroupsClient Groups => (GroupsClient)(_clients.TryGetValue(nameof(Groups), out var c) ? c : _clients[nameof(Groups)] = new GroupsClient(_core));
    public InsectsClient Insects => (InsectsClient)(_clients.TryGetValue(nameof(Insects), out var c) ? c : _clients[nameof(Insects)] = new InsectsClient(_core));
    public KnocksClient Knocks => (KnocksClient)(_clients.TryGetValue(nameof(Knocks), out var c) ? c : _clients[nameof(Knocks)] = new KnocksClient(_core));
    public LocationsClient Locations => (LocationsClient)(_clients.TryGetValue(nameof(Locations), out var c) ? c : _clients[nameof(Locations)] = new LocationsClient(_core));
    public NotesClient Notes => (NotesClient)(_clients.TryGetValue(nameof(Notes), out var c) ? c : _clients[nameof(Notes)] = new NotesClient(_core));
    public OfficesClient Offices => (OfficesClient)(_clients.TryGetValue(nameof(Offices), out var c) ? c : _clients[nameof(Offices)] = new OfficesClient(_core));
    public PaymentsClient Payments => (PaymentsClient)(_clients.TryGetValue(nameof(Payments), out var c) ? c : _clients[nameof(Payments)] = new PaymentsClient(_core));
    public PaymentProfilesClient PaymentProfiles => (PaymentProfilesClient)(_clients.TryGetValue(nameof(PaymentProfiles), out var c) ? c : _clients[nameof(PaymentProfiles)] = new PaymentProfilesClient(_core));
    public ProductsClient Products => (ProductsClient)(_clients.TryGetValue(nameof(Products), out var c) ? c : _clients[nameof(Products)] = new ProductsClient(_core));
    public RegionsClient Regions => (RegionsClient)(_clients.TryGetValue(nameof(Regions), out var c) ? c : _clients[nameof(Regions)] = new RegionsClient(_core));
    public ReserviceReasonsClient ReserviceReasons => (ReserviceReasonsClient)(_clients.TryGetValue(nameof(ReserviceReasons), out var c) ? c : _clients[nameof(ReserviceReasons)] = new ReserviceReasonsClient(_core));
    public ReviewsClient Reviews => (ReviewsClient)(_clients.TryGetValue(nameof(Reviews), out var c) ? c : _clients[nameof(Reviews)] = new ReviewsClient(_core));
    public RoutesClient Routes => (RoutesClient)(_clients.TryGetValue(nameof(Routes), out var c) ? c : _clients[nameof(Routes)] = new RoutesClient(_core));
    public RouteTemplatesClient RouteTemplates => (RouteTemplatesClient)(_clients.TryGetValue(nameof(RouteTemplates), out var c) ? c : _clients[nameof(RouteTemplates)] = new RouteTemplatesClient(_core));
    public ServicePlansClient ServicePlans => (ServicePlansClient)(_clients.TryGetValue(nameof(ServicePlans), out var c) ? c : _clients[nameof(ServicePlans)] = new ServicePlansClient(_core));
    public ServicePlanRoundsClient ServicePlanRounds => (ServicePlanRoundsClient)(_clients.TryGetValue(nameof(ServicePlanRounds), out var c) ? c : _clients[nameof(ServicePlanRounds)] = new ServicePlanRoundsClient(_core));
    public ServiceTypesClient ServiceTypes => (ServiceTypesClient)(_clients.TryGetValue(nameof(ServiceTypes), out var c) ? c : _clients[nameof(ServiceTypes)] = new ServiceTypesClient(_core));
    public SkillsClient Skills => (SkillsClient)(_clients.TryGetValue(nameof(Skills), out var c) ? c : _clients[nameof(Skills)] = new SkillsClient(_core));
    public SpotsClient Spots => (SpotsClient)(_clients.TryGetValue(nameof(Spots), out var c) ? c : _clients[nameof(Spots)] = new SpotsClient(_core));
    public SubscriptionsClient Subscriptions => (SubscriptionsClient)(_clients.TryGetValue(nameof(Subscriptions), out var c) ? c : _clients[nameof(Subscriptions)] = new SubscriptionsClient(_core));
    public TasksClient Tasks => (TasksClient)(_clients.TryGetValue(nameof(Tasks), out var c) ? c : _clients[nameof(Tasks)] = new TasksClient(_core));
    public TeamsClient Teams => (TeamsClient)(_clients.TryGetValue(nameof(Teams), out var c) ? c : _clients[nameof(Teams)] = new TeamsClient(_core));
    public TicketsClient Tickets => (TicketsClient)(_clients.TryGetValue(nameof(Tickets), out var c) ? c : _clients[nameof(Tickets)] = new TicketsClient(_core));
    public TicketItemsClient TicketItems => (TicketItemsClient)(_clients.TryGetValue(nameof(TicketItems), out var c) ? c : _clients[nameof(TicketItems)] = new TicketItemsClient(_core));
    public TimeClocksClient TimeClocks => (TimeClocksClient)(_clients.TryGetValue(nameof(TimeClocks), out var c) ? c : _clients[nameof(TimeClocks)] = new TimeClocksClient(_core));
    public TimeClockCategorysClient TimeClockCategorys => (TimeClockCategorysClient)(_clients.TryGetValue(nameof(TimeClockCategorys), out var c) ? c : _clients[nameof(TimeClockCategorys)] = new TimeClockCategorysClient(_core));
    public UnitsClient Units => (UnitsClient)(_clients.TryGetValue(nameof(Units), out var c) ? c : _clients[nameof(Units)] = new UnitsClient(_core));
}
