// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesDisbursementItem record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesDisbursementItem
{
    public int? GatewayDisbursementEntryID { get; set; }
    public int? GatewayDisbursementID { get; set; }
    public string? DateCreated { get; set; }
    public string? DateUpdated { get; set; }
    public string? BillingFirstName { get; set; }
    public string? BillingLastName { get; set; }
    public decimal? Amount { get; set; }
    public decimal? ActualAmount { get; set; }
    public string? Description { get; set; }
    public int? IsFee { get; set; }
    public int? GatewayEventID { get; set; }
    public string? GatewayEventType { get; set; }
    public string? GatewayEventFeeType { get; set; }
    public string? GatewayEventDescription { get; set; }
}
