// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesTeam record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesTeam
{
    public int? TeamID { get; set; }
    public int? OfficeID { get; set; }
    public string? Name { get; set; }
    public int? TeamLeader { get; set; }
    public int? EmployeeIDs { get; set; }
}
