// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesAppliedPayment record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesAppliedPayment
{
    public int? AppliedPaymentID { get; set; }
    public int? OfficeID { get; set; }
    public int? PaymentID { get; set; }
    public int? TicketID { get; set; }
    public int? CustomerID { get; set; }
    public string? DateApplied { get; set; }
    public int? AppliedBy { get; set; }
    public decimal? AppliedAmount { get; set; }
    public decimal? TaxCollected { get; set; }
    public string? DateUpdated { get; set; }
}
