// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesGenericFlagAssignment record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesGenericFlagAssignment
{
    public int? GenericFlagAssignmentID { get; set; }
    public int? GenericFlagID { get; set; }
    public int? EntityID { get; set; }
    public string? Type { get; set; }
    public string? DateCreated { get; set; }
    public string? DateUpdated { get; set; }
}
