// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesAccessControl record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesAccessControl
{
    public int? EmployeeID { get; set; }
    public int? AccessControlProfileID { get; set; }
    public int? Admin { get; set; }
    public int? AdminMessage { get; set; }
    public int? EditPreferences { get; set; }
    public int? ViewOwnRoutes { get; set; }
    public int? ViewOtherRoutes { get; set; }
    public int? EditOwnRoutes { get; set; }
    public int? EditOtherRoutes { get; set; }
    public int? CreateRoutes { get; set; }
    public int? DeleteRoutes { get; set; }
    public int? LockUnlockRoutes { get; set; }
    public int? ScheduleOnLockedRoutes { get; set; }
    public int? ScheduleOwn { get; set; }
    public int? CancelOwn { get; set; }
    public int? EditOthers { get; set; }
    public int? CanUnlockAppointments { get; set; }
    public int? IntelligentRouting { get; set; }
    public int? EditMap { get; set; }
    public int? ViewProdValue { get; set; }
    public int? UseTechRoutesStructures { get; set; }
    public int? ViewUsers { get; set; }
    public int? AddUsers { get; set; }
    public int? EditUsers { get; set; }
    public int? ViewTechs { get; set; }
    public int? AddTechs { get; set; }
    public int? EditTechs { get; set; }
    public int? ViewSalesmen { get; set; }
    public int? AddSalesmen { get; set; }
    public int? EditSalesmen { get; set; }
    public int? ViewOwnTimeSheet { get; set; }
    public int? ViewOtherTimeSheet { get; set; }
    public int? EditOwnTimeSheet { get; set; }
    public int? EditOtherTimeSheet { get; set; }
    public int? OverrideTimeClockRestrictions { get; set; }
    public int? CanSpyOnReps { get; set; }
    public int? EditTeams { get; set; }
    public int? ViewEmployeeFinancialSettings { get; set; }
    public int? EditEmployeeFinancialSettings { get; set; }
    public int? ViewOwnTasks { get; set; }
    public int? ViewOtherTasks { get; set; }
    public int? EditOwnTasks { get; set; }
    public int? EditOtherTasks { get; set; }
    public int? ViewAlerts { get; set; }
    public int? ViewTransactions { get; set; }
    public int? AddCharge { get; set; }
    public int? ApplyPayment { get; set; }
    public int? EditTransactions { get; set; }
    public int? ProcessRefunds { get; set; }
    public int? DeleteInvoice { get; set; }
    public int? CreateCoupon { get; set; }
    public int? InvoiceNegativeItem { get; set; }
    public int? ClosedMonthAppointmentCompletion { get; set; }
    public int? CreateCustomers { get; set; }
    public int? ViewOwnCustomers { get; set; }
    public int? ViewOtherCustomers { get; set; }
    public int? EditOwnCustomers { get; set; }
    public int? EditOtherCustomers { get; set; }
    public int? ToggleCustomerStatus { get; set; }
    public int? EditRedNotes { get; set; }
    public int? EditCancellationDates { get; set; }
    public int? ToggleSubscriptionStatus { get; set; }
    public int? ViewOwnSubscriptions { get; set; }
    public int? ViewOtherSubscriptions { get; set; }
    public int? EditOwnSubscriptions { get; set; }
    public int? EditOtherSubscriptions { get; set; }
    public int? AccessSentricon { get; set; }
    public int? EditOwnSalesRep { get; set; }
    public int? EditOtherSalesRep { get; set; }
    public int? ViewLeaderBoardsAllOffices { get; set; }
    public int? CreateCustomersFromMobile { get; set; }
    public int? ViewOwnLeads { get; set; }
    public int? ViewOtherLeads { get; set; }
    public int? EditOwnLeads { get; set; }
    public int? EditOtherLeads { get; set; }
    public int? AssignBillingAccount { get; set; }
    public int? ViewOwnBilling { get; set; }
    public int? ViewOtherBilling { get; set; }
    public int? EditOwnBilling { get; set; }
    public int? EditOtherBilling { get; set; }
    public int? AddOwnBilling { get; set; }
    public int? AddOtherBilling { get; set; }
    public int? ApproveForms { get; set; }
    public int? ViewOwnInvoices { get; set; }
    public int? ViewOtherInvoices { get; set; }
    public int? EditTaxable { get; set; }
    public int? HideCommercialPricing { get; set; }
    public int? HideResidentialPricing { get; set; }
    public int? IgnoreMinInitial { get; set; }
    public int? IgnoreMinRecurring { get; set; }
    public int? IgnoreMinContractValue { get; set; }
    public int? ViewSalesmanReports { get; set; }
    public int? ViewDetailedSalesReports { get; set; }
    public int? ViewOfficeReports { get; set; }
    public int? ViewCustomReports { get; set; }
    public int? ViewCustomerReport { get; set; }
    public int? ViewDashboard { get; set; }
    public int? SalesroutesBaseballRevenue { get; set; }
    public int? ServiceNotificationApproval { get; set; }
    public int? ViewDisbursementsReport { get; set; }
    public int? ActiveCustomersWidget { get; set; }
    public int? SubscriptionTypesWidget { get; set; }
    public int? CancelReasonsWidget { get; set; }
    public int? MonthlyServicesWidget { get; set; }
    public int? StarRatingWidget { get; set; }
    public int? CollectionsWidget { get; set; }
    public int? CompletionPercentageWidget { get; set; }
    public int? RegularStopsPerRouteWidget { get; set; }
    public int? APayCustomersWidget { get; set; }
    public int? AccountAgeWidget { get; set; }
    public int? PaymentBreakdownWidget { get; set; }
    public int? AverageRatesWidget { get; set; }
    public int? AverageContractValuesWidget { get; set; }
    public int? CustomerAgeWidget { get; set; }
    public int? CustomerSourcesWidget { get; set; }
    public int? ExtraCardsWidget { get; set; }
    public int? MonthlyBillingWidget { get; set; }
    public int? DebitBalanceWidget { get; set; }
    public int? RevenueByServiceTypeWidget { get; set; }
    public int? RevenueByMonthWidget { get; set; }
    public int? RecurringAnnualRevenueWidget { get; set; }
    public string? AccessControlProfileName { get; set; }
    public int? ViewAssignmentLayers { get; set; }
    public int? EditAnyBoundaryRegion { get; set; }
    public int? EditBoundaryRegionInManagedArea { get; set; }
    public int? EditAnyAssignmentRegion { get; set; }
    public int? EditAssignmentRegionInManagedArea { get; set; }
    public int? ViewReportingLayers { get; set; }
    public int? EditOwnReportingRegions { get; set; }
    public int? EditOtherReportingRegions { get; set; }
    public int? ViewDataLayers { get; set; }
    public int? EditOwnDataLayers { get; set; }
    public int? EditOtherDataLayers { get; set; }
    public int? ViewDoorKnockSystemLayer { get; set; }
    public int? ViewCustomerSystemLayer { get; set; }
    public int? ViewFeedback { get; set; }
    public string? DateUpdated { get; set; }
}
