// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesTask record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesTask
{
    public int? TaskIDs { get; set; }
    public int? OfficeID { get; set; }
    public int? CustomerID { get; set; }
    public int? AddedBy { get; set; }
    public int? AssignedTo { get; set; }
    public int? CompletedBy { get; set; }
    public int? Type { get; set; }
    public string? DueDate { get; set; }
    public string? DateAdded { get; set; }
    public string? DateCompleted { get; set; }
    public int? Category { get; set; }
    public int? CategoryDescription { get; set; }
    public string? Task { get; set; }
    public string? CompletionNotes { get; set; }
    public int? ReferenceID { get; set; }
    public string? Phone { get; set; }
    public string? DateUpdated { get; set; }
    public string? Status { get; set; }
}
