// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesProduct record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesProduct
{
    public int? ProductID { get; set; }
    public int? OfficeID { get; set; }
    public string? Description { get; set; }
    public string? GlAccountID { get; set; }
    public decimal? Amount { get; set; }
    public int? Taxable { get; set; }
    public string? Code { get; set; }
    public string? Category { get; set; }
    public int? Visible { get; set; }
    public int? SalesVisible { get; set; }
    public int? Recurring { get; set; }
}
