// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesTicketItem record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesTicketItem
{
    public int? ItemID { get; set; }
    public int? TicketID { get; set; }
    public int? OfficeID { get; set; }
    public string? Description { get; set; }
    public int? Quantity { get; set; }
    public decimal? Amount { get; set; }
    public int? ProductID { get; set; }
    public int? ServiceID { get; set; }
    public int? Taxable { get; set; }
    public int? CreditTo { get; set; }
    public int? UnitID { get; set; }
    public string? GlNumber { get; set; }
    public int? MeasurementSF { get; set; }
    public int? MeasurementLF { get; set; }
    public int? PrepaymentAmount { get; set; }
    public string? Category { get; set; }
    public string? Code { get; set; }
    public string? DateCreated { get; set; }
    public string? DateUpdated { get; set; }
}
