// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesGenericFlag record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesGenericFlag
{
    public int? GenericFlagID { get; set; }
    public int? OfficeIDs { get; set; }
    public int? OfficeID { get; set; }
    public string? Code { get; set; }
    public string? Description { get; set; }
    public int? Status { get; set; }
    public string? Type { get; set; }
    public string? DateCreated { get; set; }
    public string? DateUpdated { get; set; }
}
