// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesInsect record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesInsect
{
    public int? InsectID { get; set; }
    public int? OfficeID { get; set; }
    public string? Name { get; set; }
    public string? Family { get; set; }
    public string? Threat { get; set; }
    public string? Fact { get; set; }
    public string? About1 { get; set; }
    public string? About2 { get; set; }
    public string? AboutBlurb { get; set; }
    public string? FunFacts { get; set; }
    public string? FactBlurb { get; set; }
    public string? Image { get; set; }
    public int? Visible { get; set; }
    public int? System { get; set; }
}
