// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesSpot record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesSpot
{
    public int? SpotID { get; set; }
    public int? RouteID { get; set; }
    public string? Date { get; set; }
    public string? Start { get; set; }
    public string? End { get; set; }
    public int? SpotCapacity { get; set; }
    public string? Description { get; set; }
    public int? CurrentAppointment { get; set; }
    public int? CurrentAppointmentDuration { get; set; }
    public string? BlockReason { get; set; }
    public decimal? DistanceToPrevious { get; set; }
    public decimal? PreviousLat { get; set; }
    public decimal? PreviousLng { get; set; }
    public int? PrevCustomer { get; set; }
    public int? PrevSpotID { get; set; }
    public int? PrevAppointmentID { get; set; }
    public decimal? DistanceToNext { get; set; }
    public decimal? NextLat { get; set; }
    public decimal? NextLng { get; set; }
    public int? NextCustomer { get; set; }
    public int? NextSpotID { get; set; }
    public int? NextAppointmentID { get; set; }
    public int? ApiCanSchedule { get; set; }
    public int? AssignedTech { get; set; }
    public int? Reserved { get; set; }
    public string? ReservationEnd { get; set; }
}
