// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesNote record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesNote
{
    public int? NoteID { get; set; }
    public int? OfficeIDs { get; set; }
    public int? CustomerID { get; set; }
    public string? CustomerName { get; set; }
    public string? CustomerSpouse { get; set; }
    public string? CompanyName { get; set; }
    public int? EmployeeID { get; set; }
    public string? EmployeeName { get; set; }
    public string? Date { get; set; }
    public int? ShowCustomer { get; set; }
    public int? ShowTech { get; set; }
    public int? CancellationReasonID { get; set; }
    public string? CancellationReason { get; set; }
    public int? TypeID { get; set; }
    public int? Type { get; set; }
    public int? ContactTypeCategories { get; set; }
    public string? Notes { get; set; }
    public int? ReferenceID { get; set; }
    public string? DateAdded { get; set; }
    public string? DateUpdated { get; set; }
}
