// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesChangelog record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesChangelog
{
    public int? ChangeID { get; set; }
    public int? ClassID { get; set; }
    public string? Class { get; set; }
    public string? DateChanged { get; set; }
    public int? EmployeeID { get; set; }
    public object? Notes { get; set; }
    public int? ReferenceID { get; set; }
}
