// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesPayment record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesPayment
{
    public int? PaymentID { get; set; }
    public int? OfficeID { get; set; }
    public int? CustomerID { get; set; }
    public string? Date { get; set; }
    public int? PaymentMethod { get; set; }
    public decimal? Amount { get; set; }
    public decimal? AppliedAmount { get; set; }
    public decimal? UnassignedAmount { get; set; }
    public int? Status { get; set; }
    public int? InvoiceIDs { get; set; }
    public string? PaymentApplications { get; set; }
    public int? EmployeeID { get; set; }
    public int? OfficePayment { get; set; }
    public int? CollectionPayment { get; set; }
    public int? WriteOff { get; set; }
    public int? CreditMemo { get; set; }
    public int? PaymentOrigin { get; set; }
    public int? OriginalPaymentID { get; set; }
    public string? LastFour { get; set; }
    public string? Notes { get; set; }
    public string? BatchOpened { get; set; }
    public string? BatchClosed { get; set; }
    public string? PaymentSource { get; set; }
    public string? DateUpdated { get; set; }
    public int? TransactionID { get; set; }
}
