// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesContract record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesContract
{
    public int? ContractIDs { get; set; }
    public int? ContractID { get; set; }
    public int? CustomerIDs { get; set; }
    public int? SubscriptionIDs { get; set; }
    public string? DateSigned { get; set; }
    public string? DateAdded { get; set; }
    public int? DocumentState { get; set; }
    public string? Description { get; set; }
    public string? DateUpdated { get; set; }
}
