// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesAppointmentReminder record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesAppointmentReminder
{
    public int? ReminderID { get; set; }
    public int? OfficeID { get; set; }
    public int? AppointmentID { get; set; }
    public string? Text { get; set; }
    public string? DateSent { get; set; }
    public string? EmailSent { get; set; }
    public string? VoiceSent { get; set; }
    public int? Status { get; set; }
    public string? Response { get; set; }
    public string? ResponseTime { get; set; }
    public string? SendTo { get; set; }
    public string? EmailAddress { get; set; }
    public string? VoiceNumber { get; set; }
    public string? DateUpdated { get; set; }
}
