// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesTimeClockCategory record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesTimeClockCategory
{
    public int? ClockCategoryID { get; set; }
    public int? OfficeID { get; set; }
    public int? Visible { get; set; }
    public int? AllowOnClockIn { get; set; }
    public int? SystemReserved { get; set; }
    public int? Paid { get; set; }
    public string? DateUpdated { get; set; }
    public int? Description { get; set; }
}
