// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesServiceType record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesServiceType
{
    public int? TypeID { get; set; }
    public int? OfficeID { get; set; }
    public string? Description { get; set; }
    public int? Frequency { get; set; }
    public decimal? DefaultCharge { get; set; }
    public string? Category { get; set; }
    public int? Reservice { get; set; }
    public int? DefaultLength { get; set; }
    public decimal? DefaultInitialCharge { get; set; }
    public int? InitialID { get; set; }
    public decimal? MinimumRecurringCharge { get; set; }
    public decimal? MinimumInitialCharge { get; set; }
    public int? RegularService { get; set; }
    public int? Initial { get; set; }
    public string? SeasonStart { get; set; }
    public string? SeasonEnd { get; set; }
    public int? GlAccountID { get; set; }
    public int? Sentricon { get; set; }
    public int? Visible { get; set; }
}
