// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesPaymentProfile record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesPaymentProfile
{
    public int? PaymentProfileID { get; set; }
    public int? CustomerID { get; set; }
    public int? OfficeID { get; set; }
    public int? CreatedBy { get; set; }
    public string? Description { get; set; }
    public string? DateCreated { get; set; }
    public string? DateUpdated { get; set; }
    public int? Status { get; set; }
    public string? StatusNotes { get; set; }
    public string? BillingName { get; set; }
    public string? BillingAddress1 { get; set; }
    public string? BillingAddress2 { get; set; }
    public int? BillingCountryID { get; set; }
    public string? BillingCity { get; set; }
    public string? BillingState { get; set; }
    public string? BillingZip { get; set; }
    public string? BillingPhone { get; set; }
    public string? BillingEmail { get; set; }
    public int? PaymentMethod { get; set; }
    public string? Gateway { get; set; }
    public string? MerchantID { get; set; }
    public string? MerchantToken { get; set; }
    public string? LastFour { get; set; }
    public string? ExpMonth { get; set; }
    public string? ExpYear { get; set; }
    public string? CardType { get; set; }
    public string? BankName { get; set; }
    public string? AccountNumber { get; set; }
    public string? RoutingNumber { get; set; }
    public int? CheckType { get; set; }
    public int? AccountType { get; set; }
    public int? FailedAttempts { get; set; }
    public string? SentFailureDate { get; set; }
    public string? LastAttemptDate { get; set; }
    public string? PaymentHoldDate { get; set; }
    public int? RetryPoints { get; set; }
    public string? InitialTransactionID { get; set; }
    public string? LastDeclineType { get; set; }
}
