// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesUnit record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesUnit
{
    public int? UnitID { get; set; }
    public string? UnitName { get; set; }
    public string? Building { get; set; }
    public string? Description { get; set; }
    public int? CustomerID { get; set; }
}
