// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesChargeback record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesChargeback
{
    public int? GatewayChargebackID { get; set; }
    public int? OfficeID { get; set; }
    public string? DateCreated { get; set; }
    public string? DateUpdated { get; set; }
    public decimal? ChargebackAmount { get; set; }
    public string? ChargebackReasonCode { get; set; }
    public int? PaymentID { get; set; }
    public int? GatewayBillingName { get; set; }
}
