// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesKnock record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesKnock
{
    public int? KnockID { get; set; }
    public int? Type { get; set; }
    public int? DoorID { get; set; }
    public int? ServiceID { get; set; }
    public int? EmployeeID { get; set; }
    public string? DateAdded { get; set; }
    public string? DateUpdated { get; set; }
}
