// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesDoor record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesDoor
{
    public int? DoorID { get; set; }
    public decimal? Lat { get; set; }
    public decimal? Lng { get; set; }
    public string? TimeCreated { get; set; }
    public int? EmployeeID { get; set; }
    public string? Name { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
    public string? Phone { get; set; }
    public int? Status { get; set; }
    public string? Notes { get; set; }
    public string? Email { get; set; }
    public string? CallbackTime { get; set; }
    public int? KnockCounter { get; set; }
    public string? CountryID { get; set; }
}
