// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesForm record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesForm
{
    public int? FormID { get; set; }
    public int? CustomerID { get; set; }
    public string? DateSigned { get; set; }
    public string? DateAdded { get; set; }
    public int? UnitID { get; set; }
    public int? EmployeeID { get; set; }
    public int? DocumentState { get; set; }
    public int? FormTemplateID { get; set; }
    public string? FormDescription { get; set; }
}
