// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesLocation record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesLocation
{
    public int? LocationID { get; set; }
    public int? OfficeID { get; set; }
    public string? Name { get; set; }
    public int? Visible { get; set; }
    public int? System { get; set; }
}
