// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesDiagram record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesDiagram
{
    public int? Diagram { get; set; }
    public int? CustomerID { get; set; }
    public string? Description { get; set; }
    public string? DateCreated { get; set; }
    public string? DateUpdated { get; set; }
    public List<object>? DiagramObject { get; set; }
    public int? CreatedBy { get; set; }
    public string? DiagramType { get; set; }
    public int? Measurement { get; set; }
    public string? MeasurementUnit { get; set; }
}
