// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesAdditionalContact record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesAdditionalContact
{
    public int? AdditionalContactID { get; set; }
    public int? AdditionalContactTypeID { get; set; }
    public int? CustomerID { get; set; }
    public string? Fname { get; set; }
    public string? Lname { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
    public string? Phone { get; set; }
    public string? PhoneExt { get; set; }
    public string? Phone2 { get; set; }
    public string? Phone2Ext { get; set; }
    public string? Email { get; set; }
    public int? SmsReminders { get; set; }
    public int? PhoneReminders { get; set; }
    public int? EmailReminders { get; set; }
    public string? ContactType { get; set; }
    public string? DateUpdated { get; set; }
    public string? DateCreated { get; set; }
    public int? AddedBy { get; set; }
    public int? EditedBy { get; set; }
    public string? CompanyName { get; set; }
    public int? Visibility { get; set; }
    public int? BusinessContactID { get; set; }
    public int? TermiteReportID { get; set; }
    public int? WdoOrderedBy { get; set; }
    public int? WdoPartyOfInterest { get; set; }
    public int? WdoReportSentTo { get; set; }
    public int? WdoEmailOnly { get; set; }
    public int? Description { get; set; }
}
