// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesRoute record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesRoute
{
    public int? RouteID { get; set; }
    public int? Title { get; set; }
    public int? TemplateID { get; set; }
    public string? DateAdded { get; set; }
    public int? AddedBy { get; set; }
    public int? OfficeID { get; set; }
    public int? GroupID { get; set; }
    public int? GroupTitle { get; set; }
    public string? Date { get; set; }
    public int? DayNotes { get; set; }
    public int? DayAlert { get; set; }
    public int? DayID { get; set; }
    public string? AdditionalTechs { get; set; }
    public int? AssignedTech { get; set; }
    public int? ApiCanSchedule { get; set; }
    public string? ScheduleTeams { get; set; }
    public string? ScheduleTypes { get; set; }
    public decimal? AverageLatitude { get; set; }
    public decimal? AverageLongitude { get; set; }
    public decimal? AverageDistance { get; set; }
    public string? DateUpdated { get; set; }
    public int? DistanceScore { get; set; }
}
