// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesRegion record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesRegion
{
    public int? RegionIDs { get; set; }
    public int? OfficeIDs { get; set; }
    public string? Description { get; set; }
    public string? Created { get; set; }
    public string? Deleted { get; set; }
    public string? Points { get; set; }
    public string? Type { get; set; }
    public string? Active { get; set; }
}
