// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesEmployee record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesEmployee
{
    public int? EmployeeID { get; set; }
    public int? OfficeID { get; set; }
    public int? Active { get; set; }
    public string? Fname { get; set; }
    public string? Lname { get; set; }
    public string? Initials { get; set; }
    public string? Nickname { get; set; }
    public int? Type { get; set; }
    public string? Phone { get; set; }
    public int? Email { get; set; }
    public string? Username { get; set; }
    public int? Experience { get; set; }
    public int? SkillIDs { get; set; }
    public int? SkillDescriptions { get; set; }
    public string? Pic { get; set; }
    public int? LinkedEmployeeIDs { get; set; }
    public string? EmployeeLink { get; set; }
    public string? LicenseNumber { get; set; }
    public int? SupervisorID { get; set; }
    public int? RoamingRep { get; set; }
    public int? RegionalManagerOfficeIDs { get; set; }
    public string? LastLogin { get; set; }
    public int? TeamIDs { get; set; }
    public int? PrimaryTeam { get; set; }
    public int? AccessControlProfileID { get; set; }
    public string? StartAddress { get; set; }
    public string? StartCity { get; set; }
    public string? StartState { get; set; }
    public string? StartZip { get; set; }
    public decimal? StartLat { get; set; }
    public decimal? StartLng { get; set; }
    public string? EndAddress { get; set; }
    public string? EndCity { get; set; }
    public string? EndState { get; set; }
    public string? EndZip { get; set; }
    public decimal? EndLat { get; set; }
    public decimal? EndLng { get; set; }
    public string? DateUpdated { get; set; }
}
