// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesOffice record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesOffice
{
    public int? OfficeID { get; set; }
    public string? OfficeName { get; set; }
    public int? CompanyID { get; set; }
    public int? LicenseNumber { get; set; }
    public string? ContactNumber { get; set; }
    public string? ContactEmail { get; set; }
    public string? Website { get; set; }
    public string? TimeZone { get; set; }
    public string? Address { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? Zip { get; set; }
    public string? InvoiceAddress { get; set; }
    public string? InvoiceCity { get; set; }
    public string? InvoiceState { get; set; }
    public string? InvoiceZip { get; set; }
    public string? CautionStatements { get; set; }
}
