// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesReview record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesReview
{
    public int? FeedbackID { get; set; }
    public int? OfficeIDs { get; set; }
    public int? CustomerID { get; set; }
    public int? AppointmentID { get; set; }
    public string? Date { get; set; }
    public int? StarRating { get; set; }
    public string? Feedback { get; set; }
    public int? Favorable { get; set; }
    public object? Customer { get; set; }
}
