// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesRouteTemplate record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesRouteTemplate
{
    public int? TemplateID { get; set; }
    public int? OfficeID { get; set; }
    public string? TemplateName { get; set; }
    public string? OfficeDefault { get; set; }
    public string? Visible { get; set; }
}
