// Originally generated from api.md by tools/generate.py (now DEPRECATED).
// This file is MANUALLY MAINTAINED — never regenerate. See AGENTS.md.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesTicket record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesTicket
{
    public int? TicketID { get; set; }
    public int? CustomerID { get; set; }
    public int? BillToAccountID { get; set; }
    public int? OfficeID { get; set; }
    public string? DateCreated { get; set; }
    public string? InvoiceDate { get; set; }
    public string? DateUpdated { get; set; }
    public int? Active { get; set; }
    public decimal? SubTotal { get; set; }
    public decimal? TaxAmount { get; set; }
    public decimal? Total { get; set; }
    public decimal? ServiceCharge { get; set; }
    public int? ServiceTaxable { get; set; }
    public decimal? ProductionValue { get; set; }
    public decimal? TaxRate { get; set; }
    public int? AppointmentID { get; set; }
    public decimal? Balance { get; set; }
    public int? SubscriptionID { get; set; }
    public int? AutoGenerated { get; set; }
    public string? AutoGeneratedType { get; set; }
    public int? RenewalID { get; set; }
    public int? ServiceID { get; set; }
    // MANUAL FIX (2026-08-05): api.md types items as string but describes "An array of line
    // items associated with this ticket" — real wire is a JSON array of objects — fixed to
    // List<object>?. See api.md line 6454/6550.
    public List<object>? Items { get; set; }
    public string? InvoiceNumber { get; set; }
    public string? TemplateType { get; set; }
    public string? GlNumber { get; set; }
    public string? CreatedBy { get; set; }
}
