// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesCustomerSource record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesCustomerSource
{
    public int? SourceID { get; set; }
    public int? OfficeID { get; set; }
    public string? Source { get; set; }
    public int? SalesRoutesDefault { get; set; }
    public string? Visible { get; set; }
    public int? DealsSource { get; set; }
}
