// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesApplicationMethod record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesApplicationMethod
{
    public int? ApplicationMethodID { get; set; }
    public int? OfficeID { get; set; }
    public string? ApplicationMethod { get; set; }
    public int? Visible { get; set; }
    public int? SystemReserved { get; set; }
}
