// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesChemical record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesChemical
{
    public int? ChemicalID { get; set; }
    public string? Name { get; set; }
    public string? Manufacturer { get; set; }
    public string? Label { get; set; }
    public string? Ingredient1 { get; set; }
    public string? Ingredient2 { get; set; }
    public string? Ingredient3 { get; set; }
    public decimal? Percent1 { get; set; }
    public decimal? Percent2 { get; set; }
    public decimal? Percent3 { get; set; }
    public string? EpaNumber { get; set; }
    public string? Image { get; set; }
    public string? Description { get; set; }
    public decimal? DefaultDilution { get; set; }
    public string? ConcentratedUnit { get; set; }
    public string? DilutedUnit { get; set; }
    public string? InventoryUnit { get; set; }
    public string? ApplicationRate { get; set; }
    public string? Links { get; set; }
    public string? MsdsLink { get; set; }
    public int? MeasurementType { get; set; }
    public int? Visible { get; set; }
    public int? DefaultApplicationMethod { get; set; }
    public int? OfficeID { get; set; }
    public int? IsBait { get; set; }
    public int? SentriconBaitTypeID { get; set; }
    public string? LabelLink { get; set; }
    public decimal? MixRatioNumerator { get; set; }
    public string? MixRatioNumeratorUnit { get; set; }
    public decimal? MixRatioDenominator { get; set; }
    public string? MixRatioDenominatorUnit { get; set; }
    public decimal? ActiveIngredientRate { get; set; }
    public int? Type { get; set; }
    public int? TargetIssues { get; set; }
    public int? AvailableToTermite { get; set; }
    public int? PestControlCode { get; set; }
}
