// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesChemicalUse record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesChemicalUse
{
    public int? ChemicalUseID { get; set; }
    public int? ChemicalID { get; set; }
    public int? OfficeID { get; set; }
    public int? AppointmentID { get; set; }
    public int? CustomerID { get; set; }
    public string? DateCreated { get; set; }
    public string? CreatedBy { get; set; }
    public int? ServiceID { get; set; }
    public decimal? Dilution { get; set; }
    public decimal? Dosage { get; set; }
    public decimal? Amount { get; set; }
    public decimal? ConcentratedAmount { get; set; }
    public string? ConcentratedUnit { get; set; }
    public string? Unit { get; set; }
    public string? TargetInsects { get; set; }
    public string? LocationsTreated { get; set; }
    public int? ApplicationMethod { get; set; }
    public int? SquareFoot { get; set; }
    public int? StructureID { get; set; }
    public decimal? MixRatioNumerator { get; set; }
    public string? MixRatioNumeratorUnit { get; set; }
    public decimal? MixRatioDenominator { get; set; }
    public string? MixRatioDenominatorUnit { get; set; }
    public decimal? ActiveIngredientRate { get; set; }
    public string? EpaLot { get; set; }
    public int? PestControlCode { get; set; }
    public string? DateUpdated { get; set; }
}
