// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesDocument record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesDocument
{
    public int? UploadID { get; set; }
    public int? OfficeID { get; set; }
    public int? CustomerID { get; set; }
    public string? DateAdded { get; set; }
    public int? AddedBy { get; set; }
    public string? Description { get; set; }
    public int? ShowCustomer { get; set; }
    public int? ShowTech { get; set; }
    public int? AppointmentID { get; set; }
    public int? Prefix { get; set; }
    public string? DateUpdated { get; set; }
}
