// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesTicket record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesTicket
{
    public int? TicketID { get; set; }
    public int? CustomerID { get; set; }
    public int? BillToAccountID { get; set; }
    public int? OfficeID { get; set; }
    public string? DateCreated { get; set; }
    public string? InvoiceDate { get; set; }
    public string? DateUpdated { get; set; }
    public int? Active { get; set; }
    public decimal? SubTotal { get; set; }
    public decimal? TaxAmount { get; set; }
    public decimal? Total { get; set; }
    public decimal? ServiceCharge { get; set; }
    public int? ServiceTaxable { get; set; }
    public decimal? ProductionValue { get; set; }
    public decimal? TaxRate { get; set; }
    public int? AppointmentID { get; set; }
    public decimal? Balance { get; set; }
    public int? SubscriptionID { get; set; }
    public int? AutoGenerated { get; set; }
    public string? AutoGeneratedType { get; set; }
    public int? RenewalID { get; set; }
    public int? ServiceID { get; set; }
    public string? Items { get; set; }
    public string? InvoiceNumber { get; set; }
    public string? TemplateType { get; set; }
    public string? GlNumber { get; set; }
    public string? CreatedBy { get; set; }
}
