// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesCustomerFlag record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesCustomerFlag
{
    public int? CustomerID { get; set; }
    public string? Flag { get; set; }
    public string? FlagValue { get; set; }
}
