// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
/// <summary>FieldRoutesEmployeeLocation record as returned by the FieldRoutes API.</summary>
public sealed class FieldRoutesEmployeeLocation
{
    public int? LocationID { get; set; }
    public int? EmployeeID { get; set; }
    public int? OfficeID { get; set; }
    public int? Time { get; set; }
    public decimal? Latitude { get; set; }
    public decimal? Longitude { get; set; }
}
