// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppointmentReminderCreateRequest
{
    /// <summary>appointmentID the reminder pertains to</summary>
    public int? AppointmentID { get; set; }
    /// <summary>Text of the reminder</summary>
    public string? Text { get; set; }
    /// <summary>Time the reminder was sent</summary>
    public string? DateSent { get; set; }
    /// <summary>Time email was sent</summary>
    public string? EmailSent { get; set; }
    /// <summary>Time voice message was sent</summary>
    public string? VoiceSent { get; set; }
    /// <summary>-1 = don't send reminder, 0 = not sent(not allowed), 1 = sent, 6 = confirmed by office, 9 = confirmed via SMS</summary>
    public int? Status { get; set; }
    /// <summary>Response text received</summary>
    public string? Response { get; set; }
    /// <summary>Time response was received</summary>
    public string? ResponseTime { get; set; }
    /// <summary>Phone number for SMS</summary>
    public string? SendTo { get; set; }
    /// <summary>Email address the reminder was sent to</summary>
    public string? EmailAddress { get; set; }
    /// <summary>Phone number for voice</summary>
    public string? VoiceNumber { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (AppointmentID is null) throw new ArgumentException("Required parameter AppointmentID is null.", nameof(AppointmentID));
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (Text is null) throw new ArgumentException("Required parameter Text is null.", nameof(Text));
        if (Text is not null) d["text"] = Text;
        if (DateSent is null) throw new ArgumentException("Required parameter DateSent is null.", nameof(DateSent));
        if (DateSent is not null) d["dateSent"] = DateSent;
        if (EmailSent is null) throw new ArgumentException("Required parameter EmailSent is null.", nameof(EmailSent));
        if (EmailSent is not null) d["emailSent"] = EmailSent;
        if (VoiceSent is not null) d["voiceSent"] = VoiceSent;
        if (Status is null) throw new ArgumentException("Required parameter Status is null.", nameof(Status));
        if (Status is not null) d["status"] = Status;
        if (Response is not null) d["response"] = Response;
        if (ResponseTime is not null) d["responseTime"] = ResponseTime;
        if (SendTo is not null) d["sendTo"] = SendTo;
        if (EmailAddress is not null) d["emailAddress"] = EmailAddress;
        if (VoiceNumber is not null) d["voiceNumber"] = VoiceNumber;
        return d;
    }
}
