// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSubscriptionDeleteInitialAddOnRequest
{
    /// <summary>Foreign key to subscriptions table.</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>Foreign key to initialAddons table.</summary>
    public int? AddOnID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (SubscriptionID is null) throw new ArgumentException("Required parameter SubscriptionID is null.", nameof(SubscriptionID));
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (AddOnID is null) throw new ArgumentException("Required parameter AddOnID is null.", nameof(AddOnID));
        if (AddOnID is not null) d["addOnID"] = AddOnID;
        return d;
    }
}
