// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesReviewCreateRequest
{
    /// <summary>Foreign key to appointments table</summary>
    public int? AppointmentID { get; set; }
    /// <summary>Foreign key to customers table</summary>
    public int? CustomerID { get; set; }
    /// <summary>Integer 1-5 as star rating.</summary>
    public int? StarRating { get; set; }
    /// <summary>Customer Feedback String</summary>
    public string? Feedback { get; set; }
    /// <summary>Time the feedback was given</summary>
    public string? Time { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (AppointmentID is null) throw new ArgumentException("Required parameter AppointmentID is null.", nameof(AppointmentID));
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (StarRating is null) throw new ArgumentException("Required parameter StarRating is null.", nameof(StarRating));
        if (StarRating is not null) d["starRating"] = StarRating;
        if (Feedback is null) throw new ArgumentException("Required parameter Feedback is null.", nameof(Feedback));
        if (Feedback is not null) d["feedback"] = Feedback;
        if (Time is null) throw new ArgumentException("Required parameter Time is null.", nameof(Time));
        if (Time is not null) d["time"] = Time;
        return d;
    }
}
