// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesRouteUpdateRequest
{
    /// <summary>DayID to create for</summary>
    public string? Date { get; set; }
    /// <summary>employeeID</summary>
    public int? AssignedTech { get; set; }
    /// <summary>set as 1 if the group should be auto-created with the template title, set as 0 to reject on missing group. Default 1</summary>
    public int? AutoCreateGroup { get; set; }
    /// <summary>groupID for manually assigning to a group</summary>
    public int? GroupID { get; set; }
    /// <summary>Primary key to the route table.</summary>
    public int? RouteID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (Date is not null) d["date"] = Date;
        if (AssignedTech is not null) d["assignedTech"] = AssignedTech;
        if (AutoCreateGroup is not null) d["autoCreateGroup"] = AutoCreateGroup;
        if (GroupID is not null) d["groupID"] = GroupID;
        if (RouteID is null) throw new ArgumentException("Required parameter RouteID is null.", nameof(RouteID));
        if (RouteID is not null) d["routeID"] = RouteID;
        return d;
    }
}
