// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSpotGetBulkParameters
{
    /// <summary>Latitude for distance calculcations. If not specified, the office longitude will be used</summary>
    public decimal? Latitude { get; set; }
    /// <summary>Longitude for distance calculcations. If not specified, the office longitude will be used</summary>
    public decimal? Longitude { get; set; }
    /// <summary>Maximum number of miles from the previous spot to return.</summary>
    public int? MaxDistance { get; set; }
    /// <summary>If sent as 1 the start and end of the route will be ignored for distanceToClosest and maxDistance once the route has an appointment on it. This strategy can be beneficial technicians are driving a long distance to their first appointment, then servicing locally from there.</summary>
    public int? IgnoreInitialDriveTime { get; set; }
    /// <summary>Set as 1 to return only open routes from the GET</summary>
    public int? Open { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (Latitude is not null) d["latitude"] = Latitude;
        if (Longitude is not null) d["longitude"] = Longitude;
        if (MaxDistance is not null) d["maxDistance"] = MaxDistance;
        if (IgnoreInitialDriveTime is not null) d["ignoreInitialDriveTime"] = IgnoreInitialDriveTime;
        if (Open is not null) d["open"] = Open;
        return d;
    }
}
