// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesReviewGetBulkParameters : FieldRoutesQueryBase
{
    /// <summary>Set true to include the Customer object in review results..</summary>
    public int? IncludeCustomers { get; set; }
    /// <summary>Set true to return review text that has been pruned of credit card, phone, and email information.</summary>
    public int? PruneSensitiveInfo { get; set; }
    /// <summary>Set true to return review text that has been pruned of common profanity.</summary>
    public int? PruneProfanity { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (IncludeCustomers is not null) d["includeCustomers"] = IncludeCustomers;
        if (PruneSensitiveInfo is not null) d["pruneSensitiveInfo"] = PruneSensitiveInfo;
        if (PruneProfanity is not null) d["pruneProfanity"] = PruneProfanity;
        return d;
    }
}
