// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesGroupUpdateRequest
{
    /// <summary>Title string (30 character limit)</summary>
    public string? Title { get; set; }
    /// <summary>Primary key to the group table.</summary>
    public int? GroupID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (Title is not null) d["title"] = Title;
        if (GroupID is null) throw new ArgumentException("Required parameter GroupID is null.", nameof(GroupID));
        if (GroupID is not null) d["groupID"] = GroupID;
        return d;
    }
}
