// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesReviewUpdateRequest
{
    /// <summary>Foreign key to appointments table</summary>
    public int? AppointmentID { get; set; }
    /// <summary>Foreign key to customers table</summary>
    public int? CustomerID { get; set; }
    /// <summary>Integer 1-5 as star rating.</summary>
    public int? StarRating { get; set; }
    /// <summary>Customer Feedback String</summary>
    public string? Feedback { get; set; }
    /// <summary>Time the feedback was given</summary>
    public string? Time { get; set; }
    /// <summary>Primary key to the customerFeedback table.</summary>
    public int? FeedbackID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (StarRating is not null) d["starRating"] = StarRating;
        if (Feedback is not null) d["feedback"] = Feedback;
        if (Time is not null) d["time"] = Time;
        if (FeedbackID is null) throw new ArgumentException("Required parameter FeedbackID is null.", nameof(FeedbackID));
        if (FeedbackID is not null) d["feedbackID"] = FeedbackID;
        return d;
    }
}
