// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerUpdateRequest
{
    public int? BillToAccountID { get; set; }
    /// <summary>First name</summary>
    public string? Fname { get; set; }
    /// <summary>Last name</summary>
    public string? Lname { get; set; }
    public string? Spouse { get; set; }
    /// <summary>Address string</summary>
    public string? Address { get; set; }
    /// <summary>City string</summary>
    public string? City { get; set; }
    /// <summary>2 letter state code</summary>
    public string? State { get; set; }
    /// <summary>Zip code</summary>
    public string? Zip { get; set; }
    /// <summary>Map Code</summary>
    public string? MapCode { get; set; }
    public int? SquareFeet { get; set; }
    public string? Phone1 { get; set; }
    public string? Phone2 { get; set; }
    public string? Ext1 { get; set; }
    public string? Ext2 { get; set; }
    /// <summary>0 - no APay, 1 - credit card apay, 2 ACH apay</summary>
    public int? APay { get; set; }
    public decimal? MaxMonthlyCharge { get; set; }
    public int? PaidInFull { get; set; }
    public int? PreferredPayment { get; set; }
    public int? Status { get; set; }
    public decimal? Lat { get; set; }
    public decimal? Lng { get; set; }
    public int? EmployeeID { get; set; }
    public string? Notes { get; set; }
    public int? TermiteMonitoring { get; set; }
    /// <summary>External ID, usually the primary key for your application</summary>
    public string? CustomerLink { get; set; }
    public decimal? TaxRate { get; set; }
    public decimal? StateTax { get; set; }
    public decimal? CityTax { get; set; }
    public decimal? CountyTax { get; set; }
    public decimal? DistrictTax { get; set; }
    public decimal? CustomTax { get; set; }
    public string? CustomCode { get; set; }
    public string? CityCode { get; set; }
    public string? CountyCode { get; set; }
    public string? DistrictCode { get; set; }
    public string? ZipCityCounty { get; set; }
    public int? SmsReminders { get; set; }
    public int? PhoneReminders { get; set; }
    public int? EmailReminders { get; set; }
    public int? PreferredTech { get; set; }
    public string? PreferredBillingDate { get; set; }
    public int? CountyID { get; set; }
    public string? County { get; set; }
    /// <summary>2-letter Country code e.g. US</summary>
    public string? CountryID { get; set; }
    public string? DateCancelled { get; set; }
    public string? SpecialScheduling { get; set; }
    public int? RegionID { get; set; }
    public int? SalesmanAPay { get; set; }
    /// <summary>0 if not part a master account or assigned to one; otherwise ID of the master account for this customer group</summary>
    public int? MasterAccount { get; set; }
    public int? BillTo { get; set; }
    public int? CommercialAccount { get; set; }
    public string? CompanyName { get; set; }
    /// <summary>email</summary>
    public string? Email { get; set; }
    /// <summary>sourceID for the customer (from Admin &gt; Preferences &gt; Customer References &gt; Customer Sources</summary>
    public int? SourceID { get; set; }
    public int? DivisionID { get; set; }
    public int? SubPropertyTypeID { get; set; }
    /// <summary>Billing First Name</summary>
    public string? BillingFName { get; set; }
    /// <summary>Billing Last Name</summary>
    public string? BillingLName { get; set; }
    /// <summary>Billing CountryID</summary>
    public string? BillingCountryID { get; set; }
    /// <summary>Billing Address</summary>
    public string? BillingAddress { get; set; }
    /// <summary>Billing City</summary>
    public string? BillingCity { get; set; }
    /// <summary>Billing State</summary>
    public string? BillingState { get; set; }
    /// <summary>Billing Zip</summary>
    public string? BillingZip { get; set; }
    /// <summary>Billing Phone</summary>
    public string? BillingPhone { get; set; }
    /// <summary>Billing Email</summary>
    public string? BillingEmail { get; set; }
    /// <summary>Billing billingCompanyName</summary>
    public string? BillingCompanyName { get; set; }
    /// <summary>Billing billingPhoneExt</summary>
    public string? BillingPhoneExt { get; set; }
    /// <summary>Billing billingPhone2</summary>
    public string? BillingPhone2 { get; set; }
    /// <summary>Billing billingPhone2Ext</summary>
    public string? BillingPhone2Ext { get; set; }
    /// <summary>Billing billingBusinessContactID</summary>
    public string? BillingBusinessContactID { get; set; }
    /// <summary>Sets the Purple Dragon customer flag checkbox</summary>
    public int? PurpleDragon { get; set; }
    /// <summary>Primary key to the customers table.</summary>
    public int? CustomerID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (BillToAccountID is not null) d["billToAccountID"] = BillToAccountID;
        if (Fname is not null) d["fname"] = Fname;
        if (Lname is not null) d["lname"] = Lname;
        if (Spouse is not null) d["spouse"] = Spouse;
        if (Address is not null) d["address"] = Address;
        if (City is not null) d["city"] = City;
        if (State is not null) d["state"] = State;
        if (Zip is not null) d["zip"] = Zip;
        if (MapCode is not null) d["mapCode"] = MapCode;
        if (SquareFeet is not null) d["squareFeet"] = SquareFeet;
        if (Phone1 is not null) d["phone1"] = Phone1;
        if (Phone2 is not null) d["phone2"] = Phone2;
        if (Ext1 is not null) d["ext1"] = Ext1;
        if (Ext2 is not null) d["ext2"] = Ext2;
        if (APay is not null) d["aPay"] = APay;
        if (MaxMonthlyCharge is not null) d["maxMonthlyCharge"] = MaxMonthlyCharge;
        if (PaidInFull is not null) d["paidInFull"] = PaidInFull;
        if (PreferredPayment is not null) d["preferredPayment"] = PreferredPayment;
        if (Status is not null) d["status"] = Status;
        if (Lat is not null) d["lat"] = Lat;
        if (Lng is not null) d["lng"] = Lng;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (Notes is not null) d["notes"] = Notes;
        if (TermiteMonitoring is not null) d["termiteMonitoring"] = TermiteMonitoring;
        if (CustomerLink is not null) d["customerLink"] = CustomerLink;
        if (TaxRate is not null) d["taxRate"] = TaxRate;
        if (StateTax is not null) d["stateTax"] = StateTax;
        if (CityTax is not null) d["cityTax"] = CityTax;
        if (CountyTax is not null) d["countyTax"] = CountyTax;
        if (DistrictTax is not null) d["districtTax"] = DistrictTax;
        if (CustomTax is not null) d["customTax"] = CustomTax;
        if (CustomCode is not null) d["customCode"] = CustomCode;
        if (CityCode is not null) d["cityCode"] = CityCode;
        if (CountyCode is not null) d["countyCode"] = CountyCode;
        if (DistrictCode is not null) d["districtCode"] = DistrictCode;
        if (ZipCityCounty is not null) d["zipCityCounty"] = ZipCityCounty;
        if (SmsReminders is not null) d["smsReminders"] = SmsReminders;
        if (PhoneReminders is not null) d["phoneReminders"] = PhoneReminders;
        if (EmailReminders is not null) d["emailReminders"] = EmailReminders;
        if (PreferredTech is not null) d["preferredTech"] = PreferredTech;
        if (PreferredBillingDate is not null) d["preferredBillingDate"] = PreferredBillingDate;
        if (CountyID is not null) d["countyID"] = CountyID;
        if (County is not null) d["county"] = County;
        if (CountryID is not null) d["countryID"] = CountryID;
        if (DateCancelled is not null) d["dateCancelled"] = DateCancelled;
        if (SpecialScheduling is not null) d["specialScheduling"] = SpecialScheduling;
        if (RegionID is not null) d["regionID"] = RegionID;
        if (SalesmanAPay is not null) d["salesmanAPay"] = SalesmanAPay;
        if (MasterAccount is not null) d["masterAccount"] = MasterAccount;
        if (BillTo is not null) d["billTo"] = BillTo;
        if (CommercialAccount is not null) d["commercialAccount"] = CommercialAccount;
        if (CompanyName is not null) d["companyName"] = CompanyName;
        if (Email is not null) d["email"] = Email;
        if (SourceID is not null) d["sourceID"] = SourceID;
        if (DivisionID is not null) d["divisionID"] = DivisionID;
        if (SubPropertyTypeID is not null) d["subPropertyTypeID"] = SubPropertyTypeID;
        if (BillingFName is not null) d["billingFName"] = BillingFName;
        if (BillingLName is not null) d["billingLName"] = BillingLName;
        if (BillingCountryID is not null) d["billingCountryID"] = BillingCountryID;
        if (BillingAddress is not null) d["billingAddress"] = BillingAddress;
        if (BillingCity is not null) d["billingCity"] = BillingCity;
        if (BillingState is not null) d["billingState"] = BillingState;
        if (BillingZip is not null) d["billingZip"] = BillingZip;
        if (BillingPhone is not null) d["billingPhone"] = BillingPhone;
        if (BillingEmail is not null) d["billingEmail"] = BillingEmail;
        if (BillingCompanyName is not null) d["billingCompanyName"] = BillingCompanyName;
        if (BillingPhoneExt is not null) d["billingPhoneExt"] = BillingPhoneExt;
        if (BillingPhone2 is not null) d["billingPhone2"] = BillingPhone2;
        if (BillingPhone2Ext is not null) d["billingPhone2Ext"] = BillingPhone2Ext;
        if (BillingBusinessContactID is not null) d["billingBusinessContactID"] = BillingBusinessContactID;
        if (PurpleDragon is not null) d["purpleDragon"] = PurpleDragon;
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        return d;
    }
}
