// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTicketDeleteAddOnRequest
{
    /// <summary>Foreign key to subscriptions table.</summary>
    public int? TicketID { get; set; }
    /// <summary>Foreign key to ticketItems table. Retrieve via getAddons(subscriptionID).</summary>
    public int? ItemID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (TicketID is null) throw new ArgumentException("Required parameter TicketID is null.", nameof(TicketID));
        if (TicketID is not null) d["ticketID"] = TicketID;
        if (ItemID is null) throw new ArgumentException("Required parameter ItemID is null.", nameof(ItemID));
        if (ItemID is not null) d["itemID"] = ItemID;
        return d;
    }
}
