// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTaskCreateRequest
{
    /// <summary>0: task, 1: alert</summary>
    public int? Type { get; set; }
    /// <summary>CustomerID the task pertains to</summary>
    public int? CustomerID { get; set; }
    /// <summary>SubscriptionID the task pertains to</summary>
    public int? ReferenceID { get; set; }
    /// <summary>Phone number for the task</summary>
    public string? Phone { get; set; }
    /// <summary>categoryID of the task values: Appt Status (15), Billing (1), Customer Care (10), Customer Status (13), Feedback (7), Follow Up (5), Office (6), Reminder Reply (9), Sales (11), Scheduling (2), Service (4), SMS Reply (12), Subscription Status (14), Tech Flag (8), Voice Mail (3)</summary>
    public int? Category { get; set; }
    /// <summary>EmployeeID who added the task or alert</summary>
    public int? AddedBy { get; set; }
    /// <summary>EmployeeID the task is assigned to</summary>
    public int? AssignedTo { get; set; }
    /// <summary>Date the task is due</summary>
    public string? DueDate { get; set; }
    /// <summary>Text description of the task</summary>
    public string? Task { get; set; }
    /// <summary>0: Pending, 1: Completed, 2: In Use, 3: Urgent, -1: Deleted</summary>
    public int? Status { get; set; }
    public string? DateCompleted { get; set; }
    public int? CompletedBy { get; set; }
    public int? CompletionNotes { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (Type is null) throw new ArgumentException("Required parameter Type is null.", nameof(Type));
        if (Type is not null) d["type"] = Type;
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (ReferenceID is not null) d["referenceID"] = ReferenceID;
        if (Phone is not null) d["phone"] = Phone;
        if (Category is not null) d["category"] = Category;
        if (AddedBy is not null) d["addedBy"] = AddedBy;
        if (AssignedTo is not null) d["assignedTo"] = AssignedTo;
        if (DueDate is not null) d["dueDate"] = DueDate;
        if (Task is not null) d["task"] = Task;
        if (Status is not null) d["status"] = Status;
        if (DateCompleted is not null) d["dateCompleted"] = DateCompleted;
        if (CompletedBy is not null) d["completedBy"] = CompletedBy;
        if (CompletionNotes is not null) d["completionNotes"] = CompletionNotes;
        return d;
    }
}
