// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppointmentCancelRequest
{
    /// <summary>appointmentID to cancel</summary>
    public int? AppointmentID { get; set; }
    /// <summary>Cancel Reason</summary>
    public string? CancelReason { get; set; }
    /// <summary>employeeID that cancelled the appointment</summary>
    public int? CancelledBy { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (AppointmentID is null) throw new ArgumentException("Required parameter AppointmentID is null.", nameof(AppointmentID));
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (CancelReason is not null) d["cancelReason"] = CancelReason;
        if (CancelledBy is not null) d["cancelledBy"] = CancelledBy;
        return d;
    }
}
