// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerFlagUpdateRequest
{
    /// <summary>ID of customer the flags are to be set to</summary>
    public int? CustomerID { get; set; }
    /// <summary>Pass 1 to set Paid In Full flag, 0 to unset</summary>
    public int? PaidInFull { get; set; }
    /// <summary>Pass 1 to set Switch Over flag, 0 to unset</summary>
    public int? TermiteMonitoring { get; set; }
    /// <summary>Pass 1 to set Purple Dragon flag, 0 to unset</summary>
    public int? PurpleDragon { get; set; }
    /// <summary>Pass 1 to set Sales Rep APay flag, 0 to unset</summary>
    public int? SalesmanAPay { get; set; }
    /// <summary>Pass 1 to set Prefers Paper flag, 0 to unset</summary>
    public int? PrefersPaper { get; set; }
    /// <summary>Pass 1 to set Pending Cancel flag, 0 to unset</summary>
    public int? PendingCancel { get; set; }
    /// <summary>Cancellation Reason ID, required if setting the Pending Cancel flag</summary>
    public int? PendingCancelReasonID { get; set; }
    /// <summary>Pending Cancel Notes</summary>
    public string? PendingCancelNotes { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (PaidInFull is not null) d["paidInFull"] = PaidInFull;
        if (TermiteMonitoring is not null) d["termiteMonitoring"] = TermiteMonitoring;
        if (PurpleDragon is not null) d["purpleDragon"] = PurpleDragon;
        if (SalesmanAPay is not null) d["salesmanAPay"] = SalesmanAPay;
        if (PrefersPaper is not null) d["prefersPaper"] = PrefersPaper;
        if (PendingCancel is not null) d["pendingCancel"] = PendingCancel;
        if (PendingCancelReasonID is not null) d["pendingCancelReasonID"] = PendingCancelReasonID;
        if (PendingCancelNotes is not null) d["pendingCancelNotes"] = PendingCancelNotes;
        return d;
    }
}
