// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesContractGetBulkParameters : FieldRoutesQueryBase
{
    /// <summary>Send as 1 to retrieve a link to the document on AWS with a 15 day TTL.</summary>
    public int? IncludeDocumentLink { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (IncludeDocumentLink is not null) d["includeDocumentLink"] = IncludeDocumentLink;
        return d;
    }
}
