// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAdditionalContactCreateRequest
{
    public int? CustomerID { get; set; }
    public int? AdditionalContactTypeID { get; set; }
    /// <summary>First name</summary>
    public string? Fname { get; set; }
    /// <summary>Last name</summary>
    public string? Lname { get; set; }
    /// <summary>Address string</summary>
    public string? Address { get; set; }
    /// <summary>City string</summary>
    public string? City { get; set; }
    /// <summary>2 letter state code</summary>
    public string? State { get; set; }
    /// <summary>Zip code</summary>
    public string? Zip { get; set; }
    public string? Phone { get; set; }
    public string? Phone2 { get; set; }
    public string? PhoneExt { get; set; }
    public string? Phone2Ext { get; set; }
    public int? SmsReminders { get; set; }
    public int? PhoneReminders { get; set; }
    public int? EmailReminders { get; set; }
    public string? CompanyName { get; set; }
    /// <summary>email</summary>
    public string? Email { get; set; }
    /// <summary>contact type: SERVICE, BILLING, SERVICE_BILLING</summary>
    public string? ContactType { get; set; }
    /// <summary>business contact ID</summary>
    public string? BusinessContactID { get; set; }
    /// <summary>User that added this contact</summary>
    public string? AddedBy { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (AdditionalContactTypeID is null) throw new ArgumentException("Required parameter AdditionalContactTypeID is null.", nameof(AdditionalContactTypeID));
        if (AdditionalContactTypeID is not null) d["additionalContactTypeID"] = AdditionalContactTypeID;
        if (Fname is not null) d["fname"] = Fname;
        if (Lname is not null) d["lname"] = Lname;
        if (Address is not null) d["address"] = Address;
        if (City is not null) d["city"] = City;
        if (State is not null) d["state"] = State;
        if (Zip is not null) d["zip"] = Zip;
        if (Phone is not null) d["phone"] = Phone;
        if (Phone2 is not null) d["phone2"] = Phone2;
        if (PhoneExt is not null) d["phoneExt"] = PhoneExt;
        if (Phone2Ext is not null) d["phone2Ext"] = Phone2Ext;
        if (SmsReminders is not null) d["smsReminders"] = SmsReminders;
        if (PhoneReminders is not null) d["phoneReminders"] = PhoneReminders;
        if (EmailReminders is not null) d["emailReminders"] = EmailReminders;
        if (CompanyName is not null) d["companyName"] = CompanyName;
        if (Email is not null) d["email"] = Email;
        if (ContactType is not null) d["contactType"] = ContactType;
        if (BusinessContactID is not null) d["businessContactID"] = BusinessContactID;
        if (AddedBy is not null) d["addedBy"] = AddedBy;
        return d;
    }
}
