// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppointmentCompleteRequest
{
    public int? AppointmentID { get; set; }
    /// <summary>The status of an appointment which can include:0: Pending, 1: Completed, 2: No Show</summary>
    public int? Status { get; set; }
    public string? CompletionNotes { get; set; }
    public string? OfficeNotes { get; set; }
    public string? FlagNotes { get; set; }
    public string? TimeIn { get; set; }
    public string? TimeOut { get; set; }
    public string? CheckIn { get; set; }
    public string? CheckOut { get; set; }
    public decimal? LatIn { get; set; }
    public decimal? LatOut { get; set; }
    public decimal? LongIn { get; set; }
    public decimal? LongOut { get; set; }
    /// <summary>base64 encoded signature</summary>
    public string? Signature { get; set; }
    /// <summary>base64 encoded signature</summary>
    public string? TechSignature { get; set; }
    public int? WindSpeed { get; set; }
    /// <summary>N,NW,NE,etc..</summary>
    public string? WindDirection { get; set; }
    public int? ServicedInterior { get; set; }
    public int? Temperature { get; set; }
    public int? SprayRigID { get; set; }
    public int? PaymentMethod { get; set; }
    public decimal? AmountCollected { get; set; }
    public int? CheckCollectedNumber { get; set; }
    public List<object>? Chemicals { get; set; }
    public int? EmployeeID { get; set; }
    public int? CompletedBy { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (AppointmentID is null) throw new ArgumentException("Required parameter AppointmentID is null.", nameof(AppointmentID));
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (Status is not null) d["status"] = Status;
        if (CompletionNotes is not null) d["completionNotes"] = CompletionNotes;
        if (OfficeNotes is not null) d["officeNotes"] = OfficeNotes;
        if (FlagNotes is not null) d["flagNotes"] = FlagNotes;
        if (TimeIn is not null) d["timeIn"] = TimeIn;
        if (TimeOut is not null) d["timeOut"] = TimeOut;
        if (CheckIn is not null) d["checkIn"] = CheckIn;
        if (CheckOut is not null) d["checkOut"] = CheckOut;
        if (LatIn is not null) d["latIn"] = LatIn;
        if (LatOut is not null) d["latOut"] = LatOut;
        if (LongIn is not null) d["longIn"] = LongIn;
        if (LongOut is not null) d["longOut"] = LongOut;
        if (Signature is not null) d["signature"] = Signature;
        if (TechSignature is not null) d["techSignature"] = TechSignature;
        if (WindSpeed is not null) d["windSpeed"] = WindSpeed;
        if (WindDirection is not null) d["windDirection"] = WindDirection;
        if (ServicedInterior is not null) d["servicedInterior"] = ServicedInterior;
        if (Temperature is not null) d["temperature"] = Temperature;
        if (SprayRigID is not null) d["sprayRigID"] = SprayRigID;
        if (PaymentMethod is not null) d["paymentMethod"] = PaymentMethod;
        if (AmountCollected is not null) d["amountCollected"] = AmountCollected;
        if (CheckCollectedNumber is not null) d["checkCollectedNumber"] = CheckCollectedNumber;
        if (Chemicals is not null) d["chemicals"] = Chemicals;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (CompletedBy is not null) d["completedBy"] = CompletedBy;
        return d;
    }
}
