// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesEmployeeGetBulkParameters
{
    /// <summary>Send as 1 to retrieve additional commission data for the employee.</summary>
    public int? IncludeCommissionData { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (IncludeCommissionData is not null) d["includeCommissionData"] = IncludeCommissionData;
        return d;
    }
}
