// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSkillCreateRequest
{
    /// <summary>Name of skill</summary>
    public string? Name { get; set; }
    /// <summary>officeID this skill is specific to, or -1 to be available to all offices</summary>
    public int? OfficeID { get; set; }
    /// <summary>Skill visibility: 1 = visible, 0 = hidden</summary>
    public int? Visible { get; set; }
    /// <summary>Array of serviceType IDs the skill should be for</summary>
    public string? ServiceIDs { get; set; }
    /// <summary>Array of productIDs the skill should be for</summary>
    public string? ProductIDs { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (Name is null) throw new ArgumentException("Required parameter Name is null.", nameof(Name));
        if (Name is not null) d["name"] = Name;
        if (OfficeID is null) throw new ArgumentException("Required parameter OfficeID is null.", nameof(OfficeID));
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (Visible is null) throw new ArgumentException("Required parameter Visible is null.", nameof(Visible));
        if (Visible is not null) d["visible"] = Visible;
        if (ServiceIDs is not null) d["serviceIDs"] = ServiceIDs;
        if (ProductIDs is not null) d["productIDs"] = ProductIDs;
        return d;
    }
}
