// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesEmployeeResetRequest
{
    /// <summary>EmployeeID</summary>
    public int? EmployeeID { get; set; }
    /// <summary>login username</summary>
    public string? Username { get; set; }
    /// <summary>Send recovery email, default behaviour if not send flags are included.</summary>
    public int? SendEmail { get; set; }
    /// <summary>Send recovery sms</summary>
    public int? SendSMS { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (Username is not null) d["username"] = Username;
        if (SendEmail is not null) d["sendEmail"] = SendEmail;
        if (SendSMS is not null) d["sendSMS"] = SendSMS;
        return d;
    }
}
