// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesServicePlanRoundUpdateRequest
{
    /// <summary>Primary key to the subscriptions table.</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>Service plan round description/abbreviation</summary>
    public string? Description { get; set; }
    /// <summary>Start date for this service round</summary>
    public string? StartDate { get; set; }
    /// <summary>End date for this service round</summary>
    public string? EndDate { get; set; }
    /// <summary>Days to wait after the prior service round completed before starting this service round</summary>
    public int? DaysAfterPrerequisite { get; set; }
    /// <summary>Maximum number of days to wait before starting this service round</summary>
    public int? MaxDelay { get; set; }
    /// <summary>The skip/omit status for the round</summary>
    public string? Skipped { get; set; }
    /// <summary>The skip reason for MANUAL_SKIPPED rounds, defined in skipReasons table</summary>
    public int? SkipReasonID { get; set; }
    /// <summary>The skip notes for MANUAL_SKIPPED rounds</summary>
    public string? SkippedNotes { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (SubscriptionID is null) throw new ArgumentException("Required parameter SubscriptionID is null.", nameof(SubscriptionID));
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (Description is not null) d["description"] = Description;
        if (StartDate is not null) d["startDate"] = StartDate;
        if (EndDate is not null) d["endDate"] = EndDate;
        if (DaysAfterPrerequisite is not null) d["daysAfterPrerequisite"] = DaysAfterPrerequisite;
        if (MaxDelay is not null) d["maxDelay"] = MaxDelay;
        if (Skipped is not null) d["skipped"] = Skipped;
        if (SkipReasonID is not null) d["skipReasonID"] = SkipReasonID;
        if (SkippedNotes is not null) d["skippedNotes"] = SkippedNotes;
        return d;
    }
}
