// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesContractCreateRequest
{
    /// <summary>Foreign key to subscriptions table.</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>Alternative to subscriptionID. This is the \"SubscriptionID\" sent during an API insert through import/main.</summary>
    public int? SubscriptionLink { get; set; }
    /// <summary>Set as 1 to also send a link to the customer via email.</summary>
    public int? EmailCustomer { get; set; }
    /// <summary>The date the contract was signed. Required if uploading a signed document. Date formats m/d/y or y-m-d</summary>
    public string? DateSigned { get; set; }
    /// <summary>The Base64 encoded signed contract. Pass this if not sending the file.</summary>
    public string? Base64EncodedFile { get; set; }
    /// <summary>Set to 1 by default, will send out email to customer with contract as well as a first appointment reminder</summary>
    public int? NotifyCustomerOnSignedAgreement { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (SubscriptionLink is not null) d["subscriptionLink"] = SubscriptionLink;
        if (EmailCustomer is not null) d["emailCustomer"] = EmailCustomer;
        if (DateSigned is not null) d["dateSigned"] = DateSigned;
        if (Base64EncodedFile is not null) d["base64EncodedFile"] = Base64EncodedFile;
        if (NotifyCustomerOnSignedAgreement is not null) d["notifyCustomerOnSignedAgreement"] = NotifyCustomerOnSignedAgreement;
        return d;
    }
}
