// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppointmentGetBulkParameters
{
    /// <summary>Send as 1 to retrieve an additional field cancellationReason.</summary>
    public int? IncludeCancellationReason { get; set; }
    /// <summary>Send as 1 to retrieve an additional field targetPests as an array of integers.</summary>
    public int? IncludeTargetPests { get; set; }
    /// <summary>Send as 1 to retrieve an additional field customFields as an array of Custom Fields names and values.</summary>
    public int? IncludeCustomFields { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (IncludeCancellationReason is not null) d["includeCancellationReason"] = IncludeCancellationReason;
        if (IncludeTargetPests is not null) d["includeTargetPests"] = IncludeTargetPests;
        if (IncludeCustomFields is not null) d["includeCustomFields"] = IncludeCustomFields;
        return d;
    }
}
