// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesPaymentCreateRequest
{
    /// <summary>1 - payment will be processed via FieldRoutes. 0 - payment is inserted as a completed payment without charging.</summary>
    public int? DoCharge { get; set; }
    /// <summary>Payment Method 0-Coupon, 1-Cash, 2-Check, 3-Credit Card, 4 ACH</summary>
    public int? PaymentMethod { get; set; }
    /// <summary>customerID to associate the payment with</summary>
    public int? CustomerID { get; set; }
    /// <summary>Amount this payment was for</summary>
    public decimal? Amount { get; set; }
    /// <summary>Employee to associate with the payment</summary>
    public int? EmployeeID { get; set; }
    /// <summary>Description for this payment</summary>
    public int? Notes { get; set; }
    /// <summary>Limit payment to this ticket</summary>
    public int? TicketID { get; set; }
    /// <summary>Limit payment to this subscription</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>Limit use specified paymentProfileID for payment (must be owned by customer)</summary>
    public int? PaymentProfileID { get; set; }
    /// <summary>Only applies with doCharge=0. Set as 0 to create a failed payment record, 1 to create a success</summary>
    public int? Status { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (DoCharge is null) throw new ArgumentException("Required parameter DoCharge is null.", nameof(DoCharge));
        if (DoCharge is not null) d["doCharge"] = DoCharge;
        if (PaymentMethod is null) throw new ArgumentException("Required parameter PaymentMethod is null.", nameof(PaymentMethod));
        if (PaymentMethod is not null) d["paymentMethod"] = PaymentMethod;
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (Amount is null) throw new ArgumentException("Required parameter Amount is null.", nameof(Amount));
        if (Amount is not null) d["amount"] = Amount;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (Notes is not null) d["notes"] = Notes;
        if (TicketID is not null) d["ticketID"] = TicketID;
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (PaymentProfileID is not null) d["paymentProfileID"] = PaymentProfileID;
        if (Status is not null) d["status"] = Status;
        return d;
    }
}
