// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesPaymentProfileCreateRequest
{
    /// <summary>Foreign Key to customers table</summary>
    public int? CustomerID { get; set; }
    /// <summary>Billing name associated with payment profile</summary>
    public string? BillingName { get; set; }
    /// <summary>Billing address associated with payment profile</summary>
    public string? BillingAddress1 { get; set; }
    /// <summary>Billing address associated with payment profile</summary>
    public string? BillingAddress2 { get; set; }
    /// <summary>Billing city associated with payment profile</summary>
    public string? BillingCity { get; set; }
    /// <summary>Billing state associated with payment profile</summary>
    public string? BillingState { get; set; }
    /// <summary>Billing zip code associated with payment profile</summary>
    public int? BillingZip { get; set; }
    /// <summary>Billing country code associated with payment profile</summary>
    public string? BillingCountryID { get; set; }
    /// <summary>1=cc, 2 = ach</summary>
    public int? PaymentMethod { get; set; }
    /// <summary>ACH or CC gateway E.G. authorize, nmi, brain, element, payrix</summary>
    public string? Gateway { get; set; }
    /// <summary>ACH only</summary>
    public string? BankName { get; set; }
    /// <summary>ACH only - check account number</summary>
    public string? AccountNumber { get; set; }
    /// <summary>ACH only - routing number</summary>
    public string? RoutingNumber { get; set; }
    /// <summary>ACH only - 0=checking, 1=savings</summary>
    public int? CheckType { get; set; }
    /// <summary>ACH only - 0=personal, 1=business</summary>
    public int? AccountType { get; set; }
    /// <summary>Required for braintree and element. Not required for nmi</summary>
    public string? MerchantID { get; set; }
    /// <summary>Required for braintree and nmi. Not required for element</summary>
    public string? MerchantToken { get; set; }
    /// <summary>Send as 1 to set the owning customer to autopay using this profile</summary>
    public int? Autopay { get; set; }
    /// <summary>Hold date for the payment profile</summary>
    public string? PaymentHoldDate { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (BillingName is not null) d["billingName"] = BillingName;
        if (BillingAddress1 is not null) d["billingAddress1"] = BillingAddress1;
        if (BillingAddress2 is not null) d["billingAddress2"] = BillingAddress2;
        if (BillingCity is not null) d["billingCity"] = BillingCity;
        if (BillingState is not null) d["billingState"] = BillingState;
        if (BillingZip is not null) d["billingZip"] = BillingZip;
        if (BillingCountryID is not null) d["billingCountryID"] = BillingCountryID;
        if (PaymentMethod is null) throw new ArgumentException("Required parameter PaymentMethod is null.", nameof(PaymentMethod));
        if (PaymentMethod is not null) d["paymentMethod"] = PaymentMethod;
        if (Gateway is not null) d["gateway"] = Gateway;
        if (BankName is not null) d["bankName"] = BankName;
        if (AccountNumber is not null) d["accountNumber"] = AccountNumber;
        if (RoutingNumber is not null) d["routingNumber"] = RoutingNumber;
        if (CheckType is not null) d["checkType"] = CheckType;
        if (AccountType is not null) d["accountType"] = AccountType;
        if (MerchantID is not null) d["merchantID"] = MerchantID;
        if (MerchantToken is not null) d["merchantToken"] = MerchantToken;
        if (Autopay is not null) d["autopay"] = Autopay;
        if (PaymentHoldDate is not null) d["paymentHoldDate"] = PaymentHoldDate;
        return d;
    }
}
