// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesEmployeeDealiasRequest
{
    /// <summary>Primary key of the employee</summary>
    public int? EmployeeID { get; set; }
    /// <summary>External key of the employee</summary>
    public int? EmployeeLink { get; set; }
    /// <summary>active property of the employee 0: inactive 1: active</summary>
    public int? Active { get; set; }
    /// <summary>Send as 1 to join on both roamingRep and employeeLink relationship</summary>
    public int? UseBothKeys { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (EmployeeLink is not null) d["employeeLink"] = EmployeeLink;
        if (Active is not null) d["active"] = Active;
        if (UseBothKeys is not null) d["useBothKeys"] = UseBothKeys;
        return d;
    }
}
