// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesRouteGetParameters
{
    /// <summary>Latitude for distance calculcations. If not specified, the office longitude will be used</summary>
    public decimal? Latitude { get; set; }
    /// <summary>Longitude for distance calculcations. If not specified, the office longitude will be used</summary>
    public decimal? Longitude { get; set; }
    /// <summary>Maximum number of miles from the route average to return.</summary>
    public int? MaxDistance { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (Latitude is not null) d["latitude"] = Latitude;
        if (Longitude is not null) d["longitude"] = Longitude;
        if (MaxDistance is not null) d["maxDistance"] = MaxDistance;
        return d;
    }
}
