// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTicketUpdateRequest
{
    /// <summary>Foreign key to customers table.</summary>
    public int? CustomerID { get; set; }
    /// <summary>Foreign key to subscription table.</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>Foreign key to serviceTypes table.</summary>
    public int? ServiceID { get; set; }
    /// <summary>1- tax 0 - no tax; Defaults to the value specified for given serviceID.</summary>
    public int? ServiceTaxable { get; set; }
    /// <summary>Date this invoice should be applied</summary>
    public string? Date { get; set; }
    /// <summary>Foreign key to customers table.</summary>
    public int? BillToAccountID { get; set; }
    /// <summary>Value in USD.</summary>
    public decimal? ServiceCharge { get; set; }
    /// <summary>Add notes about the invoice.</summary>
    public string? AdditionalNotes { get; set; }
    /// <summary>0 = not active, 1 = active, -1 = ticket template, -3 = lead</summary>
    public string? Status { get; set; }
    /// <summary>R = recurring, I = initial, NA = not applicable/not a template</summary>
    public string? TemplateType { get; set; }
    /// <summary>Production value for this ticket.</summary>
    public decimal? ProductionValue { get; set; }
    /// <summary>If addons are sent with ticket/update a setAddons operation will be used. Old addons will be removed and new addons will be created to match the array sent.</summary>
    public List<object>? Addons { get; set; }
    /// <summary>Primary key to the tickets table.</summary>
    public int? TicketID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (ServiceID is not null) d["serviceID"] = ServiceID;
        if (ServiceTaxable is not null) d["serviceTaxable"] = ServiceTaxable;
        if (Date is not null) d["date"] = Date;
        if (BillToAccountID is not null) d["billToAccountID"] = BillToAccountID;
        if (ServiceCharge is not null) d["serviceCharge"] = ServiceCharge;
        if (AdditionalNotes is not null) d["additionalNotes"] = AdditionalNotes;
        if (Status is not null) d["status"] = Status;
        if (TemplateType is not null) d["templateType"] = TemplateType;
        if (ProductionValue is not null) d["productionValue"] = ProductionValue;
        if (Addons is not null) d["addons"] = Addons;
        if (TicketID is null) throw new ArgumentException("Required parameter TicketID is null.", nameof(TicketID));
        if (TicketID is not null) d["ticketID"] = TicketID;
        return d;
    }
}
