// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerFlagGetBulkParameters : FieldRoutesQueryBase
{
    /// <summary>Standard search filter. E.G. \"limitCustomerFlags\": {\"operator\":\"IN\",\"value\":[\"myFlag\",\"yourflag\"}</summary>
    public string? LimitCustomerFlags { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (LimitCustomerFlags is not null) d["limitCustomerFlags"] = LimitCustomerFlags;
        return d;
    }
}
