// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesGroupCreateRequest
{
    /// <summary>Date to create for</summary>
    public string? Date { get; set; }
    /// <summary>templateID from office software</summary>
    public int? TemplateID { get; set; }
    /// <summary>Title string (30 character limit)</summary>
    public string? Title { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (Date is not null) d["date"] = Date;
        if (TemplateID is not null) d["templateID"] = TemplateID;
        if (Title is not null) d["title"] = Title;
        return d;
    }
}
