// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerCreatePaymentProfileRequest
{
    /// <summary>Foreign Key to customers table</summary>
    public int? CustomerID { get; set; }
    /// <summary>Required for braintree and element. Not required for nmi</summary>
    public string? CreditCardToken { get; set; }
    /// <summary>Required for braintree and nmi. Not required for element</summary>
    public string? CreditCardTokenID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (CreditCardToken is not null) d["CreditCardToken"] = CreditCardToken;
        if (CreditCardTokenID is not null) d["CreditCardTokenID"] = CreditCardTokenID;
        return d;
    }
}
