// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesPaymentCreateRefundRequest
{
    /// <summary>paymentID to refund</summary>
    public int? PaymentID { get; set; }
    /// <summary>Amount this payment was for</summary>
    public decimal? Amount { get; set; }
    /// <summary>Send as 1 to create a payment record without processing the refund</summary>
    public int? SkipProcessing { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (PaymentID is null) throw new ArgumentException("Required parameter PaymentID is null.", nameof(PaymentID));
        if (PaymentID is not null) d["paymentID"] = PaymentID;
        if (Amount is not null) d["amount"] = Amount;
        if (SkipProcessing is not null) d["skipProcessing"] = SkipProcessing;
        return d;
    }
}
