// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSubscriptionSetInitialAddOnsRequest
{
    /// <summary>Foreign key to subscriptions table.</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>Addon Entity - see createInitialAddOn params</summary>
    public List<object>? Addons { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (SubscriptionID is null) throw new ArgumentException("Required parameter SubscriptionID is null.", nameof(SubscriptionID));
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (Addons is not null) d["addons"] = Addons;
        return d;
    }
}
