// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSubscriptionUpdateRequest
{
    /// <summary>Subscription Link for import</summary>
    public string? SubscriptionLink { get; set; }
    /// <summary>The service type ID for the regular recurring services</summary>
    public int? ServiceID { get; set; }
    /// <summary>Customer ID which this subscription belongs to</summary>
    public int? CustomerID { get; set; }
    /// <summary>Billing Account which this subscription belongs to</summary>
    public int? BillToAccountID { get; set; }
    /// <summary>0: frozen, 1: active and being placed in the job pool.</summary>
    public int? Active { get; set; }
    /// <summary>Frequency that an invoice is generated for this service. -1/0</summary>
    public int? BillingFrequency { get; set; }
    /// <summary>The frequency that the services get scheduled. -1 represents One-Time, 0 represents 'as needed'. Greater than 0 represents the frequency in days. If it is divisible by 30, it is converted to months -- so 90 would represent 3 months and not necessarily 90 days.</summary>
    public int? Frequency { get; set; }
    /// <summary>Seasonal Start</summary>
    public string? SeasonalStart { get; set; }
    /// <summary>Seasonal End</summary>
    public string? SeasonalEnd { get; set; }
    /// <summary>How many days after the initial service to schedule the first recurring service. Set as -1 to use frequency</summary>
    public int? FollowupDelay { get; set; }
    /// <summary>Agreement Length</summary>
    public int? AgreementLength { get; set; }
    /// <summary>The employee ID of the preferred tech - 0 for no preference</summary>
    public int? PreferredTech { get; set; }
    /// <summary>Preferred appointment day (0-SUN, 1-MON, 2-TUE, 3-WED, 4-THU, 5-FRI, 6-SAT)</summary>
    public int? PreferredDays { get; set; }
    /// <summary>Preferred appointment start time window in local time e.g. 00:00:00</summary>
    public string? PreferredStart { get; set; }
    /// <summary>Preferred appointment end time window in local time e.g. 14:30:00</summary>
    public string? PreferredEnd { get; set; }
    /// <summary>Subscription Source ID</summary>
    public int? SourceID { get; set; }
    /// <summary>RegionID of the subscription</summary>
    public int? RegionID { get; set; }
    /// <summary>How often a subscription is due for renewal.</summary>
    public int? RenewalFrequency { get; set; }
    /// <summary>Next renewal date</summary>
    public string? RenewalDate { get; set; }
    /// <summary>Custom next appointment date for the subscription.</summary>
    public string? CustomDate { get; set; }
    /// <summary>ID of a pre-defined custom-schedule for services. frequency will be set to -3.</summary>
    public int? CustomScheduleID { get; set; }
    /// <summary>Next billing date for the subscription</summary>
    public string? NextBillingDate { get; set; }
    /// <summary>The default duration in minutes for the appointment. Set to -1 to inherit from the service type.</summary>
    public int? Duration { get; set; }
    /// <summary>Value of the lead</summary>
    public decimal? LeadValue { get; set; }
    /// <summary>Expiration date of the subscription</summary>
    public int? ExpirationDate { get; set; }
    /// <summary>The employee ID that added the subscription</summary>
    public int? AddedBy { get; set; }
    /// <summary>Date the subscription was cancelled</summary>
    public string? DateCancelled { get; set; }
    /// <summary>Net Billing Days</summary>
    public int? BillingTermsDays { get; set; }
    /// <summary>subscription poNumber</summary>
    public string? PoNumber { get; set; }
    /// <summary>int in minutes</summary>
    public int? CallAhead { get; set; }
    /// <summary>The employee ID who gets credit for this sale. Defaults to the user who added the subscription</summary>
    public int? SoldBy { get; set; }
    /// <summary>Additional employeeID that gets credit for this sale</summary>
    public int? SoldBy2 { get; set; }
    /// <summary>Additional employeeID that gets credit for this sale</summary>
    public int? SoldBy3 { get; set; }
    /// <summary>Automatically convert the subscription to a lead following the request</summary>
    public int? ConvertToLead { get; set; }
    /// <summary>When the initial invoice should get generated. INITIAL_COMPLETION = when the initial service is completed. SIGNED_AGREEMENT = when the agreement is signed. INITIAL_BILLING_DATE = on a specified billing date.</summary>
    public string? InitialInvoice { get; set; }
    /// <summary>Primary key to the tickets table.</summary>
    public int? SubscriptionID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (SubscriptionLink is not null) d["subscriptionLink"] = SubscriptionLink;
        if (ServiceID is not null) d["serviceID"] = ServiceID;
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (BillToAccountID is not null) d["billToAccountID"] = BillToAccountID;
        if (Active is not null) d["active"] = Active;
        if (BillingFrequency is not null) d["billingFrequency"] = BillingFrequency;
        if (Frequency is not null) d["frequency"] = Frequency;
        if (SeasonalStart is not null) d["seasonalStart"] = SeasonalStart;
        if (SeasonalEnd is not null) d["seasonalEnd"] = SeasonalEnd;
        if (FollowupDelay is not null) d["followupDelay"] = FollowupDelay;
        if (AgreementLength is not null) d["agreementLength"] = AgreementLength;
        if (PreferredTech is not null) d["preferredTech"] = PreferredTech;
        if (PreferredDays is not null) d["preferredDays"] = PreferredDays;
        if (PreferredStart is not null) d["preferredStart"] = PreferredStart;
        if (PreferredEnd is not null) d["preferredEnd"] = PreferredEnd;
        if (SourceID is not null) d["sourceID"] = SourceID;
        if (RegionID is not null) d["regionID"] = RegionID;
        if (RenewalFrequency is not null) d["renewalFrequency"] = RenewalFrequency;
        if (RenewalDate is not null) d["renewalDate"] = RenewalDate;
        if (CustomDate is not null) d["customDate"] = CustomDate;
        if (CustomScheduleID is not null) d["customScheduleID"] = CustomScheduleID;
        if (NextBillingDate is not null) d["nextBillingDate"] = NextBillingDate;
        if (Duration is not null) d["duration"] = Duration;
        if (LeadValue is not null) d["leadValue"] = LeadValue;
        if (ExpirationDate is not null) d["expirationDate"] = ExpirationDate;
        if (AddedBy is not null) d["addedBy"] = AddedBy;
        if (DateCancelled is not null) d["dateCancelled"] = DateCancelled;
        if (BillingTermsDays is not null) d["billingTermsDays"] = BillingTermsDays;
        if (PoNumber is not null) d["poNumber"] = PoNumber;
        if (CallAhead is not null) d["callAhead"] = CallAhead;
        if (SoldBy is not null) d["soldBy"] = SoldBy;
        if (SoldBy2 is not null) d["soldBy2"] = SoldBy2;
        if (SoldBy3 is not null) d["soldBy3"] = SoldBy3;
        if (ConvertToLead is not null) d["convertToLead"] = ConvertToLead;
        if (InitialInvoice is not null) d["initialInvoice"] = InitialInvoice;
        if (SubscriptionID is null) throw new ArgumentException("Required parameter SubscriptionID is null.", nameof(SubscriptionID));
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        return d;
    }
}
