// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSpotReserveRequest
{
    /// <summary>Foreign key to spots table</summary>
    public int? SpotID { get; set; }
    /// <summary>Array of spotIDs. If sent, the first available spotID in this set will be reserved</summary>
    public int[]? SpotOptions { get; set; }
    /// <summary>duration of the lock in minutes</summary>
    public int? Duration { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (SpotID is not null) d["spotID"] = SpotID;
        if (SpotOptions is not null) d["spotOptions"] = SpotOptions;
        if (Duration is null) throw new ArgumentException("Required parameter Duration is null.", nameof(Duration));
        if (Duration is not null) d["duration"] = Duration;
        return d;
    }
}
