// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesDocumentCreateRequest
{
    /// <summary>Customer ID this document relates to.</summary>
    public int? CustomerID { get; set; }
    /// <summary>Description for this document</summary>
    public int? Description { get; set; }
    /// <summary>Appointment ID this document relates to</summary>
    public int? AppointmentID { get; set; }
    /// <summary>If set true this document will be accessable to the customer it is attached to.</summary>
    public bool? ShowCustomer { get; set; }
    /// <summary>If set true this document will be accessable to technicians servicing this customer.</summary>
    public bool? ShowTech { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (Description is null) throw new ArgumentException("Required parameter Description is null.", nameof(Description));
        if (Description is not null) d["description"] = Description;
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (ShowCustomer is not null) d["showCustomer"] = ShowCustomer;
        if (ShowTech is not null) d["showTech"] = ShowTech;
        return d;
    }
}
