// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerGetBulkParameters
{
    /// <summary>Send as 1 to retrieve an array of cancellationNotes associated with each customer.</summary>
    public int? IncludeCancellationReason { get; set; }
    /// <summary>Send as 1 to retrieve an array of subscriptions associated with each customer.</summary>
    public int? IncludeSubscriptions { get; set; }
    /// <summary>Send as 1 to retrieve an array of flags associated with each customer.</summary>
    public int? IncludeCustomerFlag { get; set; }
    /// <summary>Send as 1 to retrieve an array of additional contacts associated with each customer.</summary>
    public int? IncludeAdditionalContacts { get; set; }
    /// <summary>Send as 1 to retrieve additional properties portalLogin (full URL for customer login) and portalLoginExpires (datetime in PST). Portal token guarenteed valid for 3 days or longer.</summary>
    public int? IncludePortalLogin { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (IncludeCancellationReason is not null) d["includeCancellationReason"] = IncludeCancellationReason;
        if (IncludeSubscriptions is not null) d["includeSubscriptions"] = IncludeSubscriptions;
        if (IncludeCustomerFlag is not null) d["includeCustomerFlag"] = IncludeCustomerFlag;
        if (IncludeAdditionalContacts is not null) d["includeAdditionalContacts"] = IncludeAdditionalContacts;
        if (IncludePortalLogin is not null) d["includePortalLogin"] = IncludePortalLogin;
        return d;
    }
}
