// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesReviewDeleteRequest
{
    /// <summary>Primary key of the customerFeedback table</summary>
    public int? FeedbackID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (FeedbackID is null) throw new ArgumentException("Required parameter FeedbackID is null.", nameof(FeedbackID));
        if (FeedbackID is not null) d["feedbackID"] = FeedbackID;
        return d;
    }
}
