// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesTicketCreateAddOnRequest
{
    /// <summary>Foreign key to tickets table. Retrieve via getAddons(subscriptionID).</summary>
    public int? TicketID { get; set; }
    /// <summary>Customer Facing text for item.</summary>
    public string? Description { get; set; }
    /// <summary>Number of products or services to add.</summary>
    public int? Quantity { get; set; }
    /// <summary>Charge Amount for item.</summary>
    public decimal? Amount { get; set; }
    /// <summary>Foreign key to products table.</summary>
    public int? ProductID { get; set; }
    /// <summary>Foreign key to services Table.</summary>
    public int? ServiceID { get; set; }
    /// <summary>0 for untaxable, 1 for taxable. Items with negative amounts cannot be taxable.</summary>
    public int? Taxable { get; set; }
    /// <summary>Foreign key to employees table.</summary>
    public int? CreditTo { get; set; }
    /// <summary>Foreign key to unit table (if applicable for unit specific addons on multi-unit customers)</summary>
    public int? UnitID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (TicketID is null) throw new ArgumentException("Required parameter TicketID is null.", nameof(TicketID));
        if (TicketID is not null) d["ticketID"] = TicketID;
        if (Description is not null) d["description"] = Description;
        if (Quantity is not null) d["quantity"] = Quantity;
        if (Amount is null) throw new ArgumentException("Required parameter Amount is null.", nameof(Amount));
        if (Amount is not null) d["amount"] = Amount;
        if (ProductID is not null) d["productID"] = ProductID;
        if (ServiceID is not null) d["serviceID"] = ServiceID;
        if (Taxable is null) throw new ArgumentException("Required parameter Taxable is null.", nameof(Taxable));
        if (Taxable is not null) d["taxable"] = Taxable;
        if (CreditTo is not null) d["creditTo"] = CreditTo;
        if (UnitID is not null) d["unitID"] = UnitID;
        return d;
    }
}
