// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesEmployeeUpdateRequest
{
    /// <summary>0: office staff, 1: technician, 2: salesman</summary>
    public int? Type { get; set; }
    /// <summary>Employee first name.</summary>
    public string? Fname { get; set; }
    /// <summary>Employee last name.</summary>
    public string? Lname { get; set; }
    /// <summary>Employee phone.</summary>
    public string? Phone { get; set; }
    /// <summary>Employee email.</summary>
    public string? Email { get; set; }
    /// <summary>Login username, required for a roaming rep.</summary>
    public string? Username { get; set; }
    /// <summary>Login password, required for a roaming rep.</summary>
    public string? Password { get; set; }
    /// <summary>EmployeeID of the master account. If a non-master account is selected, that account's master rep will be used instead.</summary>
    public int? RoamingRep { get; set; }
    /// <summary>Set as 1 to specify that the user is a roaming master account. This setting will override roamingRep.</summary>
    public int? RoamingMaster { get; set; }
    /// <summary>Array of officeIDs this employee is a manager of. Replaces existing regionalManager offices.</summary>
    public List<object>? RegionalManagers { get; set; }
    /// <summary>Employee's Link</summary>
    public string? EmployeeLink { get; set; }
    /// <summary>Employee's License Number</summary>
    public string? LicenseNumber { get; set; }
    /// <summary>Access Control Profile ID defined in preferences. 0 represents a custom profile.</summary>
    public int? AccessControlProfileID { get; set; }
    /// <summary>Send as form-data array or as a JSON encoded string</summary>
    public string? AccessControl { get; set; }
    /// <summary>Send as 0 to set the employee as inactive, send as 1 to set the employee to active. Default state is active.</summary>
    public int? Active { get; set; }
    /// <summary>Set the primary team for the employee. If the employee is not on this team it will be placed on that team during this operation.</summary>
    public int? PrimaryTeam { get; set; }
    /// <summary>employeeID of the supervisor for this employee.</summary>
    public int? SupervisorID { get; set; }
    /// <summary>Integer (max 2 digits)</summary>
    public int? Experience { get; set; }
    /// <summary>Employee's starting address on routes</summary>
    public string? StartAddress { get; set; }
    /// <summary>Employee's starting city on routes</summary>
    public string? StartCity { get; set; }
    /// <summary>Employee's starting state on routes</summary>
    public string? StartState { get; set; }
    /// <summary>Employee's starting zip on routes</summary>
    public string? StartZip { get; set; }
    /// <summary>Employee's ending address on routes</summary>
    public string? EndAddress { get; set; }
    /// <summary>Employee's ending city on routes</summary>
    public string? EndCity { get; set; }
    /// <summary>Employee's ending state on routes</summary>
    public string? EndState { get; set; }
    /// <summary>Employee's ending zip on routes</summary>
    public string? EndZip { get; set; }
    /// <summary>Array of skillIDs</summary>
    public int? EmployeeSkills { get; set; }
    /// <summary>base64encoded image</summary>
    public string? Pic { get; set; }
    /// <summary>Primary key to the employee table.</summary>
    public int? EmployeeID { get; set; }
    /// <summary>Send as 1 to remove visual grouping assignments for the employee.</summary>
    public int? RemoveVisualGrouping { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (Type is not null) d["type"] = Type;
        if (Fname is not null) d["fname"] = Fname;
        if (Lname is not null) d["lname"] = Lname;
        if (Phone is not null) d["phone"] = Phone;
        if (Email is not null) d["email"] = Email;
        if (Username is not null) d["username"] = Username;
        if (Password is not null) d["password"] = Password;
        if (RoamingRep is not null) d["roamingRep"] = RoamingRep;
        if (RoamingMaster is not null) d["roamingMaster"] = RoamingMaster;
        if (RegionalManagers is not null) d["regionalManagers"] = RegionalManagers;
        if (EmployeeLink is not null) d["employeeLink"] = EmployeeLink;
        if (LicenseNumber is not null) d["licenseNumber"] = LicenseNumber;
        if (AccessControlProfileID is not null) d["accessControlProfileID"] = AccessControlProfileID;
        if (AccessControl is not null) d["accessControl"] = AccessControl;
        if (Active is not null) d["active"] = Active;
        if (PrimaryTeam is not null) d["primaryTeam"] = PrimaryTeam;
        if (SupervisorID is not null) d["supervisorID"] = SupervisorID;
        if (Experience is not null) d["experience"] = Experience;
        if (StartAddress is not null) d["startAddress"] = StartAddress;
        if (StartCity is not null) d["startCity"] = StartCity;
        if (StartState is not null) d["startState"] = StartState;
        if (StartZip is not null) d["startZip"] = StartZip;
        if (EndAddress is not null) d["endAddress"] = EndAddress;
        if (EndCity is not null) d["endCity"] = EndCity;
        if (EndState is not null) d["endState"] = EndState;
        if (EndZip is not null) d["endZip"] = EndZip;
        if (EmployeeSkills is not null) d["employeeSkills"] = EmployeeSkills;
        if (Pic is not null) d["pic"] = Pic;
        if (EmployeeID is null) throw new ArgumentException("Required parameter EmployeeID is null.", nameof(EmployeeID));
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (RemoveVisualGrouping is not null) d["removeVisualGrouping"] = RemoveVisualGrouping;
        return d;
    }
}
