// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesDocumentDeleteRequest
{
    /// <summary>CustomerID to delete from.</summary>
    public int? CustomerID { get; set; }
    /// <summary>UploadID to delete.</summary>
    public int? UploadID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (UploadID is null) throw new ArgumentException("Required parameter UploadID is null.", nameof(UploadID));
        if (UploadID is not null) d["uploadID"] = UploadID;
        return d;
    }
}
