// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesNoteDeleteRequest
{
    /// <summary>Foreign key to customers table.</summary>
    public int? CustomerID { get; set; }
    /// <summary>Foreign key to customerContacts table.</summary>
    public int? ContactID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (ContactID is null) throw new ArgumentException("Required parameter ContactID is null.", nameof(ContactID));
        if (ContactID is not null) d["contactID"] = ContactID;
        return d;
    }
}
