// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesCustomerUpdatePaymentProfileRequest
{
    /// <summary>Foreign Key to customers table</summary>
    public int? CustomerID { get; set; }
    /// <summary>Billing name associated with payment profile</summary>
    public string? BillingName { get; set; }
    /// <summary>Billing address associated with payment profile</summary>
    public string? BillingAddress1 { get; set; }
    /// <summary>Billing city associated with payment profile</summary>
    public string? BillingCity { get; set; }
    /// <summary>Billing state associated with payment profile</summary>
    public string? BillingState { get; set; }
    /// <summary>Billing zip code associated with payment profile</summary>
    public int? BillingZip { get; set; }
    /// <summary>Billing country code associated with payment profile</summary>
    public string? BillingCountryID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (BillingName is not null) d["billingName"] = BillingName;
        if (BillingAddress1 is not null) d["billingAddress1"] = BillingAddress1;
        if (BillingCity is not null) d["billingCity"] = BillingCity;
        if (BillingState is not null) d["billingState"] = BillingState;
        if (BillingZip is not null) d["billingZip"] = BillingZip;
        if (BillingCountryID is not null) d["billingCountryID"] = BillingCountryID;
        return d;
    }
}
