// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesPaymentProfileUpdateRequest
{
    /// <summary>Foreign Key to paymentProfile table</summary>
    public int? PaymentProfileID { get; set; }
    /// <summary>Billing name associated with payment profile</summary>
    public string? BillingFName { get; set; }
    /// <summary>Billing name associated with payment profile</summary>
    public string? BillingLName { get; set; }
    /// <summary>Billing address associated with payment profile</summary>
    public string? BillingAddress1 { get; set; }
    /// <summary>Billing address associated with payment profile</summary>
    public string? BillingAddress2 { get; set; }
    /// <summary>Billing city associated with payment profile</summary>
    public string? BillingCity { get; set; }
    /// <summary>Billing state associated with payment profile</summary>
    public string? BillingState { get; set; }
    /// <summary>Billing zip code associated with payment profile</summary>
    public int? BillingZip { get; set; }
    /// <summary>Billing country code associated with payment profile</summary>
    public string? BillingCountryID { get; set; }
    /// <summary>2 digit month</summary>
    public int? ExpMonth { get; set; }
    /// <summary>2 digit year (e.g. 21 for 2021)</summary>
    public int? ExpYear { get; set; }
    /// <summary>Send as 1 to set the owning customer to autopay using this profile</summary>
    public int? Autopay { get; set; }
    /// <summary>Hold date for the payment profile</summary>
    public string? PaymentHoldDate { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (PaymentProfileID is null) throw new ArgumentException("Required parameter PaymentProfileID is null.", nameof(PaymentProfileID));
        if (PaymentProfileID is not null) d["paymentProfileID"] = PaymentProfileID;
        if (BillingFName is not null) d["billingFName"] = BillingFName;
        if (BillingLName is not null) d["billingLName"] = BillingLName;
        if (BillingAddress1 is not null) d["billingAddress1"] = BillingAddress1;
        if (BillingAddress2 is not null) d["billingAddress2"] = BillingAddress2;
        if (BillingCity is not null) d["billingCity"] = BillingCity;
        if (BillingState is not null) d["billingState"] = BillingState;
        if (BillingZip is not null) d["billingZip"] = BillingZip;
        if (BillingCountryID is not null) d["billingCountryID"] = BillingCountryID;
        if (ExpMonth is not null) d["expMonth"] = ExpMonth;
        if (ExpYear is not null) d["expYear"] = ExpYear;
        if (Autopay is not null) d["autopay"] = Autopay;
        if (PaymentHoldDate is not null) d["paymentHoldDate"] = PaymentHoldDate;
        return d;
    }
}
