// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesAppointmentUpdateRequest
{
    /// <summary>customerID associated with the appointment</summary>
    public int? CustomerID { get; set; }
    /// <summary>serviceID to perform</summary>
    public int? Type { get; set; }
    /// <summary>Start Time Window</summary>
    public string? Start { get; set; }
    /// <summary>End Time Window</summary>
    public string? End { get; set; }
    /// <summary>Number of minutes this appointment should last</summary>
    public int? Duration { get; set; }
    /// <summary>employeeID to whom this appointment belongs</summary>
    public int? EmployeeID { get; set; }
    /// <summary>Appointment Notes</summary>
    public string? Notes { get; set; }
    /// <summary>Specify to fix this appointment to a spot</summary>
    public object? SpotID { get; set; }
    /// <summary>Specify to fix this appointment on a route.</summary>
    public int? RouteID { get; set; }
    /// <summary>Number of minutes ahead of the appointment start time to call</summary>
    public int? CallAhead { get; set; }
    /// <summary>employeeID of the technician assigned to this appointment</summary>
    public int? AssignedTech { get; set; }
    /// <summary>Specify the subscriptionID this appointment is associated with</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>0 - unspecified, 1 - Exterior only, 2 - Interior Needed</summary>
    public int? DoInterior { get; set; }
    /// <summary>Comma separated list of insectIDs</summary>
    public string? TargetPests { get; set; }
    /// <summary>Send as 1 to receive a failure result when the appointment would create a second appointment in the same spot as another appointment (fixed or floating appointments).</summary>
    public int? RejectOccupiedSpots { get; set; }
    /// <summary>Send as 1 to receive a failure result when the appointment would create a second appointment in the same spot as another fixed-to-spot appointment appointment.</summary>
    public int? RejectFixedOccupiedSpots { get; set; }
    /// <summary>If the spotID sent has been reserved, send a bearer token to schedule to a reserved spot</summary>
    public string? Reservation { get; set; }
    /// <summary>Ignore locked route setting and schedule anyways</summary>
    public int? BypassLockedRoute { get; set; }
    /// <summary>Ignore api can schedule on route and schedule anyways.</summary>
    public int? BypassSchedulePermission { get; set; }
    /// <summary>employeeID who completed the appointment</summary>
    public int? ServicedBy { get; set; }
    /// <summary>The employee ID who marked this as serviced -- not necessarily which tech completed the service.</summary>
    public int? CompletedBy { get; set; }
    /// <summary>When multiple appointments occupy the same spot this determines which of the appointments will be first.</summary>
    public int? Sequence { get; set; }
    /// <summary>Primary key to the appointments table.</summary>
    public int? AppointmentID { get; set; }
    /// <summary>The time the technician checked into the appointment (via user defined input).</summary>
    public string? TimeIn { get; set; }
    /// <summary>The time the technician checked out of the appointment (via user-defined input).</summary>
    public string? TimeOut { get; set; }
    /// <summary>The time the technician checked into the appointment (via check-in button).</summary>
    public string? CheckIn { get; set; }
    /// <summary>The time the technician checked out of the appointment (via check-out button).</summary>
    public string? CheckOut { get; set; }
    /// <summary>The status of an appointment which can include:0: Pending, 1: Completed, 2: No Show</summary>
    public int? Status { get; set; }
    /// <summary>employeeID of employee that cancelled the appointment, if setting to status No Show</summary>
    public int? CancelledBy { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (Type is not null) d["type"] = Type;
        if (Start is not null) d["start"] = Start;
        if (End is not null) d["end"] = End;
        if (Duration is not null) d["duration"] = Duration;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (Notes is not null) d["notes"] = Notes;
        if (SpotID is not null) d["spotID"] = SpotID;
        if (RouteID is not null) d["routeID"] = RouteID;
        if (CallAhead is not null) d["callAhead"] = CallAhead;
        if (AssignedTech is not null) d["assignedTech"] = AssignedTech;
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (DoInterior is not null) d["doInterior"] = DoInterior;
        if (TargetPests is not null) d["targetPests"] = TargetPests;
        if (RejectOccupiedSpots is not null) d["rejectOccupiedSpots"] = RejectOccupiedSpots;
        if (RejectFixedOccupiedSpots is not null) d["rejectFixedOccupiedSpots"] = RejectFixedOccupiedSpots;
        if (Reservation is not null) d["reservation"] = Reservation;
        if (BypassLockedRoute is not null) d["bypassLockedRoute"] = BypassLockedRoute;
        if (BypassSchedulePermission is not null) d["bypassSchedulePermission"] = BypassSchedulePermission;
        if (ServicedBy is not null) d["servicedBy"] = ServicedBy;
        if (CompletedBy is not null) d["completedBy"] = CompletedBy;
        if (Sequence is not null) d["sequence"] = Sequence;
        if (AppointmentID is null) throw new ArgumentException("Required parameter AppointmentID is null.", nameof(AppointmentID));
        if (AppointmentID is not null) d["appointmentID"] = AppointmentID;
        if (TimeIn is not null) d["timeIn"] = TimeIn;
        if (TimeOut is not null) d["timeOut"] = TimeOut;
        if (CheckIn is not null) d["checkIn"] = CheckIn;
        if (CheckOut is not null) d["checkOut"] = CheckOut;
        if (Status is not null) d["status"] = Status;
        if (CancelledBy is not null) d["cancelledBy"] = CancelledBy;
        return d;
    }
}
