// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesServicePlanGetParameters
{
    /// <summary>Send as 1 to retrieve an array of cancellationNotes associated with the subscription.</summary>
    public int? IncludeCancellationReason { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (IncludeCancellationReason is not null) d["includeCancellationReason"] = IncludeCancellationReason;
        return d;
    }
}
