// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSubscriptionCreateInitialAddOnRequest
{
    /// <summary>Foreign key to subscriptions table.</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>Foreign key to products table.</summary>
    public int? ProductID { get; set; }
    /// <summary>Foreign key to serviceTypes table.</summary>
    public int? ServiceID { get; set; }
    /// <summary>Amount to charge for this addon.</summary>
    public decimal? Amount { get; set; }
    /// <summary>The number of items. Defaults to 1.</summary>
    public int? Quantity { get; set; }
    /// <summary>1- tax 0 - no tax; Defaults to the value specified for serviceTaxable on initial ticket.</summary>
    public int? Taxable { get; set; }
    /// <summary>The employee who will receive credit for selling the add-on for commissions. Defaults to creditTo on Service Subscription.</summary>
    public int? CreditTo { get; set; }
    /// <summary>Customer facing text for item.</summary>
    public string? Description { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (SubscriptionID is null) throw new ArgumentException("Required parameter SubscriptionID is null.", nameof(SubscriptionID));
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (ProductID is null) throw new ArgumentException("Required parameter ProductID is null.", nameof(ProductID));
        if (ProductID is not null) d["productID"] = ProductID;
        if (ServiceID is not null) d["serviceID"] = ServiceID;
        if (Amount is null) throw new ArgumentException("Required parameter Amount is null.", nameof(Amount));
        if (Amount is not null) d["amount"] = Amount;
        if (Quantity is not null) d["quantity"] = Quantity;
        if (Taxable is not null) d["taxable"] = Taxable;
        if (CreditTo is not null) d["creditTo"] = CreditTo;
        if (Description is not null) d["description"] = Description;
        return d;
    }
}
