// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesNoteCreateRequest
{
    /// <summary>Foreign key to customers table.</summary>
    public int? CustomerID { get; set; }
    /// <summary>Date of the note (mutable)</summary>
    public string? Date { get; set; }
    /// <summary>Foreign key to employees table.</summary>
    public int? EmployeeID { get; set; }
    /// <summary>Foreign key to contactTypes table found via Admin &gt; Preferences &gt; Note Types</summary>
    public int? ContactType { get; set; }
    /// <summary>Arbitrary comment string</summary>
    public string? Notes { get; set; }
    /// <summary>System field?</summary>
    public string? SendTo { get; set; }
    /// <summary>1 to display this note on invoices, 0 to hide</summary>
    public bool? ShowOnInvoice { get; set; }
    /// <summary>Foreign key to cancellationReasons table found via Admin &gt; Preferences &gt; Cancellation Reasons</summary>
    public int? CancellationReason { get; set; }
    /// <summary>Note will be displayed to Tech on the mobile app</summary>
    public bool? ShowTech { get; set; }
    /// <summary>Note will be displayed to the customer in some service notifications</summary>
    public bool? ShowCustomer { get; set; }
    /// <summary>Subscription ID this note relates to.</summary>
    public int? ReferenceID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (CustomerID is null) throw new ArgumentException("Required parameter CustomerID is null.", nameof(CustomerID));
        if (CustomerID is not null) d["customerID"] = CustomerID;
        if (Date is null) throw new ArgumentException("Required parameter Date is null.", nameof(Date));
        if (Date is not null) d["date"] = Date;
        if (EmployeeID is not null) d["employeeID"] = EmployeeID;
        if (ContactType is null) throw new ArgumentException("Required parameter ContactType is null.", nameof(ContactType));
        if (ContactType is not null) d["contactType"] = ContactType;
        if (Notes is null) throw new ArgumentException("Required parameter Notes is null.", nameof(Notes));
        if (Notes is not null) d["notes"] = Notes;
        if (SendTo is not null) d["sendTo"] = SendTo;
        if (ShowOnInvoice is null) throw new ArgumentException("Required parameter ShowOnInvoice is null.", nameof(ShowOnInvoice));
        if (ShowOnInvoice is not null) d["showOnInvoice"] = ShowOnInvoice;
        if (CancellationReason is not null) d["cancellationReason"] = CancellationReason;
        if (ShowTech is not null) d["showTech"] = ShowTech;
        if (ShowCustomer is not null) d["showCustomer"] = ShowCustomer;
        if (ReferenceID is not null) d["referenceID"] = ReferenceID;
        return d;
    }
}
