// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesPaymentProfileDeleteRequest
{
    /// <summary>Foreign Key to paymentProfile table</summary>
    public int? PaymentProfileID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (PaymentProfileID is null) throw new ArgumentException("Required parameter PaymentProfileID is null.", nameof(PaymentProfileID));
        if (PaymentProfileID is not null) d["paymentProfileID"] = PaymentProfileID;
        return d;
    }
}
