// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesDiagramUpdateRequest
{
    /// <summary>ID of diagram being updated</summary>
    public int? DiagramID { get; set; }
    /// <summary>e.g. linear footage, square footage, or quantity</summary>
    public int? Measurement { get; set; }
    /// <summary>['SF','LF','QTY']</summary>
    public string? MeasurementUnit { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (DiagramID is null) throw new ArgumentException("Required parameter DiagramID is null.", nameof(DiagramID));
        if (DiagramID is not null) d["diagramID"] = DiagramID;
        if (Measurement is not null) d["measurement"] = Measurement;
        if (MeasurementUnit is not null) d["measurementUnit"] = MeasurementUnit;
        return d;
    }
}
