// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesSubscriptionUpdateLeadStageRequest
{
    /// <summary>Foreign key to subscriptions table.</summary>
    public int? SubscriptionID { get; set; }
    /// <summary>Alternative to subscriptionID. This is the \"SubscriptionID\" sent during an API insert through import/main.</summary>
    public int? SubscriptionLink { get; set; }
    /// <summary>Lead stage ID.</summary>
    public int? StageID { get; set; }
    /// <summary>0 - Convert To Lead, 1 - Convert to subscription (lead won)</summary>
    public int? Status { get; set; }
    /// <summary>Lead Lost Reason</summary>
    public int? LostReason { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (SubscriptionID is null) throw new ArgumentException("Required parameter SubscriptionID is null.", nameof(SubscriptionID));
        if (SubscriptionID is not null) d["subscriptionID"] = SubscriptionID;
        if (SubscriptionLink is not null) d["subscriptionLink"] = SubscriptionLink;
        if (StageID is not null) d["stageID"] = StageID;
        if (Status is not null) d["status"] = Status;
        if (LostReason is not null) d["lostReason"] = LostReason;
        return d;
    }
}
