// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesContractUpdateRequest
{
    /// <summary>ID of contract being updated</summary>
    public int? ContractID { get; set; }
    /// <summary>Description of contract being updated</summary>
    public string? Description { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (ContractID is null) throw new ArgumentException("Required parameter ContractID is null.", nameof(ContractID));
        if (ContractID is not null) d["contractID"] = ContractID;
        if (Description is not null) d["description"] = Description;
        return d;
    }
}
