// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesGenericFlagAssignmentCreateRequest
{
    /// <summary>Foreign key to flag</summary>
    public int? GenericFlagID { get; set; }
    /// <summary>ID of entity being assigned the flag</summary>
    public int? EntityID { get; set; }
    /// <summary>Type of flag.</summary>
    public string? Type { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (GenericFlagID is null) throw new ArgumentException("Required parameter GenericFlagID is null.", nameof(GenericFlagID));
        if (GenericFlagID is not null) d["genericFlagID"] = GenericFlagID;
        if (EntityID is null) throw new ArgumentException("Required parameter EntityID is null.", nameof(EntityID));
        if (EntityID is not null) d["entityID"] = EntityID;
        if (Type is null) throw new ArgumentException("Required parameter Type is null.", nameof(Type));
        if (Type is not null) d["type"] = Type;
        return d;
    }
}
