// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesGenericFlagAssignmentDeleteRequest
{
    public int? GenericFlagAssignmentID { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (GenericFlagAssignmentID is null) throw new ArgumentException("Required parameter GenericFlagAssignmentID is null.", nameof(GenericFlagAssignmentID));
        if (GenericFlagAssignmentID is not null) d["genericFlagAssignmentID"] = GenericFlagAssignmentID;
        return d;
    }
}
