// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesReviewSummaryRequest
{
    /// <summary>Zip codes to summarize</summary>
    public List<object>? ZipCodes { get; set; }
    /// <summary>Cities to summarize</summary>
    public List<object>? Cities { get; set; }
    /// <summary>Foreign key to offices table. Default: officeID associated with the API key sent.</summary>
    public int[]? OfficeIDs { get; set; }
    /// <summary>Foreign key to customers table</summary>
    public int[]? CustomerIDs { get; set; }
    /// <summary>Left bound for feedback time</summary>
    public string? StartTime { get; set; }
    /// <summary>Right bound for feedback time</summary>
    public string? EndTime { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (ZipCodes is not null) d["zipCodes"] = ZipCodes;
        if (Cities is not null) d["cities"] = Cities;
        if (OfficeIDs is not null) d["officeIDs"] = OfficeIDs;
        if (CustomerIDs is not null) d["customerIDs"] = CustomerIDs;
        if (StartTime is not null) d["startTime"] = StartTime;
        if (EndTime is not null) d["endTime"] = EndTime;
        return d;
    }
}
