// <auto-generated>
// Generated from api.md by tools/generate.py. Do not edit by hand.
#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using FieldRoutesApiClient.Core;

namespace FieldRoutesApiClient.Entities;
public sealed class FieldRoutesProductCreateRequest
{
    /// <summary>OfficeID of the product; -1 is available to all offices.</summary>
    public int? OfficeID { get; set; }
    /// <summary>Description of the product</summary>
    public string? Description { get; set; }
    /// <summary>Cost of each product</summary>
    public decimal? Amount { get; set; }
    /// <summary>Set as 1 if the product is taxable</summary>
    public int? Taxable { get; set; }
    /// <summary>Product Code (up to 25 characters)</summary>
    public string? Code { get; set; }
    /// <summary>Product category</summary>
    public string? Category { get; set; }
    /// <summary>Whether or not the product is visible in lists when creating a new addon</summary>
    public int? Visible { get; set; }
    /// <summary>Whether or not the product is visible for sales reps on mobile app</summary>
    public int? SalesVisible { get; set; }
    /// <summary>0 means it shows up only on the service it was added to, 1 means it shows up on every service</summary>
    public int? Recurring { get; set; }

    internal Dictionary<string, object?> ToDictionary()
    {
        var d = new Dictionary<string, object?>();
        if (OfficeID is not null) d["officeID"] = OfficeID;
        if (Description is null) throw new ArgumentException("Required parameter Description is null.", nameof(Description));
        if (Description is not null) d["description"] = Description;
        if (Amount is null) throw new ArgumentException("Required parameter Amount is null.", nameof(Amount));
        if (Amount is not null) d["amount"] = Amount;
        if (Taxable is null) throw new ArgumentException("Required parameter Taxable is null.", nameof(Taxable));
        if (Taxable is not null) d["taxable"] = Taxable;
        if (Code is null) throw new ArgumentException("Required parameter Code is null.", nameof(Code));
        if (Code is not null) d["code"] = Code;
        if (Category is null) throw new ArgumentException("Required parameter Category is null.", nameof(Category));
        if (Category is not null) d["category"] = Category;
        if (Visible is null) throw new ArgumentException("Required parameter Visible is null.", nameof(Visible));
        if (Visible is not null) d["visible"] = Visible;
        if (SalesVisible is null) throw new ArgumentException("Required parameter SalesVisible is null.", nameof(SalesVisible));
        if (SalesVisible is not null) d["salesVisible"] = SalesVisible;
        if (Recurring is null) throw new ArgumentException("Required parameter Recurring is null.", nameof(Recurring));
        if (Recurring is not null) d["recurring"] = Recurring;
        return d;
    }
}
